= Install the {product}
:navtitle: Install the CLI
:description: {product} makes it easier to integrate {product-short} into your applications and workflows by letting you perform common platform tasks for {astra_db} and {astra_stream} from the command line.

Install the {product} to create and manage {astra_db} databases and {astra_stream} tenants from the command line.

== Platform compatibility

The {product} supports the following operating systems:

[cols="1,2"]
|===
|Operating System |Architecture

|Linux
|x86_64, arm64

|macOS
|x86_64, arm64

|Microsoft Windows
|x86_64
|===

== Install the {product}

Select one of the following installation methods and follow the steps to install the {product}.

[tabs,sync-group-id=platforms]
======
macOS and Linux::
+
Select one of the following installation methods to install the {product} on macOS and Linux.
If you prefer to use a package manager, follow the Homebrew instructions instead.
+
[tabs]
=====
Scripted installation (recommended)::
+
--
. Run the following Bash script to install the latest version of the {product}:
+
[source,bash]
----
curl -sSL ibm.biz/astra-cli | sh
----

. When prompted to specify the installation location, press kbd:[Enter] to accept the default location (`~/.astra/cli/`).
+
To install the {product} to a different location, use the binary installation method instead.

. Add the following lines to your shell profile (for example, `~/.zprofile` or `~/.bash_profile`) to make the `astra` command executable from any directory:
+
[source,bash]
----
# Astra CLI shell configuration
eval "$(~/.astra/cli/astra shellenv)"
----

. Reload your shell profile or open a new terminal window.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--

Binary installation::
+
--
. Download the appropriate binary archive for your OS and CPU architecture from https://github.com/datastax/astra-cli/releases[GitHub].

. Extract the archive into the directory where you want to install the {product}.
For example:
+
[source,bash,subs="+quotes"]
----
sudo tar -xzvf astra-macos-arm64.tar.gz -C **INSTALLATION_DIRECTORY**
----

. Add the following lines to your shell profile (for example, `~/.zprofile` or `~/.bash_profile`) to make the `astra` command executable from any directory:
+
[source,bash,subs="+quotes"]
----
# Astra CLI shell configuration
eval "$(**PATH_TO_BINARY** shellenv)"
----
+
Replace `**PATH_TO_BINARY**` with the full path to the `astra` executable in the installation directory.

. Reload your shell profile or open a new terminal window.

. On macOS: Delete the `com.apple.quarantine` attribute from the `astra` binary to remove https://support.apple.com/guide/security/gatekeeper-and-runtime-protection-sec5599b66df/web[macOS Gatekeeper restrictions]:
+
[source,bash]
----
xattr -d com.apple.quarantine $(which astra)
----
+
Alternatively, you can remove these restrictions in your https://support.apple.com/en-us/102445#openanyway[macOS System Settings].

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--
=====

Windows::
+
Select one of the following installation methods to install the {product} on Windows:
+
[tabs]
=====
Scripted installation (recommended)::
+
--
. Run the following PowerShell script to install the latest version of the {product}:
+
[source,shell]
----
powershell -c "irm https://ibm.biz/astra-cli-win | iex"
----

. When prompted to specify the installation location, press kbd:[Enter] to accept the default location (`~\AppData\Local\.astra\cli`).
+
To install the {product} to a different location, use the binary installation method instead.

. Add the following lines to your shell profile to make the `astra` command executable from any directory:
+
[source,shell]
----
TBD
----

. Reload your shell profile or open a new terminal window.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--

Binary installation::
+
--
. Download the `windows` zip file from https://github.com/datastax/astra-cli/releases[GitHub].

. Extract the zip file into the directory where you want to install the {product}:
+
[source,shell,subs="+quotes"]
----
powershell -C "Expand-Archive -Path astra-windows-x86_64.zip -DestinationPath **INSTALLATION_DIRECTORY** -Force"
----

. Add the path to the unzipped `astra.exe` file to your `PATH` environment variable.
To learn how to update environment variables, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].

. Reload your shell profile or open a new terminal window.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--
=====

Homebrew::
+
--
. Install the latest version of the {product} using https://brew.sh/[Homebrew]:
+
[source,bash]
----
brew install datastax/astra-cli/astra
----

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--
======

== Next steps

To connect to {product-short} run your first commands, see xref:use-cli.adoc[].
