= Install the {product}
:navtitle: Install the CLI
:description: {product} makes it easier to integrate {product-short} into your applications and workflows by letting you perform common platform tasks for {astra_db} and {astra_stream} from the command line.

Install the {product} to create and manage {astra_db} databases and {astra_stream} tenants from the command line.

== Platform compatibility

The {product} supports the following operating systems:

[cols="1,2"]
|===
|Operating System |Architecture

|Linux
|x86_64

|macOS
|x86_64, ARM64

|Microsoft Windows
|x86_64
|===

== Install the {product}

Select one of the following installation methods and follow the steps to install the {product}.

[tabs,id=install]
======
Homebrew::
+
--
. Install the {product} using https://brew.sh/[Homebrew]:
+
[source,bash]
----
brew install datastax/astra-cli/astra-cli
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
TBD
----
====

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--

macOS::
+
Select one of the following installation methods to install the {product} on macOS without using Homebrew:
+
[tabs]
=====
Scripted installation (recommended)::
+
--
. Run the following Bash script to install the {product}:
+
[source,bash]
----
sh -c "$(curl -fsSL https://raw.githubusercontent.com/toptobes/astra-cli-pico/master/scripts/install.sh)"
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
    _____            __
   /  _  \   _______/  |_____________
  /  /_\  \ /  ___/\   __\_  __ \__  \
 /    |    \___ \  |  |  |  | \// __ \_
 \____|__  /____  > |__|  |__|  (____  /
         \/     \/                   \/

                    Installer: {product-version}

→ Required tools are available.
→ No existing installation found.

Ready to install Astra CLI ✅

Do you want to install Astra CLI to ~/.astra/cli/? [Y]es/[d]ifferent path/[c]ancel
>
----
====

. When prompted to specify the installation location, press kbd:[Return] to accept the default (`~/.astra/cli/`).
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
→ Using installation dir ~/.astra/cli/.
→ Archive downloaded.
→ Archive verified and extracted.

Astra CLI installed successfully! 🎉

Next steps:

# Append the following to your shell profile (e.g. ~/.bashrc, ~/.zshrc, etc.)
$ eval "$(~/.astra/cli/astra shellenv)"

# Run the following to get started!
$ astra setup
----
====
+
To install the {product} to a different location, use the binary installation method.

. Add the following lines to your shell profile (for example, `~/.zshrc` or `~/.bashrc`) to make the `astra` command executable from any directory:
+
[source,bash]
----
# Astra CLI shell configuration
eval "$(~/.astra/cli/astra shellenv)"
----

. Reload your shell profile or open a new terminal window.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--

Binary installation::
+
--
. Download the latest `macos` archive file for your CPU architecture from https://github.com/toptobes/astra-cli-pico/releases[GitHub].

. Extract the archive into the directory where you want to install the {product}:
+
[source,bash,subs="+quotes"]
----
sudo tar -xzvf astra-macos-**ARCHITECTURE**.tar.gz -C **INSTALLATION_DIRECTORY**
----

. Add the following lines to your shell profile (for example, `~/.zshrc` or `~/.bashrc`) to make the `astra` command executable from any directory:
+
[source,bash,subs="+quotes"]
----
# Astra CLI shell configuration
eval "$(**PATH_TO_EXEC** shellenv)"
----
+
Replace `**PATH_TO_EXEC**` with the full path to the `astra` executable in the installation directory.

. Reload your shell profile or open a new terminal window.

. Run the following command to de-quarantine the binary:
+
[source,bash]
----
xattr -d com.apple.quarantine $(which astra)
----
+
For more information

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--
=====

Windows::
+
Select one of the following installation methods to install the {product} on Windows:
+
[tabs]
=====
Scripted installation (recommended)::
+
--
. Run the following PowerShell script to install the {product}:
+
[source,powershell]
----
powershell -c "irm https://raw.githubusercontent.com/toptobes/astra-cli-pico/master/scripts/install.ps1 | iex"
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
TBD
----
====

. When prompted to specify the installation location, press kbd:[Return] to accept the default (`~\AppData\Local\.astra\cli`).
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
TBD
----
====
+
To install the {product} to a different location, use the binary installation method.

. Add the following lines to your PowerShell profile to make the `astra` command executable from any directory:
+
[source,powershell]
----
TBD
----

. Reload your shell profile or open a new command prompt.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--

Binary installation::
+
--
. Download the latest `windows` zip file from https://github.com/toptobes/astra-cli-pico/releases[GitHub].

. Extract the zip file into the directory where you want to install the {product}:
+
[source,powershell,subs="+quotes"]
----
powershell -Command "Expand-Archive -Path astra-windows-x86_64.zip -DestinationPath **INSTALLATION_DIRECTORY** -Force"
----

. Add the path to the unzipped `astra.exe` file to your `PATH` environment variable.
To learn how to update environment variables, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].

. Reload your shell profile or open a new terminal window.

. Run the `astra` command from any directory to verify successful installation:
+
[source,bash]
----
astra
----
+
The response includes available commands and options for the {product}.
--
=====

Linux::
+
--
TBD
--

Docker::
+
--
TBD
--
======

To set up a new configuration and run your first commands, see xref:use-cli.adoc[].

[#file-locations]
=== Installation file locations

The {product} and its configuration are installed in the following locations:

[cols="1,2"]
|===
|File location |Description

|`~/.astra`
a|The {product} installation directory.

For <<install-curl,curl-based installations>>, the `astra` executable and `astra-init.sh` auto-completion script are located in `~/.astra/cli`.
The `~/.astra/cli` folder is added to the `PATH` environment variable.
_This folder is deleted and recreated when you update or re-install the {product}._

For <<install-homebrew,Homebrew-based installations>>, the `astra` executable and auto-completion script are located in https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location[Homebrew's default prefix] at the following locations:

* Executable: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/bin/astra`
* Auto-completion script: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/etc/bash_completion.d/astra`

|`~/.astrarc`
|The {product} configuration file.

_This file is *not* deleted when you update or re-install the {product}._
|===

