= Install the {product}
:navtitle: Install the CLI
:description: {product} makes it easier to integrate {product-short} into your applications and workflows by letting you perform common platform tasks for {astra_db} and {astra_stream} from the command line.

Install the {product} to create and manage {astra_db} databases and {astra_stream} tenants from the command line.

== Platform compatibility

The {product} supports the following operating systems:

[cols="1,2"]
|===
|Operating System |Architecture

|Linux
|x86_64

|macOS
|x86_64, ARM64

|Microsoft Windows
|x86_64

_Requires https://learn.microsoft.com/en-us/windows/wsl/install[Windows Subsystem for Linux (WSL)]_
|===

== Install the {product}

Select one of the following installation methods and follow the steps to install the {product}.

[tabs,id=install]
======
Homebrew::
+
--
. Install the {product} using https://brew.sh/[Homebrew]:
+
[source,bash]
----
brew install datastax/astra-cli/astra-cli
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
TBD
----
====

. Confirm that the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
The command returns the {product} version that is installed:

[source,console,subs="+attributes"]
----
{product-version}
----
====
--

macOS::
+
--
Select one of the following installation methods to install the {product} on macOS without using Homebrew:

[tabs]
=====
Scripted install (recommended)::
+
. Run the following shell script to install the {product}:
+
[source,bash]
----
sh -c "$(curl -fsSL https://raw.githubusercontent.com/toptobes/astra-cli-pico/master/scripts/install.sh)"
----
+
.Result
[%collapsible]
====
[source,console]
----
TBD
----

. When prompted about where to install the {product}, press kbd:[Return] to accept the default location (`~/.astra/cli/`).
+
To install 
====

Manual install::
+
=====
--

curl::
+
--
You can use `curl` to install the {product} on Linux, macOS, and Windows Subsystem for Linux (WSL):

. Install the {product}:
+
[source,bash]
----
curl -Ls "https://dtsx.io/get-astra-cli" | bash
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----

    _____            __
   /  _  \   _______/  |_____________
  /  /_\  \ /  ___/\   __\_  __ \__  \
 /    |    \___ \  |  |  |  | \// __ \_
 \____|__  /____  > |__|  |__|  (____  /
         \/     \/                   \/

Installing Astra Cli {product-version}  please wait...

Checking prerequisites:
[OK] - Ready to install.
[OK] - unzip command is available
[OK] - curl command is available

Preparing directories:
[OK] - Created /home/USERNAME/.astra/tmp
[OK] - Created /home/USERNAME/.astra/cli
[OK] - Created /home/USERNAME/.astra/scb

Downloading archive:
######################################################################## 100.0%
[OK] - File downloaded
[OK] - Integrity of the archive checked

Extracting and installation:
[OK] - Extraction is successful
[OK] - File moved to /home/USERNAME/.astra/cli
[OK] - Installation cleaned up
[OK] - astra added to /home/USERNAME/.bashrc
[OK] - astra added to /home/USERNAME/.zshrc
[OK] - Installation Successful

Open A NEW TERMINAL and run: astra setup

You can close this window.
----
====
+
The `~/.astra/cli` folder is added to the `PATH` environment variable.
See <<file-locations>> for more information.

. Open a new terminal or restart your existing terminal.

. Confirm that the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
The command returns the {product} version that is installed:

[source,console,subs="+attributes"]
----
{product-version}
----
====
+
include::ROOT:partial$macos-security-notice.adoc[]
--

JVM::
+
--
The {product} is available as a packaged Java application that you can use on any machine running a JVM.

To run the {product} in a JVM, you must have Java 17+ installed.
You can install Java by downloading and installing the latest https://www.oracle.com/java/technologies/downloads/[Oracle JDK]

. Verify that Java is version 17 or higher:
+
[source,bash]
----
java --version
----

. Download the latest release of https://github.com/datastax/astra-cli/releases[astra-cli] image:https://img.shields.io/github/v/release/datastax/astra-cli?label=latest&color=green[alt="Latest astra-cli release on GitHub",link="https://github.com/datastax/astra-cli/releases"]:
+
[source,bash,subs="+attributes"]
----
curl -L -o astra-cli-{product-version}.zip https://github.com/datastax/astra-cli/releases/download/{product-version}/astra-cli-{product-version}.zip
----

. Unzip the archive:
+
[source,bash,subs="+attributes"]
----
unzip astra-cli-{product-version}.zip -d ./astra-cli-{product-version} && cd astra-cli-{product-version}
----

. Confirm that you can successfully run the {product}:
+
[source,bash]
----
java -jar astra-cli.jar --version
----
+
.Result
[%collapsible]
====
The command returns the {product} version that is installed:

[source,console,subs="+attributes"]
----
{product-version}
----
====

You can use all options and suffixes on commands when running the JAR file.
For example:

[source,bash]
----
java -jar ./astra-cli.jar db list --token AstraCS:FZm...
----
--

Docker::
+
--
The {product} is available as an https://hub.docker.com/r/datastax/astra-cli[official Docker image] that you can run in a container.

To install the {product} using Docker, you must have https://docs.docker.com/engine/install/[Docker engine] or https://www.docker.com/products/docker-desktop[Docker desktop] installed.

. Confirm that Docker is installed and running:
+
[source,bash]
----
docker --version
----
+
.Result
[%collapsible]
====
The command returns the Docker version that is installed:

[source,console]
----
Docker version 27.1.1, build 6312585
----
====

. Pull the latest {product} Docker image (`datastax/astra-cli:latest`):
+
[source,bash,subs="+attributes"]
----
docker pull datastax/astra-cli
----
+
[TIP]
====
To pull a specific version of the Docker image, run `docker pull datastax/astra-cli:**TAG**`, replacing `**TAG**` with the version tag of the Docker image you want to pull.
====
+
.Result
[%collapsible]
====
[source,console]
----
Using default tag: latest
latest: Pulling from datastax/astra-cli
7890eb226106: Pull complete
f4455e290156: Pull complete
e6c3f5cd9c43: Pull complete
322cfd5270ff: Pull complete
Digest: sha256:8dcba8115cbae7bcabfc579341611f30860239ee5edbca3938edea4542ca06fb
Status: Downloaded newer image for datastax/astra-cli:latest
docker.io/datastax/astra-cli:latest

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview datastax/astra-cli
----
====

. Confirm that you can successfully run the {product} in a Docker container:
+
[source,bash]
----
docker run -rm datastax/astra-cli --version
----
+
.Result
[%collapsible]
====
The command returns the {product} version that is installed:

[source,console,subs="+attributes"]
----
{product-version}
----
====

. Optional: Run the {product} with a configuration file:
+
[source,bash,subs="+quotes"]
----
docker run -rm -v **CONFIG_FILE**:/work/.astrarc datastax/astra-cli --version
----
+
Replace `**CONFIG_FILE**`with the path to your {product} configuration file.
For example:
+
[source,bash]
----
docker run -rm -v ~/.astrarc:/work/.astrarc datastax/astra-cli --version
----
+
This command mounts the `~/.astrarc` file from your local machine to the `/work/.astrarc` file in the Docker container.
This lets you use your local configuration file when running the {product} in a Docker container.

. Optional: Create a shell alias for running the {product} in a Docker container.
+
You can create a shell alias to eliminate the need to include the `docker run` command whenever you want to run the {product} in a Docker container.
For example, the following command creates an alias named `astra`:
+
[source,bash]
----
alias astra='docker run -rm -v ~/.astrarc:/work/.astrarc datastax/astra-cli'
----
+
You can run this command in your terminal to create a temporary alias for the current session, or you can add it to your shell configuration file so that the alias is available in every new terminal session.
+
After you add the alias, you can use it to run {product} commands in a Docker container using the same syntax as the `astra` binary:
+
[source,bash]
----
astra --version
----
--
======

To set up a new configuration and run your first commands, see xref:use-cli.adoc[].

[#file-locations]
=== Installation file locations

The {product} and its configuration are installed in the following locations:

[cols="1,2"]
|===
|File location |Description

|`~/.astra`
a|The {product} installation directory.

For <<install-curl,curl-based installations>>, the `astra` executable and `astra-init.sh` auto-completion script are located in `~/.astra/cli`.
The `~/.astra/cli` folder is added to the `PATH` environment variable.
_This folder is deleted and recreated when you update or re-install the {product}._

For <<install-homebrew,Homebrew-based installations>>, the `astra` executable and auto-completion script are located in https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location[Homebrew's default prefix] at the following locations:

* Executable: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/bin/astra`
* Auto-completion script: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/etc/bash_completion.d/astra`

|`~/.astrarc`
|The {product} configuration file.

_This file is *not* deleted when you update or re-install the {product}._
|===

[#install-custom-location]
== Install the {product} to a custom location

