= Manage {astra_db} with the {product}
:navtitle: Manage {astra_db}
:embedding-provider-name: NVIDIA
:embedding-provider-name-api: nvidia
:embedding-provider-model-name-api: NV-Embed-QA

Use the {product} to manage your {astra_db} deployments.

[TIP]
====
You can use `**DATABASE_NAME**` instead of `**DATABASE_ID**` in all `astra db` commands, so long as the database name is unique within your organization and your application token has enough permissions to list databases.
====

== Create a database

The {product} can create {db-serverless} and {db-serverless-vector} databases with on-demand (non-PCU) capacity only.
It cannot create {db-classic} databases; however, you can use the {product} to <<get-database-details,get information>> about your existing {db-classic} databases.

If your organization requires that new databases to belong to a xref:astra-db-serverless:administration:provisioned-capacity-units.adoc[PCU group], you must xref:astra-db-serverless:databases:create-database.adoc[use the {astra-ui} or {devops-api} to create databases] because the {product} doesn't support PCU group assignment with database creation.

Use the `astra db create` command to create a new {db-serverless} database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database 'my_serverless_db' does not exist. Creating database 'my_serverless_db' with keyspace 'default_keyspace'
[INFO]  Database 'my_serverless_db' and keyspace 'default_keyspace' are being created.
[INFO]  Database 'my_serverless_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 470346 millis)
[OK]    Database 'my_serverless_db' is ready.
----
====

Use the `--vector` option to create a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** --vector
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database 'my_vector_db' does not exist. Creating database 'my_vector_db' with keyspace 'default_keyspace'
[INFO]  Enabling vector search for database my_vector_db
[INFO]  Database 'my_vector_db' and keyspace 'default_keyspace' are being created.
[INFO]  Database 'my_vector_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_vector_db' has status 'ACTIVE' (took 142712 millis)
[OK]    Database 'my_vector_db' is ready.
----
====

Running `astra db create` without any options deploys the database in an available *Free* region and uses `default_keyspace` as the name for the default keyspace.

If the database already exists but is currently xref:astra-db-serverless:databases:database-statuses.adoc[hibernated], the `astra db create` command <<resume-database,resumes>> the database.

include::ROOT:partial$async-option-active.adoc[]

=== `db create` options

.Expand to see all `db create` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create - Create a database with cli

SYNOPSIS
        astra db create [ --async ] [ {-c | --cloud} <cloud> ]
                [ --capacity-units <CAPACITY UNITS> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {--if-not-exist | --if-not-exists} ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --tier <TIER> ] [ --timeout <timeout> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ] [--]
                <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -c <cloud>, --cloud <cloud>
            Cloud Provider to create a db

        --capacity-units <CAPACITY UNITS>
            Capacity units to create the database with (default 1)

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist, --if-not-exists
            will create a new DB only if none with same name

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Default keyspace created with the Db

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region to provision

        --tier <TIER>
            Tier to create the database in

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 300s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-c`, `-r`, and `-k` options to specify the cloud provider, region, and keyspace name when creating a database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** \
    -c **CLOUD_PROVIDER** \
    -r **REGION** \
    -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database 'my_serverless_db' does not exist. Creating database 'my_serverless_db' with keyspace 'my_keyspace'
[INFO]  Database 'my_serverless_db' and keyspace 'my_keyspace' are being created.
[INFO]  Database 'my_serverless_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 109050 millis)
[OK]    Database 'my_serverless_db' is ready.
----
====

//TODO: Confirm that this no longer applies.
////
The database ID, not the database name, ensures uniqueness within your {astra_db} organization.
Consequently, if you issue the `astra db create` command multiple times, you will create multiple database instances.
To ensure that you don't create a database with the same name as another existing database, use the `--if-not-exist` option:

[source,bash]
----
astra db create demo -r us-east-1 -k keyspace1 --if-not-exist
----
////

== Manage keyspaces

{astra_db} databases store data in <<manage-collections,collections>> and <<manage-tables,tables>>, which exist inside keyspaces.
Each database must have at least one keyspace, and you can create more as needed.

Use the `astra db create-keyspace` command to create a new keyspace in a database:

[source,bash,subs="+quotes"]
----
astra db create-keyspace **DATABASE_ID** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Keyspace  'keyspace2' is creating.
[INFO]  Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' has status 'MAINTENANCE' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 6669 millis)
[OK]    Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' is ready.
[OK]    Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' is ready.
----
====

The database enters *Maintenance* status while creating the keyspace.
When the database returns to *Active* status, you can use the new keyspace.

include::ROOT:partial$async-option-active.adoc[]

[TIP]
======
By default, the {product} returns an error if a keyspace with the same name already exists.
However, if you use the `--if-not-exist` option, the {product} automatically connects to the existing keyspace instead of returning an error.
This option can be useful when invoking the {product} in idempotent scripts.

[source,bash,subs="+quotes"]
----
astra db create-keyspace **DATABASE_ID** -k **KEYSPACE_NAME** --if-not-exist
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Keyspace  'keyspace1' already exists. Connecting to keyspace.
[OK]    Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' is ready.
[OK]    Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' is ready.
----
====
======

Use the `astra db list-keyspaces` command to get a list of the keyspaces in a database:

[source,bash,subs="+quotes"]
----
astra db list-keyspaces **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+
| Name                |
+---------------------+
| keyspace1 (default) |
| keyspace2           |
+---------------------+
----
====

Use the `astra db delete-keyspace` command to delete a keyspace from a database:

[source,bash,subs="+quotes"]
----
astra db delete-keyspace **DATABASE_ID** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' has status 'MAINTENANCE' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 6804 millis)
[OK]    Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc' is ready.
----
====

[WARNING]
====
Deleting a keyspace permanently deletes all collections, tables, and data in the keyspace.
====

The database enters *Maintenance* status while it deletes the keyspace along with any collections, tables, and data within the keyspace.

include::ROOT:partial$async-option-active.adoc[]

If you delete the default keyspace, {astra_db} automatically selects another keyspace to be the default keyspace.

=== `db create-keyspace` options

.Expand to see all `db create-keyspace` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create-keyspace - Create a new keyspace

SYNOPSIS
        astra db create-keyspace [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-not-exist ] {-k | --keyspace} <KEYSPACE> [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist
            will create a new DB only if none with same name

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db list-keyspaces` options

.Expand to see all `db list-keyspaces` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-keyspaces - Display the list of Keyspaces in an database

SYNOPSIS
        astra db list-keyspaces [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db delete-keyspace` options

.Expand to see all `db delete-keyspace` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete-keyspace - Delete an existing keyspace

SYNOPSIS
        astra db delete-keyspace [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                {-k | --keyspace} <KEYSPACE> [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

[#manage-collections]
== Manage collections

xref:astra-db-serverless:databases:manage-collections.adoc[Collections] store semi-structured data, in the form of documents, in {db-serverless-vector} databases.

When you create a collection, you decide if the collection can store structured vector data.
This is known as a _vector-enabled collection_.
For vector-enabled collections, you also decide how to provide embeddings.
You can bring your own embeddings and xref:astra-db-serverless:databases:embedding-generation.adoc[automatically generate embeddings with vectorize].
**You must decide which options you need when you create the collection.**

Use the `astra db create-collection` command to create a new collection in a {db-serverless-vector} database:

[tabs]
======
Bring my own embeddings::
+
--
Use these options if you plan to generate your own embeddings and import them when you load data into your collection:

[source,bash,subs="+quotes"]
----
astra db create-collection **DATABASE_ID** \
    -c **COLLECTION_NAME** \
    -d **DIMENSION** \
    -m **SIMILARITY_METRIC**
----

Replace the following:

* `**COLLECTION_NAME**`: The name of the collection you want to create.
* `**DIMENSION**`: The number of dimensions for the vectors in your dataset.
* (Optional) `**SIMILARITY_METRIC**`: The xref:astra-db-serverless:get-started:concepts.adoc#metrics[similarity metric] that your embedding model will use to compare vectors.
The available metrics are `cosine` (default), `dot_product`, and `euclidean`.

Example:

[source,bash]
----
astra db create-collection 58747660-464b-4085-bef2-c3f3e5401e3d \
    -c my_collection \
    -d 1024 \
    -m dot_product
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been created from db '58747660-464b-4085-bef2-c3f3e5401e3d' on keyspace  'default_keyspace'
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====
--

Use an {product-short}-hosted provider::
+
--
To automatically generate embeddings with xref:astra-db-serverless:databases:embedding-generation.adoc[{astra_db} vectorize], add an embedding provider integration to your collection.
Embedding provider integrations are either {product-short}-hosted or external.

This option uses an {product-short}-hosted provider:

[source,bash,subs="+quotes"]
----
astra db create-collection **DATABASE_ID** \
    -c **COLLECTION_NAME** \
    --embedding-provider **PROVIDER_NAME** \
    --embedding-model **MODEL_NAME** \
    -d **DIMENSION** \
    -m **SIMILARITY_METRIC**
----

Replace the following:

* `**COLLECTION_NAME**`: The name of the collection you want to create.
* `**PROVIDER_NAME**`: The name of the {product-short}-hosted embedding provider.
* `**MODEL_NAME**`: The name of the embedding model that you want to use to generate embeddings.
* (Optional) `**DIMENSION**`: The number of dimensions that you want the generated vectors to have.
You can only set the dimensions if the chosen model supports a range of dimensions.
* (Optional) `**SIMILARITY_METRIC**`: The xref:astra-db-serverless:get-started:concepts.adoc#metrics[similarity metric] that your embedding model will use to compare vectors.
The available metrics are `cosine` (default), `dot_product`, and `euclidean`.

Example:

[source,bash]
----
astra db create-collection 58747660-464b-4085-bef2-c3f3e5401e3d \
    -c my_collection \
    --embedding-provider nvidia \
    --embedding-model NV-Embed-QA \
    -d 1024 \
    -m dot_product
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been created from db '58747660-464b-4085-bef2-c3f3e5401e3d' on keyspace  'default_keyspace'
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====
--

Use an external provider::
+
--
To automatically generate embeddings with xref:astra-db-serverless:databases:embedding-generation.adoc[{astra_db} vectorize], add an embedding provider integration to your collection.
Embedding provider integrations are either {product-short}-hosted or external.

To use an external embedding provider, you must add an xref:astra-db-serverless:databases:embedding-generation.adoc#supported-embedding-providers[embedding provider integration] to your {astra_db} organization, and then you can select that embedding provider when you create a collection:

[source,bash,subs="+quotes"]
----
astra db create-collection **DATABASE_ID** \
    -c **COLLECTION_NAME** \
    --embedding-provider **PROVIDER_NAME** \
    --embedding-model **MODEL_NAME** \
    --embedding-key **PROVIDER_KEY_NAME** \
    -d **DIMENSION** \
    -m **SIMILARITY_METRIC**
----

Replace the following:

* `**COLLECTION_NAME**`: The name of the collection you want to create.
* `**PROVIDER_NAME**`: The name of the {product-short}-hosted embedding provider.
* `**MODEL_NAME**`: The name of the embedding model that you want to use to generate embeddings.
* (Optional) `**PROVIDER_KEY_NAME**`: The name of the provider key that you want to use to authenticate with the external embedding provider.
* (Optional) `**DIMENSION**`: The number of dimensions that you want the generated vectors to have.
You can only set the dimensions if the chosen model supports a range of dimensions.
* (Optional) `**SIMILARITY_METRIC**`: The xref:astra-db-serverless:get-started:concepts.adoc#metrics[similarity metric] that your embedding model will use to compare vectors.
The available metrics are `cosine` (default), `dot_product`, and `euclidean`.

Example:

[source,bash]
----
astra db create-collection 58747660-464b-4085-bef2-c3f3e5401e3d \
    -c my_collection \
    --embedding-provider openai \
    --embedding-model text-embedding-3-small \
    --embedding-key my_openai_key \
    -d 1024 \
    -m dot_product
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been created from db '58747660-464b-4085-bef2-c3f3e5401e3d' on keyspace  'default_keyspace'
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====
--

Non-vector collection::
+
--
To create a collection that is _not_ vector-enabled, omit the `-d` and `-m` options.
Be aware that non-vector collections don't support vector-dependent functionality like vector search.

[source,bash,subs="+quotes"]
----
astra db create-collection **DATABASE_ID** -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been created from db '58747660-464b-4085-bef2-c3f3e5401e3d' on keyspace  'default_keyspace'
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====
--
======

Use the `astra db list-collections` command to get a list of the collections in `default_keyspace`:

[source,bash,subs="+quotes"]
----
astra db list-collections **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+-----------+-------------------+--------------------+--------------+------------------------+
| Name                | DefaultId | Vector Dimension  | Similarity Metric  | AI Provider  | AI Model               |
+---------------------+-----------+-------------------+--------------------+--------------+------------------------+
| my_collection       | default   | 1024              | dot_product        |              |                        |
| my_collection2      | default   | 1024              | dot_product        | nvidia       | NV-Embed-QA            |
| my_collection3      | default   | 1024              | dot_product        | openai       | text-embedding-3-small |
+---------------------+-----------+-------------------+--------------------+--------------+------------------------+
----
====

Use the `astra db describe-collection` command to get information about a specific collection:

[source,bash,subs="+quotes"]
----
astra db describe-collection **DATABASE_ID** -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+-------------------+-----------------------------------------+
| Attribute         | Value                                   |
+-------------------+-----------------------------------------+
| Name              | my_collection                           |
| Estim. Count      | 0                                       |
|                   |                                         |
| Vector:           |                                         |
| Vector Dimension  | 1024                                    |
| Similarity Metric | dot_product                             |
+-------------------+-----------------------------------------+

[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

Use the `astra db truncate-collection` command to clear an existing collection:

[source,bash,subs="+quotes"]
----
astra db truncate-collection **DATABASE_ID** -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been truncated from '58747660-464b-4085-bef2-c3f3e5401e3d'.
----
====

Use the `astra db delete-collection` command to delete a collection:

[source,bash,subs="+quotes"]
----
astra db delete-collection **DATABASE_ID** -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been deleted from '58747660-464b-4085-bef2-c3f3e5401e3d'.
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

=== `db create-collection` options

.Expand to see all `db create-collection` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create-collection - Create a new collection

SYNOPSIS
        astra db create-collection {-c | --collection} <COLLECTION>
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ {-d | --dimension} <DIMENSION> ]
                [ --default-id <DEFAULT_ID> ]
                [ --embedding-key <EMBEDDING_KEY> ]
                [ --embedding-model <EMBEDDING_MODEL> ]
                [ --embedding-provider <EMBEDDING_PROVIDER> ]
                [ --env <Environment> ] [ --if-not-exists ]
                [ --indexing-allow <INDEXING_ALLOW> ]
                [ --indexing-deny <INDEXING_DENY> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ {-m | --metric} <METRIC> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -c <COLLECTION>, --collection <COLLECTION>
            Name of the collection to create

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -d <DIMENSION>, --dimension <DIMENSION>
            Name of the collection to create

        --default-id <DEFAULT_ID>
            Default identifier to use for the collection

        --embedding-key <EMBEDDING_KEY>
            Using Vectorize, embedding key used for shared secret

        --embedding-model <EMBEDDING_MODEL>
            Using Vectorize, embedding mode to use

        --embedding-provider <EMBEDDING_PROVIDER>
            Using Vectorize, embedding provider to use

        --env <Environment>
            Astra Environment to use

        --if-not-exists
            will create a new collection only if none with same name

        --indexing-allow <INDEXING_ALLOW>
            List of attribute to add into index (comma separated)

        --indexing-deny <INDEXING_DENY>
            List of attribute to remove from index (comma separated)

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create the collection

        -m <METRIC>, --metric <METRIC>
            Name of the collection to create

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to create a collection in a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db create-collection **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -c **COLLECTION_NAME** \
    -d **DIMENSION**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been created from db '58747660-464b-4085-bef2-c3f3e5401e3d' on keyspace  'my_keyspace'
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

=== `db list-collections` options

.Expand to see all `db list-collections` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-collections - Display the list of collections in an
        database

SYNOPSIS
        astra db list-collections [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create the collection

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to get a list of the collections in a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db list-collections **DATABASE_ID** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+--------------------------+-----------+-------------------+--------------------+--------------+---------------------+
| Name                     | DefaultId | Vector Dimension  | Similarity Metric  | AI Provider  | AI Model            |
+--------------------------+-----------+-------------------+--------------------+--------------+---------------------+
| my_collection            | default   | 1024              | cosine             |              |                     |
| my_collection_non_vector | default   |                   |                    |              |                     |
+--------------------------+-----------+-------------------+--------------------+--------------+---------------------+
----
====

=== `db describe-collection` options

.Expand to see all `db describe-collection` options
[%collapsible]
====
[source,console]
----
NAME
        astra db describe-collection - Describe an existing collection

SYNOPSIS
        astra db describe-collection {-c | --collection} <COLLECTION>
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -c <COLLECTION>, --collection <COLLECTION>
            Name of the collection

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create the collection

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to get information about a collection in a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db describe-collection **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+-------------------+-----------------------------------------+
| Attribute         | Value                                   |
+-------------------+-----------------------------------------+
| Name              | my_collection                           |
| Estim. Count      | 0                                       |
|                   |                                         |
| Vector:           |                                         |
| Vector Dimension  | 1024                                    |
| Similarity Metric | cosine                                  |
+-------------------+-----------------------------------------+

[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

=== `db truncate-collection` options

.Expand to see all `db truncate-collection` options
[%collapsible]
====
[source,console]
----
NAME
        astra db truncate-collection - Clear an existing collection

SYNOPSIS
        astra db truncate-collection {-c | --collection} <COLLECTION>
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -c <COLLECTION>, --collection <COLLECTION>
            Name of the collection

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to clear the table

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to clear an existing collection in a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db truncate-collection **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been truncated from '58747660-464b-4085-bef2-c3f3e5401e3d'.
----
====

=== `db delete-collection` options

.Expand to see all `db delete-collection` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete-collection - Delete an existing collection

SYNOPSIS
        astra db delete-collection {-c | --collection} <COLLECTION>
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-exists ] [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -c <COLLECTION>, --collection <COLLECTION>
            Name of the collection to delete

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-exists
            will delete the collection only if it exists

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create the collection

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to delete a collection from a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db delete-collection **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -c **COLLECTION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Collection 'my_collection' as been deleted from '58747660-464b-4085-bef2-c3f3e5401e3d'.
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

[#manage-tables]
== Manage tables

xref:astra-db-serverless:databases:manage-collections.adoc[Tables] store structured data, as rows and columns, instead of documents.

You can create tables in {db-serverless-vector} and {db-serverless} databases.
However, the commands described in this section apply only to {db-serverless-vector} databases.

Use the `astra db list-tables` command to get a list of the tables in a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db list-tables **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+
| Name                |
+---------------------+
| students            |
+---------------------+
----
====

Use the `astra db describe-table` command to get information about a specific table:

[source,bash,subs="+quotes"]
----
astra db describe-table **DATABASE_ID** -t **TABLE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+------------------+-----------------------------------------+
| Attribute        | Value                                   |
+------------------+-----------------------------------------+
| Name             | students                                |
|                  |                                         |
| COLUMNS          |                                         |
| email            | TEXT                                    |
| extracurriculars | SET<TEXT>                               |
| grades           | MAP<TEXT, INT>                          |
| graduated        | BOOLEAN                                 |
| graduation_year  | INT                                     |
| name             | TEXT                                    |
| semester_gpas    | LIST<DECIMAL>                           |
| vect_emb         | VECTOR<FLOAT,1024>                      |
|                  |                                         |
| PRIMARY KEY      |                                         |
| Partition Key    | [0] email                               |
+------------------+-----------------------------------------+
----
====

Use the `astra db truncate-table` command to clear an existing table:

[source,bash,subs="+quotes"]
----
astra db truncate-table **DATABASE_ID** -t **TABLE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Table 'students' as been truncated from '58747660-464b-4085-bef2-c3f3e5401e3d'.
----
====

Use the `astra db delete-collection` command to delete a collection from a a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db delete-table **DATABASE_ID** -t **TABLE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Table 'students' as been deleted from '58747660-464b-4085-bef2-c3f3e5401e3d'.
[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
====

=== `db list-tables` options

.Expand to see all `db list-tables` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-tables - Display the list of tables in a
        database/keyspace couple

SYNOPSIS
        astra db list-tables [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db describe-table` options

.Expand to see all `db describe-table` options
[%collapsible]
====
[source,console]
----
NAME
        astra db describe-table - Describe an existing table

SYNOPSIS
        astra db describe-table [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] {-t | --table} <TABLE>
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create the collection

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -t <TABLE>, --table <TABLE>
            Name of the table

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db truncate-table` options

.Expand to see all `db truncate-table` options
[%collapsible]
====
[source,console]
----
NAME
        astra db truncate-table - Clear an existing table

SYNOPSIS
        astra db truncate-table [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] {-t | --table} <TABLE>
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to clear the table

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -t <TABLE>, --table <TABLE>
            Name of the table

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db delete-table` options

.Expand to see all `db delete-table` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete-table - Delete an existing table

SYNOPSIS
        astra db delete-table [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-exists ] [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] {-t | --table} <TABLE>
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-exists
            will delete the table only if it exists

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to delete the table

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -t <TABLE>, --table <TABLE>
            Name of the table

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

== Manage embedding providers

Use the `astra db list-embedding-providers` command to get a list of the embedding provider integrations that are available for a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db list-embedding-providers **DATABASE_ID**
----

.Result
[%collapsible]
======
The following result is for example purposes only.
Supported embedding providers and options can change.

[source,console]
----
+----------------------+--------------------------+--------+------------+---------+----------+
| Key                  | DisplayName              | Models | Parameters | Au.Head | S.Secret |
+----------------------+--------------------------+--------+------------+---------+----------+
| cohere               | Cohere                   | 3      | 0          | ■       | ■        |
| openai               | OpenAI                   | 3      | 2          | ■       | ■        |
| huggingfaceDedicated | Hugging Face - Dedicated | 1      | 3          | ■       | ■        |
| azureOpenAI          | Azure OpenAI             | 3      | 2          | ■       | ■        |
| bedrock              | Amazon Bedrock           | 2      | 1          | ■       | ■        |
| jinaAI               | Jina AI                  | 5      | 0          | ■       | ■        |
| voyageAI             | Voyage AI                | 7      | 1          | ■       | ■        |
| upstageAI            | Upstage                  | 1      | 0          | ■       | ■        |
| huggingface          | Hugging Face - Serverless| 6      | 0          | ■       | ■        |
| nvidia               | Nvidia                   | 1      | 0          |         |          |
| mistral              | Mistral AI               | 1      | 0          | ■       | ■        |
+----------------------+--------------------------+--------+------------+---------+----------+
----
======

Use the `astra db describe-embedding-provider` command to get information about a specific embedding provider integration:

[source,bash,subs="+quotes"]
----
astra db describe-embedding-provider **DATABASE_ID** -ep **PROVIDER_NAME**
----

The `**PROVIDER_NAME**` is the name listed in the `Key` column in the output of the `astra db list-embedding-providers` command.

.Result
[%collapsible]
======
The following result is for example purposes only.
Supported embedding providers and options can change.

[source,console]
----
+-------------------+---------------------------------------------------------------------------------------------+
| Attribute         | Value                                                                                       |
+-------------------+---------------------------------------------------------------------------------------------+
| Key               | openai                                                                                      |
| DisplayName       | OpenAI                                                                                      |
| Parameters        | [0] organizationId (STRING)                                                                 |
|                   | [1] projectId (STRING)                                                                      |
| Models:           |                                                                                             |
| Name              | text-embedding-3-small                                                                      |
| Parameters        | [0] vectorDimension (number) , defaultValue=1536                                            |
| Name              | text-embedding-3-large                                                                      |
| Parameters        | [0] vectorDimension (number) , defaultValue=3072                                            |
| Name              | text-embedding-ada-002                                                                      |
| Vector Dimension  | 1536                                                                                        |
| Header Auth:      |                                                                                             |
| Tokens            | [0] forwarded=Authorization, accepted=x-embedding-api-key                                   |
| Shar.Secret Auth: |                                                                                             |
| Tokens            | [0] forwarded=Authorization, accepted=providerKey                                           |
| Supported Auth:   |                                                                                             |
| Authentication    | [0] NONE: []                                                                                |
|                   | [1] SHARED_SECRET: [EmbeddingProvider.Token(forwarded=Authorization, accepted=providerKey)] |
|                   | [2] HEADER: [EmbeddingProvider.Token(forwarded=Authorization, accepted=x-embedding-api-key)]|
+-------------------+---------------------------------------------------------------------------------------------+

[OK]    Database '58747660-464b-4085-bef2-c3f3e5401e3d' is ready.
----
======

=== `db list-embedding-providers` options

.Expand to see all `db list-embedding-providers` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-embedding-providers - Display the list of embedding
        providers in an database

SYNOPSIS
        astra db list-embedding-providers
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db describe-embedding-provider` options

.Expand to see all `db describe-embedding-provider` options
[%collapsible]
====
[source,console]
----
NAME
        astra db describe-embedding-provider - Describe an existing embedding
        provider

SYNOPSIS
        astra db describe-embedding-provider
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                {-ep | --embedding-provider} <EMBEDDING_PROVIDER>
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -ep <EMBEDDING_PROVIDER>, --embedding-provider <EMBEDDING_PROVIDER>
            Key of the embedding provider

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

[#get-database-details]
== Get database details

Use the `astra db list` command to get a list of all the databases in your organization:

[source,bash]
----
astra db list
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| Name                | id                                   | Regions   | Cloud | V | Status    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| my_serverless_db    | 51d23de8-9fd9-487c-9c46-c8e1abdb251b | us-east1  | gcp   |   | ACTIVE    |
| my_vector_db        | 6fabb532-a3ac-4780-a1bc-d984531aed76 | us-east1  | gcp   | ■ | ACTIVE    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
----
====

Use the `astra db get` or `astra db describe` command to get information about a specific database:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_ID**
----

[source,bash,subs="+quotes"]
----
astra db describe **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+------------------+-----------------------------------------+
| Attribute        | Value                                   |
+------------------+-----------------------------------------+
| Name             | my_serverless_db                        |
| id               | 96b1b6e3-5288-4cef-8a41-d4f1d36bbfca    |
| Cloud            | GCP                                     |
| Regions          | us-east1                                |
| Status           | ACTIVE                                  |
| Vector           | Disabled                                |
| Default Keyspace | default_keyspace                        |
| Creation Time    | 2025-01-22T21:21:14Z                    |
| Keyspaces        | [0] default_keyspace                    |
| Regions          | [0] us-east1                            |
+------------------+-----------------------------------------+
----
====

Use the `astra db status` command to get the status of a specific database:

[source,bash,subs="+quotes"]
----
astra db status **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Database '96b1b6e3-5288-4cef-8a41-d4f1d36bbfca' has status 'ACTIVE'
----
====

=== `db list` options

.Expand to see all `db list` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled
----
====

Use the `--vector` option to list only {db-serverless-vector} databases:

[source,bash]
----
astra db list --vector
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| Name                | id                                   | Regions   | Cloud | V | Status    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| my_vector_db        | ebae8d5a-4848-44c9-8485-87e413b60549 | us-east1  | gcp   | ■ | ACTIVE    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
----
====

=== `db get` options

.Expand to see all ``db get` options
[%collapsible]
====
[source,console]
----
NAME
        astra db get - Show details of a database

SYNOPSIS
        astra db get [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --key} <Key> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <Key>, --key <Key>
            Show value for a property among: 'id', 'status', 'cloud',
            'keyspace', 'keyspaces', 'region', 'regions'

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db describe` options

.Expand to see all `db describe` options
[%collapsible]
====
[source,console]
----
NAME
        astra db describe - Show details of a database

SYNOPSIS
        astra db describe [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --key} <Key> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <Key>, --key <Key>
            Show value for a property among: 'id', 'status', 'cloud',
            'keyspace', 'keyspaces', 'region', 'regions'

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db status` options

.Expand to see all `db status` options
[%collapsible]
====
[source,console]
----
NAME
        astra db status - Show status of a database

SYNOPSIS
        astra db status [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

== Get a list of available {astra_db} regions

Use the `astra db list-regions-serverless` command to get a list of available regions that support {db-serverless} databases:

[source,bash]
----
astra db list-regions-serverless
----

Use the `astra db list-regions-vector` command to get a list of available cloud provider regions that support {db-serverless-vector} databases:

[source,bash]
----
astra db list-regions-vector
----

Use the `astra db list-regions-classic` command to get a list of available cloud provider regions that support {db-classic} databases:

[source,bash]
----
astra db list-regions-classic
----

.Result
[%collapsible]
====
The result for each `list-regions-*` command is a table with `Cloud Provider`, `Region`, and `Full Name` columns.
`Full Name` can be empty or contain the region's name and location (city, state, or country).

[source,console,subs="+quotes"]
----
+-----------------+---------------------+-------------------------------+
| Cloud Provider  | Region              | Full Name                     |
+-----------------+---------------------+-------------------------------+
| **PROVIDER**    | **REGION**          | **NAME**                      |
+-----------------+---------------------+-------------------------------+
----
====

=== `db list-regions-serverless` options

.Expand to see all `db list-regions-serverless` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-regions-serverless - Show available regions (serverless).

SYNOPSIS
        astra db list-regions-serverless [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----
====

=== `db list-regions-vector` options

.Expand to see all `db list-regions-vector` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-regions-vector - Show available regions (vector).

SYNOPSIS
        astra db list-regions-vector [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----
====

=== `db list-regions-classic` options

.Expand to see all `db list-regions-classic` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-regions-classic - Show available regions (classic).

SYNOPSIS
        astra db list-regions-classic [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----
====

=== `db list-clouds` options

.Expand to see all `db list-clouds` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-clouds - Show available clouds

SYNOPSIS
        astra db list-clouds [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----
====

[#configure-multiple-regions]
== Configure multiple regions

Use the `astra db create-region` command to deploy a database to an additional region:

[source,bash,subs="+quotes"]
----
astra db create-region **DATABASE_ID** -r **REGION**
----

The database enters *Maintenance* status while provisioning and replicating data to the new region.
Some functions are limited while in *Maintenance* status.

If your organization requires use of xref:astra-db-serverless:administration:provisioned-capacity-units.adoc[PCU groups], you must xref:astra-db-serverless:databases:manage-regions.adoc[use the {astra-ui} or {devops-api} to add regions] because the {product} doesn't support PCU group assignment when adding a region.

For more information, including requirements and costs for additional regions, see xref:astra-db-serverless:databases:manage-regions.adoc[].

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] UNAVAILABLE: Database 'my_serverless_db' has been found but operation cannot be processed due to invalid state (ACTIVE) expected (ACTIVE)
.Result
[%collapsible]
====
[source,console]
----

----
====
////

Use the `astra db list-regions` command to list the regions where a database is deployed:

[source,bash,subs="+quotes"]
----
astra db list-regions **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+----------------+---------------------+----------------+----------------+
| Cloud Provider | Region              | Tier           | Status         |
+----------------+---------------------+----------------+----------------+
| aws            | us-east-2           | serverless     |                |
| aws            | us-east-1 (default) | serverless     |                |
+----------------+---------------------+----------------+----------------+
----
====

Use the `astra db delete-region` command to remove a region from a database:

[source,bash,subs="+quotes"]
----
astra db delete-region **DATABASE_ID** -r **REGION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Region 'us-west1' is deleting.
[OK]    Region us-west1 has been deleted
----
====

[IMPORTANT]
====
You cannot remove the primary (default) region, which is the first region selected when you created the database.

When you remove a region, any connections to the deleted region are also removed.
However, to avoid data loss, all data is replicated to the other regions before the region is deleted.
====

=== `db create-region` options

.Expand to see all `db create-region` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create-region - Expand database to a new region

SYNOPSIS
        astra db create-region [ --async ] [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-not-exist ] [ --no-color ] [ {-o | --output} <FORMAT> ]
                {-r | --region} <REGION> [ {-t | --tier} <CLOUD> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will wait until the database become ACTIVE

        -c <CLOUD>, --cloud <CLOUD>
            Name of the cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist
            will create a new DB only if none with same name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <REGION>, --region <REGION>
            Name of the region to create

        -t <CLOUD>, --tier <CLOUD>
            Name of the tiers

        --timeout <timeout>
            Max wait time in seconds, default+1800, 0 = no timeout.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db list-regions` options

.Expand to see all `db list-regions` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-regions - List regions for a database

SYNOPSIS
        astra db list-regions [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db delete-region` options

.Expand to see all `db delete-region` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete-region - Delete a region from a database

SYNOPSIS
        astra db delete-region [ --async ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                {-r | --region} <REGION> [ --timeout <timeout> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --wait ] [--]
                <DB>

OPTIONS
        --async
            Will wait until the database become ACTIVE

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <REGION>, --region <REGION>
            Name of the region to create

        --timeout <timeout>
            Max wait time in seconds, default+1800, 0 = no timeout.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

[#resume-database]
== Resume a hibernated database

Use the `astra db resume` command to resume a xref:astra-db-serverless:databases:database-statuses.adoc[hibernated] database:

[source,bash,subs="+quotes"]
----
astra db resume **DATABASE_ID**
----

Resuming the database may take a few minutes.

include::ROOT:partial$async-option-active.adoc[]

=== `db resume` options

.Expand to see all `db resume` options
[%collapsible]
====
[source,console]
----
NAME
        astra db resume - Resume a db if needed

SYNOPSIS
        astra db resume [ --async ] [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 180s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

== Terminate a database

[WARNING]
====
Terminating a database permanently deletes all of its data, including xref:astra-db-serverless:databases:backup-restore.adoc[automatic backups].
You cannot undo this action.
====

Use the `astra db delete` command to terminate a database:

[source,bash,subs="+quotes"]
----
astra db delete **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Deleting Database '26054aa9-eb37-4d88-b343-7c934cd1d7bc'
[OK]    Database 26054aa9-eb37-4d88-b343-7c934cd1d7bc has been deleted
----
====

The database enters *Terminating* status while deletion occurs.

By default, the command runs synchronously and doesn't return the command prompt until the database reaches *Terminated* or *Error* status.
To run the command _asynchronously_, add the `--async` option.

=== `db delete` options

.Expand to see all `db delete` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete - Delete an existing database

SYNOPSIS
        astra db delete [ --async ] [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 500s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

== Get database API endpoints

Use the `get-endpoint-swagger` command to get the Swagger UI endpoint for a database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-swagger **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
https://26054aa9-eb37-4d88-b343-7c934cd1d7bc-us-east-1.apps.astra.datastax.com/api/rest/swagger-ui/
----
====

Use the `get-endpoint-api` command to get the JSON API endpoint for a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-api **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
https://26054aa9-eb37-4d88-b343-7c934cd1d7bc-us-east-1.apps.astra.datastax.com/api/rest
----
====

Use the `get-endpoint-playground` command to get the GraphQL playground endpoint for a non-vector database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-playground **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
https://26054aa9-eb37-4d88-b343-7c934cd1d7bc-us-east-1.apps.astra.datastax.com/api/playground
----
====

=== `db get-endpoint-swagger` options

.Expand to see all `db get-endpoint-swagger` options
[%collapsible]
====
[source,console]
----
NAME
        astra db get-endpoint-swagger - Open the swagger user interface

SYNOPSIS
        astra db get-endpoint-swagger [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db get-endpoint-api` options

.Expand to see all `db get-endpoint-api` options
[%collapsible]
====
[source,console]
----
NAME
        astra db get-endpoint-api - Open the json api endpoint

SYNOPSIS
        astra db get-endpoint-api [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db get-endpoint-playground` options

.Expand to see all `db get-endpoint-playground` options
[%collapsible]
====
[source,console]
----
NAME
        astra db get-endpoint-playground - Expand database to a new region

SYNOPSIS
        astra db get-endpoint-playground
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

[#cqlsh]
== Use cqlsh

`cqlsh` is an interface that you can use to issue xref:astra@cql:ROOT:index.adoc[{cass-short} Query Language (CQL)] commands to your database.
The {product} provides built-in `cqlsh` support by downloading, installing, configuring, and wapping the `cqlsh` utility.
This can act as a convenient alternative to installing and configuring a xref:astra-db-serverless:cql:develop-with-cql.adoc#connect-to-the-cql-shell[standalone cqlsh].

To use `cqlsh` commands, you must have a supported version of Python installed on your system.
The underlying `cqlsh` utility requires Python 2.7 (with TLS support) or Python 3.6--3.11.
Python versions 3.12 and later are not supported.
For more details, see this https://support.datastax.com/s/article/cqlsh-may-fail-with-A-Python-installation-with-SSL-is-required-to-connect-to-a-cloud-cluster-when-connecting-to-Astra[Support article]

Use the `astra db cqlsh` command to start `cqlsh` in interactive mode:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Downloading Cqlshell, please wait...
[INFO]  Installing  archive, please wait...
[INFO]  Cqlsh is starting, please wait for connection establishment...
Connected to cndb at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
token@cqlsh>
----
====

Type `exit` or `quit;` and press kbd:[Return] to exit `cqlsh`.

The first time you use the `astra db cqlsh` command, the {product} downloads and installs the `cqlsh` utility to the {product} installation directory (`~/.astra/cqlsh-astra`).
The {product} also downloads the {scb} for each database you connect to and stores the {scb-short} zip files in the `~/.astra/scb` directory.

[TIP]
======
If the {product} reports `ModuleNotFoundError`, check that you have a supported version of Python available in your terminal:

[source,bash]
----
python -V
----

.Result
[%collapsible]
====
[source,console]
----
Python 3.11.10
----
====
======

=== `db cqlsh` options

.Expand to see all `db cqlsh` options
[%collapsible]
====
[source,console]
----
NAME
        astra db cqlsh - Start Cqlsh

SYNOPSIS
        astra db cqlsh [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ --connect-timeout <TIMEOUT> ] [ --debug ]
                [ {-e | --execute} <STATEMENT> ] [ --encoding <ENCODING> ]
                [ --env <Environment> ] [ {-f | --file} <FILE> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --request-timeout <TIMEOUT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --version ]
                [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --connect-timeout <TIMEOUT>
            Connection timeout in seconds (default is 10

        --debug
            Show additional debugging information.

        -e <STATEMENT>, --execute <STATEMENT>
            Execute the statement and quit.

        --encoding <ENCODING>
            Output encoding. Default encoding: utf8.

        --env <Environment>
            Astra Environment to use

        -f <FILE>, --file <FILE>
            Execute commands from a CQL file, then exit.

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Authenticate to the given keyspace.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --request-timeout <TIMEOUT>
            Request timeout in seconds (default is 20

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --version
            Display information of cqlsh.

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-k` / `--keyspace` option to connect directly to a specific keyspace:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
Connected to cndb at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
token@cqlsh:keyspace2>
----
====

Use the `-e` / `--execute` option to execute a CQL statement:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID** -e "describe keyspaces;"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

system_auth    data_endpoint_auth  system_traces
datastax_sla   default_keyspace    system_virtual_schema
system_schema  system              system_views
----
====

Use the `-f` / `--file` option to execute a CQL file:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID** -f sample.cql
----

.Example CQL file
[%collapsible]
====
.sample.cql
[source,cql]
----
-- Use a specific keyspace
USE keyspace1;

-- Create a table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    name TEXT,
    email TEXT
);

-- Insert some data
INSERT INTO users (id, name, email) VALUES (uuid(), 'Alice', 'alice@example.com');
INSERT INTO users (id, name, email) VALUES (uuid(), 'Bob', 'bob@example.com');

-- Query the data
SELECT * FROM users;
----
====

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 id                                   | email             | name
--------------------------------------+-------------------+-------
 62a32f14-5432-4a28-add7-761d3626373e |   bob@example.com |   Bob
 0a489e53-0eed-4385-81a6-081143c228f1 | alice@example.com | Alice

(2 rows)
----
====

[TIP]
======
You can also execute a CQL file using the `xref:astra@cql:reference:cqlsh-commands/source.adoc[]` CQL command:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID** -e "SOURCE 'sample.cql'"
----

.Result
[%collapsible]
====
[source,cql]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 id                                   | email             | name
--------------------------------------+-------------------+-------
 62a32f14-5432-4a28-add7-761d3626373e |   bob@example.com |   Bob
 0a489e53-0eed-4385-81a6-081143c228f1 | alice@example.com | Alice

(2 rows)
----
====
======

== Use DataStax Bulk Loader

The xref:dsbulk:overview:dsbulk-about.adoc[DataStax Bulk Loader (DSBulk)] lets you load, unload, and count data in your database tables.
The {product} provides built-in DSBulk support by downloading, installing, configuring, and wapping the `dsbulk` utility.

The {product} exposes DSBulk functionality through the `astra db load`, `astra db unload`, and `astra db count` commands.

The first time you run `astra db load`, `astra db unload`, or `astra db count` commands, the {product} downloads and installs the `dsbulk` utility to the {product} installation directory (`~/.astra/dsbulk-*`).
The {product} also downloads the {scb} for each database you connect to and stores the {scb-short} zip files in the `~/.astra/scb` directory.

Use the `astra db load` command to load data from a file into a database table:

[source,bash,subs="+quotes"]
----
astra db load **DATABASE_ID** \
  -k **KEYSPACE_NAME** \
  -t **TABLE_NAME** \
  -url **FILE_LOCATION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Downloading Dsbulk, please wait...
[INFO]  Installing  archive, please wait...
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk load -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url cities.csv -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
Operation directory: /Users/USERNAME/logs/LOAD_20250123-020734-995267
Setting executor.maxPerSecond not set when connecting to DataStax Astra: applying a limit of 27,000 ops/second based on the number of coordinators (9).
If your Astra database has higher limits, please define executor.maxPerSecond explicitly.
  total | failed | rows/s |  p50ms |  p99ms | p999ms | batches
148,266 |      0 | 19,588 | 240.82 | 771.75 | 964.69 |   30.72
Operation LOAD_20250123-020734-995267 completed successfully in 7 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/LOAD_20250123-020734-995267/checkpoint.csv
----
====

[TIP]
======
You can use the `cqlsh` command to check that the data imported successfully:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_ID** -e \
"SELECT * FROM **KEYSPACE_NAME**.**TABLE_NAME** LIMIT 20;"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 country_name | name                | country_code | country_id | id   | latitude | longitude | state_code | state_id | state_name          | wikidataid
--------------+---------------------+--------------+------------+------+----------+-----------+------------+----------+---------------------+------------
   Bangladesh |             Azimpur |           BD |         19 | 8454 |  23.7298 |   90.3854 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Badarganj |           BD |         19 | 8455 | 25.67419 |  89.05377 |         55 |      759 |    Rangpur District |       null
   Bangladesh |            Bagerhat |           BD |         19 | 8456 |     22.4 |     89.75 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bandarban |           BD |         19 | 8457 |       22 |  92.33333 |          B |      803 | Chittagong Division |       null
   Bangladesh |          Baniachang |           BD |         19 | 8458 | 24.51863 |  91.35787 |         60 |      767 |     Sylhet District |       null
   Bangladesh |             Barguna |           BD |         19 | 8459 | 22.13333 |  90.13333 |         06 |      818 |    Barisal District |       null
   Bangladesh |             Barisal |           BD |         19 | 8460 |     22.8 |      90.5 |         06 |      818 |    Barisal District |       null
   Bangladesh |                Bera |           BD |         19 | 8462 | 24.07821 |  89.63262 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |       Bhairab Bāzār |           BD |         19 | 8463 |  24.0524 |   90.9764 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Bherāmāra |           BD |         19 | 8464 | 24.02452 |  88.99234 |         27 |      811 |     Khulna District |       null
   Bangladesh |               Bhola |           BD |         19 | 8465 | 22.36667 |  90.81667 |         06 |      818 |    Barisal District |       null
   Bangladesh |           Bhāndāria |           BD |         19 | 8466 | 22.48898 |  90.06273 |         06 |      818 |    Barisal District |       null
   Bangladesh | Bhātpāra Abhaynagar |           BD |         19 | 8467 | 23.01472 |  89.43936 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bibir Hat |           BD |         19 | 8468 | 22.68347 |  91.79058 |          B |      803 | Chittagong Division |       null
   Bangladesh |               Bogra |           BD |         19 | 8469 | 24.78333 |     89.35 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |        Brahmanbaria |           BD |         19 | 8470 | 23.98333 |  91.16667 |          B |      803 | Chittagong Division |       null
   Bangladesh |         Burhānuddin |           BD |         19 | 8471 | 22.49518 |  90.72391 |         06 |      818 |    Barisal District |       null
   Bangladesh |            Bājitpur |           BD |         19 | 8472 | 24.21623 |  90.95002 |         13 |      771 |      Dhaka District |       null
   Bangladesh |            Chandpur |           BD |         19 | 8474 |    23.25 |  90.83333 |          B |      803 | Chittagong Division |       null
   Bangladesh |    Chapai Nababganj |           BD |         19 | 8475 | 24.68333 |     88.25 |         54 |      813 |   Rajshahi District |       null

(20 rows)
----
====
======

Use the `astra db unload` command to unload database table rows into a file:

[source,bash,subs="+quotes"]
----
astra db unload **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -t **TABLE_NAME** \
    -url **FILE_LOCATION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk unload -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url unloaded_data -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/UNLOAD_20250123-021231-557959
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 29,767 | 281.25 | 591.40 | 591.40
Operation UNLOAD_20250123-021231-557959 completed successfully in 4 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/UNLOAD_20250123-021231-557959/checkpoint.csv
----
====

Use the `astra db count` command to get information about loaded data:

[source,bash,subs="+quotes"]
----
astra db count **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    -t **TABLE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk count -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/COUNT_20250123-021120-127216
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 65,674 | 213.18 | 329.25 | 329.25
Operation COUNT_20250123-021120-127216 completed successfully in 1 second.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/COUNT_20250123-021120-127216/checkpoint.csv
134574
----
====

=== `db load` options

.Expand to see all `db load` options
[%collapsible]
====
[source,console]
----
NAME
        astra db load - Load data leveraging DSBulk

SYNOPSIS
        astra db load [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ -delim <delim> ]
                [ -dryRun ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                [ -encoding <ENCODING> ] [ --env <Environment> ]
                [ -header <header> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ -logDir <log directory> ]
                [ {-m | --schema.mapping} <mapping> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ]
                [ -maxErrors <maxErrors> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ --schema.allowMissingFields <allowMissingFields> ]
                [ -skipRecords <skipRecords> ] [ {-t | --table} <TABLE> ]
                [ --token <AUTH_TOKEN> ] -url <url> [ {-v | --verbose} ] [--]
                <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -delim <delim>
            Character(s) use as field delimiter.

        -dryRun
            Enable or disable dry-run mode.

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -header <header>
            Read, Write Header in input file

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -m <mapping>, --schema.mapping <mapping>
            Field-to-column mapping to use.

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        -maxErrors <maxErrors>
            Maximum number of errors before aborting the operation.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        --schema.allowMissingFields <allowMissingFields>
            Ease the mapping

        -skipRecords <skipRecords>
            Lines to skip before readind

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -url <url>
            File location to load data

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db unload` options

.Expand to see all `db unload` options
[%collapsible]
====
[source,console]
----
NAME
        astra db unload - Unload data leveraging DSBulk

SYNOPSIS
        astra db unload [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ -delim <delim> ]
                [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -encoding <ENCODING> ]
                [ --env <Environment> ] [ -header <header> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ -logDir <log directory> ]
                [ {-m | --schema.mapping} <mapping> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ]
                [ -maxErrors <maxErrors> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ -skipRecords <skipRecords> ] [ {-t | --table} <TABLE> ]
                [ --token <AUTH_TOKEN> ] [ -url <url> ] [ {-v | --verbose} ]
                [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -delim <delim>
            The character(s) to use as field delimiter. Field delimiters
            containing more than one character are accepted.

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -header <header>
            Enable or disable whether the files to read or write begin with a
            header line.

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -m <mapping>, --schema.mapping <mapping>
            The field-to-column mapping to use, that applies to both loading
            and unloading; ignored when counting.

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        -maxErrors <maxErrors>
            The maximum number of errors to tolerate before aborting the entire
            operation.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        -skipRecords <skipRecords>
            The number of records to skip from each input file before the
            parser can begin to execute. Note that if the file contains a
            header line, that line is not counted as a valid record. This
            setting is ignored when writing.

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -url <url>
            The URL or path of the resource(s) to read from or write to.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db count` options

.Expand to see all `db count` options
[%collapsible]
====
[source,console]
----
NAME
        astra db count - Count items for a table, a query

SYNOPSIS
        astra db count [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -encoding <ENCODING> ]
                [ --env <Environment> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ -logDir <log directory> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ {-t | --table} <TABLE> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== Complete DSBulk example

The following end-to-end example shows how to use the {product}'s built-in DSBulk support to load data into a database, get information about the data, and unload the data into CSV files:

. Create an {astra_db} {db-serverless} database:
+
[source,bash]
----
astra db create dsbulk_demo_db -k dsbulk_demo_keyspace
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database 'dsbulk_demo_db' does not exist. Creating database 'dsbulk_demo_db' with keyspace 'dsbulk_demo_keyspace'
[INFO]  Database 'dsbulk_demo_db' and keyspace 'dsbulk_demo_keyspace' are being created.
[INFO]  Database 'dsbulk_demo_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'dsbulk_demo_db' has status 'ACTIVE' (took 471460 millis)
[OK]    Database 'dsbulk_demo_db' is ready.
----
====

. Download the xref:ROOT:attachment$cities.csv[cities.csv] file and move it to the directory where you run {product} commands.
+
The `cities.csv` dataset contains information about cities around the world:
+
.cities.csv
[source,csv]
----
id,name,state_id,state_code,state_name,country_id,country_code,country_name,latitude,longitude,wikiDataId
52,Ashkāsham,3901,BDS,Badakhshan,1,AF,Afghanistan,36.68333000,71.53333000,Q4805192
68,Fayzabad,3901,BDS,Badakhshan,1,AF,Afghanistan,37.11664000,70.58002000,Q156558
...
----

. Create a table in your database to store your data.
+
.. Start `cqlsh` in interactive mode:
+
[source,bash]
----
astra db cqlsh dsbulk_demo_db -k dsbulk_demo_keyspace
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
Connected to cndb at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
token@cqlsh:dsbulk_demo_keyspace>
----
====
+
.. Copy and paste the following CQL command into the `cqlsh` prompt and press kbd:[Return]:
+
[source,cql]
----
CREATE TABLE cities_by_country (
    country_name text,
    name text,
    id int,
    state_id text,
    state_code text,
    state_name text,
    country_id text,
    country_code text,
    latitude double,
    longitude double,
    wikiDataId text,
    PRIMARY KEY ((country_name), name)
);
----
+
This command creates a table named `cities_by_country` with the appropriate schema for the `cities.csv` dataset.
+
.. Type `exit` or `quit;` and press kbd:[Return] to exit `cqlsh`.

. Load the data from the `cities.csv` file into the `cities_by_country` table that you just created in your database:
+
[source,bash]
----
astra db load dsbulk_demo_db \
  -k dsbulk_demo_keyspace \
  -t cities_by_country \
  -url cities.csv
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk load -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url cities.csv -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
Operation directory: /Users/USERNAME/logs/LOAD_20250123-020734-995267
Setting executor.maxPerSecond not set when connecting to DataStax Astra: applying a limit of 27,000 ops/second based on the number of coordinators (9).
If your Astra database has higher limits, please define executor.maxPerSecond explicitly.
  total | failed | rows/s |  p50ms |  p99ms | p999ms | batches
148,266 |      0 | 19,588 | 240.82 | 771.75 | 964.69 |   30.72
Operation LOAD_20250123-020734-995267 completed successfully in 7 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/LOAD_20250123-020734-995267/checkpoint.csv
----
====

. Confirm that the data loaded successfully:
+
[source,bash]
----
astra db cqlsh dsbulk_demo_db -e \
"select * from dsbulk_demo_keyspace.cities_by_country LIMIT 20;"
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 country_name | name                | country_code | country_id | id   | latitude | longitude | state_code | state_id | state_name          | wikidataid
--------------+---------------------+--------------+------------+------+----------+-----------+------------+----------+---------------------+------------
   Bangladesh |             Azimpur |           BD |         19 | 8454 |  23.7298 |   90.3854 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Badarganj |           BD |         19 | 8455 | 25.67419 |  89.05377 |         55 |      759 |    Rangpur District |       null
   Bangladesh |            Bagerhat |           BD |         19 | 8456 |     22.4 |     89.75 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bandarban |           BD |         19 | 8457 |       22 |  92.33333 |          B |      803 | Chittagong Division |       null
   Bangladesh |          Baniachang |           BD |         19 | 8458 | 24.51863 |  91.35787 |         60 |      767 |     Sylhet District |       null
   Bangladesh |             Barguna |           BD |         19 | 8459 | 22.13333 |  90.13333 |         06 |      818 |    Barisal District |       null
   Bangladesh |             Barisal |           BD |         19 | 8460 |     22.8 |      90.5 |         06 |      818 |    Barisal District |       null
   Bangladesh |                Bera |           BD |         19 | 8462 | 24.07821 |  89.63262 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |       Bhairab Bāzār |           BD |         19 | 8463 |  24.0524 |   90.9764 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Bherāmāra |           BD |         19 | 8464 | 24.02452 |  88.99234 |         27 |      811 |     Khulna District |       null
   Bangladesh |               Bhola |           BD |         19 | 8465 | 22.36667 |  90.81667 |         06 |      818 |    Barisal District |       null
   Bangladesh |           Bhāndāria |           BD |         19 | 8466 | 22.48898 |  90.06273 |         06 |      818 |    Barisal District |       null
   Bangladesh | Bhātpāra Abhaynagar |           BD |         19 | 8467 | 23.01472 |  89.43936 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bibir Hat |           BD |         19 | 8468 | 22.68347 |  91.79058 |          B |      803 | Chittagong Division |       null
   Bangladesh |               Bogra |           BD |         19 | 8469 | 24.78333 |     89.35 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |        Brahmanbaria |           BD |         19 | 8470 | 23.98333 |  91.16667 |          B |      803 | Chittagong Division |       null
   Bangladesh |         Burhānuddin |           BD |         19 | 8471 | 22.49518 |  90.72391 |         06 |      818 |    Barisal District |       null
   Bangladesh |            Bājitpur |           BD |         19 | 8472 | 24.21623 |  90.95002 |         13 |      771 |      Dhaka District |       null
   Bangladesh |            Chandpur |           BD |         19 | 8474 |    23.25 |  90.83333 |          B |      803 | Chittagong Division |       null
   Bangladesh |    Chapai Nababganj |           BD |         19 | 8475 | 24.68333 |     88.25 |         54 |      813 |   Rajshahi District |       null

(20 rows)
----
====

. Count the loaded data:
+
[source,bash]
----
astra db count dsbulk_demo_db \
    -k dsbulk_demo_keyspace \
    -t cities_by_country
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk count -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/COUNT_20250123-021120-127216
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 65,674 | 213.18 | 329.25 | 329.25
Operation COUNT_20250123-021120-127216 completed successfully in 1 second.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/COUNT_20250123-021120-127216/checkpoint.csv
134574
----
====

. Unload the data into CSV files:
+
[source,bash]
----
astra db unload dsbulk_demo_db \
    -k dsbulk_demo_keyspace \
    -t cities_by_country \
    -url unloaded_data
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk unload -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_91b35105-a5aa-4cd5-a93b-900ac58452ba_us-east1.zip -k dsbulk_demo_keyspace -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url unloaded_data -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/UNLOAD_20250123-021231-557959
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 29,767 | 281.25 | 591.40 | 591.40
Operation UNLOAD_20250123-021231-557959 completed successfully in 4 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/UNLOAD_20250123-021231-557959/checkpoint.csv
----
====
+
This command unloads row data from the `cities_by_country` table, and stores it as CSV files within a subsirectory names `unloaded_data` in the same directory where you ran the command.

[#cdc]
== Configure Change Data Capture (CDC)

[IMPORTANT]
====
CDC for {astra_db} incurs billed charges based on your {astra_stream} usage.
For more information, see https://www.ibm.com/docs/en/astra-streaming?topic=astra-streaming-annual-price-plans[{astra_stream} pricing].
====

CDC for {astra_db} automatically captures changes in real time, de-duplicates the changes, and then streams the clean set of changed data into xref:astra-streaming:ROOT:index.adoc[{astra_stream}] where it can be processed by client applications or sent to downstream systems.

Use the `astra db create-cdc` command to create a CDC connection for a table in a {db-serverless} database:

[source,bash,subs="+quotes"]
----
astra db create-cdc **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    --table **TABLE_NAME** \
    --tenant **TENANT_NAME**
----

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

Use the `astra db list-cdc` command to list the CDC connections for a specifc database:

[source,bash,subs="+quotes"]
----
astra db list-cdc **DATABASE_ID**
----

.Result
[%collapsible]
====
[source,console]
----
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| id                    | keyspace          | table          | tenant         | cluster            | namespace      | Status         |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| 57a3024f-cdcdemotable | cdc_demo_keyspace | cdc_demo_table | cdc-demo-tenant| pulsar-aws-useast1 | astracdc       | Running        |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
----
====

Use the `astra db delete-cdc` command to delete a CDC connection for a specific table:

[source,bash,subs="+quotes"]
----
astra db delete-cdc **DATABASE_ID** \
    -k **KEYSPACE_NAME** \
    --table **TABLE_NAME** \
    --tenant **TENANT_NAME**
----

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

=== `db create-cdc` options

.Expand to see all `db create-cdc` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create-cdc - Create a CDC to pulsar

SYNOPSIS
        astra db create-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ -p, --partition <PARTITION TOKEN> ] [ --table <TABLE> ]
                [ --tenant <TENANT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -p, --partition <PARTITION TOKEN>
            Paritions in the topics

        --table <TABLE>
            Table name

        --tenant <TENANT>
            Tenant name

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db list-cdc` options

.Expand to see all `db list-cdc` options
[%collapsible]
====
[source,console]
----
NAME
        astra db list-cdc - List CDC available on this databse

SYNOPSIS
        astra db list-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== `db delete-cdc` options

.Expand to see all `db delete-cdc` options
[%collapsible]
====
[source,console]
----
NAME
        astra db delete-cdc - Delete a CDC connection

SYNOPSIS
        astra db delete-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ -id <CDC_ID> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ] [ --table <TABLE> ]
                [ --tenant <TENANT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -id <CDC_ID>
            Identifier of the cdc when providing

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --table <TABLE>
            Table name

        --tenant <TENANT>
            Tenant name

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

=== Complete CDC configuration example

The following end-to-end example shows how to use the {product} to create a CDC connection for a table in a {db-serverless} database:

. Create an {astra_db} {db-serverless} database:
+
[source,bash]
----
astra db create cdc_demo_db \
    -c aws \
    -r us-east-1 \
    -k cdc_demo_keyspace
----
+
.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'cdc_demo_db' does not exist. Creating database 'cdc_demo_db' with keyspace 'cdc_demo_keyspace'
get CLoud provider
[INFO]  Database 'cdc_demo_db' and keyspace 'cdc_demo_keyspace' are being created.
[INFO]  Database 'cdc_demo_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'cdc_demo_db' has status 'ACTIVE' (took 112117 millis)
[OK]    Database 'cdc_demo_db' is ready.
----
====

. Create an {astra_stream} tenant in the same region as your database:
+
[source,bash]
----
astra streaming create cdc-demo-tenant \
    -c aws \
    -r useast1
----
+
.Result
[%collapsible]
====
[source,console]
----
https://api.astra.datastax.com/v2/streaming/tenants/cdc-demo-tenant
[OK]    Tenant 'cdc-demo-tenant' has being created.
----
====

. Use `xref:ROOT:managing.adoc#cqlsh[cqlsh]` to create a table with a primary key column in your database.
+
[source,bash]
----
astra db cqlsh cdc_demo_db -e \
"CREATE TABLE IF NOT EXISTS cdc_demo_keyspace.cdc_demo_table ( \
    key text PRIMARY KEY, \
    c1 text \
);"
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
----
====

. Confirm table creation:
+
[source,bash]
----
astra db cqlsh cdc_demo_db -e \
"SELECT * FROM cdc_demo_keyspace.cdc_demo_table"
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 key | c1
-----+----

(0 rows)
----
====

. Create a CDC connection.
+
[source,bash]
----
astra db create-cdc cdc_demo_db \
    -k cdc_demo_keyspace \
    --table cdc_demo_table \
    --tenant cdc-demo-tenant
----
+
////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

. Confirm CDC details for the database and tenant.
+
[source,bash]
----
astra db list-cdc cdc_demo_db
----
+
.Result
[%collapsible]
====
[source,console]
----
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| id                    | keyspace          | table          | tenant         | cluster            | namespace      | Status         |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| 57a3024f-cdcdemotable | cdc_demo_keyspace | cdc_demo_table | cdc-demo-tenant| pulsar-aws-useast1 | astracdc       | Running        |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
----
====
+
[source,bash]
----
astra streaming list-cdc cdc-demo-tenant
----
+
.Result
[%collapsible]
====
[source,console]
----
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| cluster            | namespace      | database       | keyspace          | table          | status         |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| pulsar-aws-useast1 | astracdc       | cdc_demo_db    | cdc_demo_keyspace | cdc_demo_table | running        |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
----
====

After you enable CDC on your {db-serverless} database, you can xref:astra-db-serverless:databases:change-data-capture.adoc#connect-a-sink[connect a sink].

== Download the {scb-brief}

The xref:astra-db-serverless:drivers:secure-connect-bundle.adoc[] is a zip file containing security credentials and certificates required for secure mutual TLS (mTLS) connection to your database.

Use the `astra db download-scb` command to download the {scb} for a database:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_ID** -r **REGION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in ./scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_dc-1.zip
----
====

The `-r **REGION_NAME**` option is required for <<configure-multiple-regions,multi-region databases>>.
If your database is configured with multiple regions, replace `**REGION_NAME**` with the name of the region you want to download the {scb-short} for.

By default, the {product} downloads the {scb-short} to the directory where you run the command and saves the file with the following naming pattern: `scb_**DATABASE-ID**_**REGION-NAME**.zip`.

[WARNING]
====
Treat the {scb-short} the same way you would any other sensitive values, such as passwords or tokens.

The {scb-short} contains sensitive information that establishes a connection to your database, including key pairs and certificates.
====

=== `db download-scb` options

.Expand to see all `db download-scb` options
[%collapsible]
====
[source,console]
----
NAME
        astra db download-scb - Download secure connect bundle archive for a
        region

SYNOPSIS
        astra db download-scb [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --output-file} <DEST> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <DEST>, --output-file <DEST>
            Destination file

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-r` / `--region` option to download the {scb-short} for a specific region:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_ID** -r **REGION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in ./scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_dc-1.zip
----
====

[TIP]
====
Use the `astra db list-regions` command to get a list of the region names where a database is deployed.
For more information, see <<configure-multiple-regions>>.
====

Use the `-f` / `--output-file` option to download the {scb-short} to a specific location and filename:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_ID** -f **DESTINATION_FILE**.zip
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in DESTINATION_FILE.zip
----
====

== Create environment variables

When developing applications with {astra_db} APIs, you will notice common values that are frequently reused, such as application tokens, database API endpoints, database IDs, and keyspace names.
It's a good practice to store these values in environment variables to facilitate reuse in your scripts, simplify token rotation, and increase security by keeping sensitive information separate from your core application code.

The {product} can automatically generate a set of relevant variables for a database that you can use in your applications.

Use the `astra db create-dotenv` command to generate a `.env` file containing relevant environment variables for a specific database:

[source,bash,subs="+quotes"]
----
astra db create-dotenv **DATABASE_ID**
----

By default, the {product} saves the `.env` file to the directory where you run the command.

If a `.env` file already exists in the directory, the {product} appends the new environment variables to the existing file.

.Result
[%collapsible%open]
====
..env
[source,console]
----
ASTRA_DB_API_ENDPOINT="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/json"
ASTRA_DB_APPLICATION_TOKEN="AstraCS:FZm..."
ASTRA_DB_GRAPHQL_URL="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql/demo"
ASTRA_DB_GRAPHQL_URL_ADMIN="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql-admin"
ASTRA_DB_GRAPHQL_URL_PLAYGROUND="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/playground"
ASTRA_DB_GRAPHQL_URL_SCHEMA="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql-schema"
ASTRA_DB_ID="a53003fe-ba42-4c3c-85d0-6b345622c2dc"
ASTRA_DB_KEYSPACE="demo"
ASTRA_DB_REGION="us-east1"
ASTRA_DB_REST_URL="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/rest"
ASTRA_DB_REST_URL_SWAGGER="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/rest/swagger-ui/"
ASTRA_DB_SECURE_BUNDLE_PATH="/Users/USERNAME/.astra/scb/scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_us-east1.zip"
ASTRA_DB_SECURE_BUNDLE_URL="https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/a53003fe-ba42-4c3c-85d0-6b345622c2dc-1/secure-connect-demo.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20241120%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20241120T233147Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=46d8704e382458c82d7da02db1ca79657e003de327f0123a0189ec1a50171cb0"
ASTRA_ORG_ID="2dbd3c55-6a68-4b5b-9155-5be9d41823e8"
ASTRA_ORG_NAME="alice@example.com"
ASTRA_ORG_TOKEN="AstraCS:FZm..."
----
====

[WARNING]
====
The generated `.env` files contains sensitive information, including the application token that the {product} uses to connect to {product-short}.

The {scb-short} contains sensitive information that establishes a connection to your database, including key pairs and certificates.
====

=== `db create-dotenv` options

The directory must already exist before you run the `db create-dotenv` command.
If the directory doesn't exist, the command fails with the error `INVALID_ARGUMENT: Destination folder has not been found`.

.Expand to see all `db create-dotenv` options
[%collapsible]
====
[source,console]
----
NAME
        astra db create-dotenv - Generate an .env configuration file associate
        with the db

SYNOPSIS
        astra db create-dotenv [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ {-d | --directory} <DIRECTORY> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -d <DIRECTORY>, --directory <DIRECTORY>
            Destination for the config file

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Default keyspace created with the Db

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----
====

Use the `-d` / `--directory` option to save the `.env` file to a specific directory:

[source,bash,subs="+quotes"]
----
astra db create-dotenv **DATABASE_ID** -d ~/tmp
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    File '/Users/USERNAME/tmp/.env' has been created/amended
----
====