= Uninstall the {product}
:navtitle: Uninstall the CLI

Follow the instructions for your original installation method to uninstall the {product}.

== Uninstall on macOS and Linux

Use these methods if you _did not_ install the {product} with a package manager.

To uninstall the {product} on macOS and Linux, you can use either `astra nuke` or manually remove the files.

=== Use astra nuke on macOS and Linux (recommended)

. Run the `xref:commands:astra-nuke.adoc[]` command:
+
[source,shell]
----
astra nuke
----
+
.Result
[source,console]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: x.x.x

Are you sure you want to entirely delete Astra CLI from your system?

This action is irreversible and will delete all Astra CLI files from your system.
  yes
> no (default)

↑↓ to navigate, Enter to select, type to filter
----

. When prompted to continue, select kbd:[yes], and then press kbd:[Enter].
+
.Result
[source,console]
----
Do you also want to delete the .astrarc file located at /Users/username/.astrarc?

(You can still Ctrl+C to safely cancel this operation.)

Your credentials may be lost if you do. A backup is recommended.
  yes
> no (default)
----

. Select whether to delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file, and then press kbd:[Enter] to continue.
+
Only select kbd:[yes] if you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles].
+
.Result
[source,console]
----
Astra CLI Nuke Summary

Files deleted:
→ /Users/username/.astra (contained binary)

Shell profiles containing astra:
→ /Users/username/.zprofile

Files skipped:
→ /Users/username/.astrarc - User chose to keep the file
----

. Optional: If the `astra nuke` command found any shell profiles containing references to the `astra` command, you can manually delete these references.

=== Manual removal on macOS and Linux

. Optional: If you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles], delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file:
+
[source,shell]
----
rm $(astra config path -p)
----

. Delete the xref:ROOT:manage-cli.adoc#file-locations[{product} home folder]:
+
[source,shell]
----
rm -rf $(astra config home path -p)
----

. Delete the `astra` binary if it still exists:
+
[source,shell]
----
rm -f $(which astra)
----

. Optional: Manually remove any references to the `astra` command from your shell profile.
For example, from `~/.zprofile` or `~/.bash_profile`.

== Uninstall on Windows

To uninstall the {product} on Windows, you can use the uninstaller, the `astra nuke` command, or manually remove the files:

=== Use the Windows uninstaller (recommended)

Only use this method if you installed the {product} using the xref:ROOT:install.adoc[scripted installer].

. Optional: If you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles], delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file:
+
[source,powershell]
----
rm -f $(astra config path -p)
----

. In your Windows **Settings**, uninstall the {product} app.
For specific instructions, see https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98[Uninstall or remove apps and programs in Windows].

=== Use astra nuke on Windows

. Run the `xref:commands:astra-nuke.adoc[]` command:
+
[source,powershell]
----
astra nuke
----
+
.Result
[source,console]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: x.x.x

Are you sure you want to entirely delete Astra CLI from your system?

This action is irreversible and will delete all Astra CLI files from your system.
  yes
> no (default)

↑↓ to navigate, Enter to select, type to filter
----

. When prompted to continue, select kbd:[yes] and press kbd:[Enter].
+
.Result
[source,console]
----
Do you also want to delete the .astrarc file located at <astra_cli_config_path>?

(You can still Ctrl+C to safely cancel this operation.)

Your credentials may be lost if you do. A backup is recommended.
  yes
> no (default)
----

. Select whether to delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file, and then press kbd:[Enter] to continue.
+
Only select kbd:[yes] if you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles].
+
.Result
[source,console]
----
Astra CLI Nuke Summary

Files deleted:
→ <astra_cli_home_directory> (contained binary)

Shell profiles containing astra:
→ <user_shell_profile_path>

Files skipped:
→ <astra_cli_config_path> - User chose to keep the file
----

. Optional: Manually remove `astra` from your system `PATH`.
For more information, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].

=== Manual removal on Windows

. Optional: If you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles], delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file:
+
[source,powershell]
----
rm -f $(astra config path -p)
----

. Delete the xref:ROOT:manage-cli.adoc#file-locations[{product} home folder]:
+
[source,powershell]
----
rm -r -f $(astra config home path -p)
----

. Delete the `astra` binary if it still exists:
+
[source,powershell]
----
rm -f (Get-Command astra).Source
----

. Optional: Manually remove `astra` from your system `PATH`.
For more information, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].

== Uninstall with Homebrew

Only use this method if you installed the {product} with Homebrew.

. Delete the {product} home folder (`xref:ROOT:manage-cli.adoc#file-locations[~/.astra]`) and optionally its configuration file (`xref:ROOT:manage-cli.adoc#file-locations[~/.astrarc]`):
+
.. Run the `xref:commands:astra-nuke.adoc[]` command:
+
[source,shell]
----
astra nuke
----
+
.Result
[source,console]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: x.x.x

Are you sure you want to entirely delete Astra CLI from your system?

This action is irreversible and will delete all Astra CLI files from your system.
  yes
> no (default)

↑↓ to navigate, Enter to select, type to filter
----
+
.. When prompted to continue, select kbd:[yes] and press kbd:[Enter].
+
.Result
[source,console]
----
Do you also want to delete the .astrarc file located at /Users/username/.astrarc?

(You can still Ctrl+C to safely cancel this operation.)

Your credentials may be lost if you do. A backup is recommended.
  yes
> no (default)
----
+
.. Select whether to delete the `xref:ROOT:manage-cli.adoc#file-locations[.astrarc]` file.
+
Only select kbd:[yes] if you don't want to preserve your xref:ROOT:manage-cli.adoc#manage-configuration-profiles[configuration profiles].
+
Press kbd:[Enter] to continue.
+
.Result
[source,console]
----
Astra CLI Nuke Summary

Files deleted:
→ /Users/username/.astra

Files skipped:
→ /Users/username/.astrarc - User chose to keep the file

To complete the uninstallation, please use Homebrew to uninstall the Astra CLI binary.
----

. Uninstall the {product} using Homebrew:
+
[source,shell]
----
brew uninstall astra
----