= Uninstall the {product}
:navtitle: Uninstall the CLI

Follow the instructions for your original installation method to uninstall the {product}.

[tabs,sync-group-id=platforms]
======
macOS and Linux::
+
Select one of the following methods to uninstall the {product} on macOS and Linux:
+
[tabs]
=====
`astra nuke` command (recommended)::
+
--
Run the `xref:commands:astra-nuke.adoc[]` command to uninstall the {product}:

[source,shell]
----
astra nuke
----

When prompted, type kbd:[y] and press kbd:[Enter] to proceed with the uninstallation.

The `astra nuke` command deletes the {product} home directory and optionally the configuration files (`xref:ROOT:use-cli.adoc#file-locations[~/.astra]` and `xref:ROOT:use-cli.adoc#file-locations[~/.astrarc]`).
It also lists any shell profile containing references to the `astra` command.
Delete these references manually if desired.
--

Manual removal::
+
--
. Optional: Remove the `xref:ROOT:use-cli.adoc#file-locations[.astrarc]` file if you don't need your credentials anymore:
+
[source,shell]
----
rm $(astra config path -p)
----

. Delete the xref:ROOT:use-cli.adoc#file-locations[{product} home directory]
+
[source,shell]
----
rm -rf $(astra config home path -p)
----

. Remove the `astra` binary if it still exists
+
[source,shell]
----
rm -f $(which astra)
----

. Remove any references to the `astra` command from your shell profile (for example, `~/.zprofile` or `~/.bash_profile`).
--
=====

Windows::
+
Select one of the following methods to uninstall the {product} on Windows:
+
[tabs]
=====
Uninstaller (recommended)::
+
--
Only use this method if you installed the {product} using the xref:ROOT:install.adoc[scripted installer].

. Optional: Remove the `xref:ROOT:use-cli.adoc#file-locations[.astrarc]` file if you don't need your credentials anymore:
+
[source,powershell]
----
rm -f $(astra config path -p)
----

. Go to *Start > Settings  > Apps > Installed apps*.
Find the {product}, select icon:ellipsis-vertical[name="More"], and then select *Uninstall*.
+
[NOTE]
====
The steps to locate and uninstall applications may vary depending on your version of Windows.
For detailed instructions, see the https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-4b55f974-2cc6-2d2b-d092-5905080eaf98[Microsoft Windows documentation].
====
--

`astra nuke` command::
+
--
Run the `xref:commands:astra-nuke.adoc[]` command to uninstall the {product}:

[source,powershell]
----
astra nuke
----

When prompted, type kbd:[y] and press kbd:[Enter] to proceed with the uninstallation.

The `astra nuke` command deletes the {product} home directory and optionally the configuration files (`xref:ROOT:use-cli.adoc#file-locations[~/.astra]` and `xref:ROOT:use-cli.adoc#file-locations[~/.astrarc]`).

You must remove `astra` from your system `PATH` manually, if desired.
For more information, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].
--

Manual removal::
+
--
. Optional: Remove the `xref:ROOT:use-cli.adoc#file-locations[.astrarc]` file if you don't need your credentials anymore:
+
[source,powershell]
----
rm -f $(astra config path -p)
----

. Delete the xref:ROOT:use-cli.adoc#file-locations[{product} home directory]
+
[source,powershell]
----
rm -r -f $(astra config home path -p)
----

. Remove the `astra` binary if it still exists
+
[source,powershell]
----
rm -f (Get-Command astra).Source
----

. Remove `astra` from your system `PATH`.
For more information, see the https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables[Microsoft PowerShell documentation].
--
=====

Homebrew::
+
--
. Optional: Run the `xref:commands:astra-nuke.adoc[]` command to delete the {product} home directory and optionally the configuration files (`xref:ROOT:use-cli.adoc#file-locations[~/.astra]` and `xref:ROOT:use-cli.adoc#file-locations[~/.astrarc]`):
+
[source,shell]
----
astra nuke
----
+
When prompted, type kbd:[y] and press kbd:[Enter] to proceed.


. Uninstall the {product} using Homebrew:
+
[source,shell]
----
brew uninstall datastax/astra-cli/astra
----
--
======
