= Upgrade the {product}
:navtitle: Upgrade the CLI

Keep the {product} up to date to access new features, improvements, and security updates.

Follow the instructions for your original installation method to upgrade the {product}.

[tabs,sync-group-id=platforms]
======
Homebrew::
+
--
. Run the following command to upgrade to the latest version of the {product}:
+
[source,bash]
----
brew upgrade datastax/astra-cli/astra
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,bash,subs="+quotes"]
----
brew install datastax/astra-cli/astra@**VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Check the {product} version to verify that the upgrade was successful:
+
[source,bash]
----
astra --version
----
+
The response returns your {product} version.
--

macOS::
+
--
. Run the `xref:commands:astra-upgrade.adoc[]` command to upgrade to the latest version of the {product}:
+
[source,bash]
----
astra upgrade
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,bash,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Check the {product} version to verify that the upgrade was successful:
+
[source,bash]
----
astra --version
----
+
The response returns your {product} version.
--

Windows::
+
--
. Run the `xref:commands:astra-upgrade.adoc[]` command to upgrade to the latest version of the {product}:
+
[source,powershell]
----
astra upgrade
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,powershell,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Check the {product} version to verify that the upgrade was successful:
+
[source,bash]
----
astra --version
----
+
The response returns your {product} version.
--

Linux::
+
--
. Run the `xref:commands:astra-upgrade.adoc[]` command to upgrade to the latest version of the {product}:
+
[source,bash]
----
astra upgrade
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,bash,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Check the {product} version to verify that the upgrade was successful:
+
[source,bash]
----
astra --version
----
+
The response returns your {product} version.
--

======
