= Upgrade the {product}
:navtitle: Upgrade the CLI

Keep the {product} up to date to access new features, improvements, and security updates.
Follow the instructions for your original installation method to upgrade the CLI.

[tabs]
======
Homebrew::
+
--
. Run the following command to upgrade to the latest version of the {product}:
+
[source,bash]
----
brew upgrade datastax/astra-cli/astra-cli
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,bash,subs="+quotes"]
----
brew install datastax/astra-cli/astra-cli@**VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Verify that the desired version of the {product} is installed:
+
[source,bash]
----
astra --version
----
--

macOS::
+
--
. Run the `astra upgrade` command to upgrade to the latest version of the {product}:
+
[source,bash]
----
astra upgrade
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,bash,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Verify that the desired version of the {product} is installed:
+
[source,bash]
----
astra --version
----
--

Windows::
+
--
. Run the `astra upgrade` command to upgrade to the latest version of the {product}:
+
[source,powershell]
----
astra upgrade
----

. Optional: Upgrade to a specific version of the {product}:
+
[source,powershell,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Verify that the desired version of the {product} is installed:
+
[source,bash]
----
astra --version
----
--
======
