= Upgrade the {product}
:navtitle: Upgrade the CLI

Keep the {product} up to date to access new features, improvements, and security updates.

If you're upgrading from version 0.6 or earlier, see xref:ROOT:upgrade-pre-1.0.adoc[].

[IMPORTANT]
====
If you used a package manager to install the {product}, such as Homebrew, then you must use the same package manager to upgrade the {product}.
====

== Upgrade with astra upgrade

You can use the `xref:commands:astra-upgrade.adoc[]` command on macOS, Linux, or Microsoft Windows if you _did not_ install the {product} with a package manager.

On Windows, run the following commands in a PowerShell terminal.

. Run the `xref:commands:astra-upgrade.adoc[]` command to upgrade to the latest version of the {product}:
+
[source,shell]
----
astra upgrade
----
+
To upgrade to a specific version, use the `--version` option:
+
[source,shell,subs="+quotes"]
----
astra upgrade --version **VERSION**
----
+
You can also use this command to downgrade to a previous version.

. Check the {product} version to verify that the upgrade was successful:
+
[source,shell]
----
astra --version
----
+
The response returns your {product} version.

== Upgrade with Homebrew

. Run the following command to upgrade to the latest version of the {product}:
+
[source,shell]
----
brew upgrade datastax/astra-cli/astra
----

. Check the {product} version to verify that the upgrade was successful:
+
[source,shell]
----
astra --version
----
+
The response returns your {product} version.