= Connect and manage the {product}
:navtitle: Connect and manage the CLI

Learn how to connect and run commands with the {product}.

If you haven't installed the {product} yet, see xref:ROOT:install.adoc[].

== Get an application token

The {product} requires an xref:astra-db-serverless:administration:manage-application-tokens.adoc[application token] to connect to {product-short}.

xref:astra-db-serverless:administration:manage-application-tokens.adoc#org-token[Generate an application token] and copy the token string (`AstraCS:…`) before moving on to the next section.

[TIP]
====
If this is your first time using the {product}, {company} recommends that you connect it to a non-production organization first.
That way, you can assign your application token a more expansive role, such as *Organization Administrator*, to try out all of the {product}'s features without putting production data at risk.

If you're using the{product} in production, {company} strongly recommends that you assign your application token only the bare minimum permissions required to perform the intended tasks.
====

== Connect the {product}

You can configure the {product} to authenticate in the following ways:

Save configuration profiles::
Configuration profiles let you save and manage connection information for use in {product} sessions.
+
Each configuration profile consists of a name and an application token.
When you set a profile as the default, the {product} authenticates all commands using that profile's application token, unless overridden.
+
See <<create-first-configuration-profile>>.

Authenticate individual commands::
You can supply an application token to authenticate individual commands.
+
This method is useful if you want to run a command without having to create a configuration profile.
+
See <<authenticate-individual-command>>.

[#create-first-configuration-profile]
=== Create your first configuration profile

The following procedure describes how to create your first configuration profile interactively, and is recommended for users who are new to the {product}.

For more advanced methods of creating and using configuration profiles, see <<manage-configuration-profiles>>.

. Run the `xref:commands:astra-setup.adoc[astra setup]` command:
+
[source,shell]
----
astra setup
----
+
.Result
[%collapsible]
====
[source,console]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: x.x.x

Welcome to the Astra CLI setup!

A configuration file with your profile will be created at /Users/USERNAME/.astrarc

If you'd prefer to provide credentials on a per-command basis rather than storing them in a file, you can either:
- Use the per-command --token flag to pass your existing AstraCS token directly.
- Use the per-command --config-file flag to specify an existing .astrarc file.

# Example:
$ astra db list --token <your_token>

Press Enter to continue, or use Ctrl+C to cancel.
----
====

. Press kbd:[Enter] to continue.

. Enter your application token (`AstraCS:...`), and press kbd:[Enter].

. Enter a name for your configuration profile, or press kbd:[Enter] to accept the default (your organization name).
+
.Result
[%collapsible]
====
[source,console]
----
Profile PROFILE_NAME successfully created.

It has been set as the default profile.
----
====
+
The {product} automatically sets the configuration profile as the default.
All subsequent commands use this profile unless you override it.

. Run a command to test the connection.
For example:
+
[source,shell]
----
astra db list-clouds
----
+
.Result
[%collapsible]
====
[source,console]
----
┌─────────────────┐
│ Cloud Provider  │
├─────────────────┤
│ gcp             │
│ azure           │
│ aws             │
└─────────────────┘
----
====
+
If the command succeeds, your connection is configured correctly.



[#authenticate-individual-command]
=== Authenticate an individual command

Every command lets you supply an application token using the `--token` option.
This method is useful if you want to run a command without having to create a configuration profile.

For example:

[source,shell,subs="+quotes"]
----
astra user list --token "**APPLICATION_TOKEN**"
----

The `--token` option bypasses the default configuration profile (if one exists) and uses the supplied application token for that command only.

== Get command help

Run `astra` by itself to print general help information:

[source,shell]
----
astra
----

.Result
[%collapsible]
====
[source,console]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: x.x.x

Documentation: https://docs.datastax.com/en/astra-cli

Usage: astra [-qVv] [--no-input] [--[no-]spinner] [--dump-logs[=FILE]]
             [--color=WHEN] [-o=FORMAT] [COMMAND]

  -v, --version            Print version information and exit.
                             (default: false)

Common Options:
      --color=WHEN         One of: auto, never, always
                             (default: auto)
      --dump-logs[=FILE]   Write all logs to an optionally specified file
                             (default: ~/.astra/logs/<file>.log)
      --no-input           Don't ask for user input (e.g. confirmation prompts)
  -o, --output=FORMAT      One of: human, json, csv
                             (default: human)
  -q, --quiet              Only output essential information
      --[no-]spinner       Enable/disable loading spinners
                             (default: enabled if tty)
  -V, --verbose            Enable verbose logging output

Commands:
  setup      Interactively set up the Astra CLI and create profiles
  config     Manage your Astra CLI configuration profiles
  db         Manage your Astra databases
  pcu        Manage your PCU groups and associations
  org        Get organization information
  role       Discover Astra roles
  streaming  Manage Astra streaming tenants
  token      Manage your Astra tokens
  user       Manage users in your organization
  upgrade    Upgrade your Astra CLI installation
  shellenv   Completions, configuration, and more
  nuke       Entirely delete Astra CLI from your system

Examples:
  # Create a new profile
  $ astra setup

  # List databases
  $ astra db list

  # Create a vector database
  $ astra db create demo -r us-east1

See 'astra <command> <subcommand> --help' for help on a specific subcommand.
----
====

Append the `-h`/`--help` option to any command or subcommand to get specific help information and examples:

[source,shell]
----
astra org -h
----

.Result
[%collapsible]
====
[source,console]
----
Usage: astra org [-qV] [--no-input] [--[no-]spinner] [--dump-logs[=FILE]]
                 [--color=WHEN] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                 [--token=TOKEN [--env=ENV]]] [COMMAND]

Get organization information

The --token flag is handy to quickly get information about another organization.

Use the --token @file syntax to read the token from a file, to avoid potential
leaks.


Common Options:
      --color=WHEN         One of: auto, never, always
                             (default: auto)
      --dump-logs[=FILE]   Write all logs to an optionally specified file
                             (default: ~/.astra/logs/<file>.log)
      --no-input           Don't ask for user input (e.g. confirmation prompts)
  -o, --output=FORMAT      One of: human, json, csv
                             (default: human)
  -q, --quiet              Only output essential information
      --[no-]spinner       Enable/disable loading spinners
                             (default: enabled if tty)
  -V, --verbose            Enable verbose logging output

Connection Options:
      -cf, --config-file=PATH
                           The .astrarc file to use for this command
                             (default: ~/.astrarc)
      --env=ENV            Override the target astra environment
  -p, --profile=NAME       The .astrarc profile to use for this command
      --token=TOKEN        The astra token to use for this command. Use the
                             --token @file syntax to read the token from a
                             file, to avoid potential leaks.

Commands:
  get   Get your organization's information
  id    Get your organization's ID
  name  Get your organization's name

Examples:
  # Get your organization's information
  $ astra org

  # Get information about another organization
  $ astra org get --token AstraCS:...

See 'astra <command> <subcommand> --help' for help on a specific subcommand.
----
====

[source,shell]
----
astra db list --help
----

.Result
[%collapsible]
====
[source,console]
----
Usage: astra db list [-qvV] [--no-input] [--[no-]spinner] [--dump-logs[=FILE]]
                     [--color=WHEN] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                     [--token=TOKEN [--env=ENV]]]

List your non-terminated Astra databases.

  -v, --vector             Only show vector-enabled databases
                             (default: false)

Common Options:
      --color=WHEN         One of: auto, never, always
                             (default: auto)
      --dump-logs[=FILE]   Write all logs to an optionally specified file
                             (default: ~/.astra/logs/<file>.log)
      --no-input           Don't ask for user input (e.g. confirmation prompts)
  -o, --output=FORMAT      One of: human, json, csv
                             (default: human)
  -q, --quiet              Only output essential information
      --[no-]spinner       Enable/disable loading spinners
                             (default: enabled if tty)
  -V, --verbose            Enable verbose logging output

Connection Options:
      -cf, --config-file=PATH
                           The .astrarc file to use for this command
                             (default: ~/.astrarc)
      --env=ENV            Override the target astra environment
  -p, --profile=NAME       The .astrarc profile to use for this command
      --token=TOKEN        The astra token to use for this command. Use the
                             --token @file syntax to read the token from a
                             file, to avoid potential leaks.

Examples:
  # List all your Astra databases
  $ astra db list

  # List only vector-enabled Astra databases
  $ astra db list --vector

See 'astra <command> <subcommand> --help' for help on a specific subcommand.
----
====

[#command-auto-completion]
== Use command auto-completion

The {product} provides command auto-completion for Bash and ZSH shells.

To use auto-completion, type the `astra` command and then press kbd:[Tab] twice to get a list of available options:

[source,shell,subs="+macros"]
----
astra kbd:[Tab] kbd:[Tab]
----

.Result
[%collapsible%open]
====
[source,console]
----
config     nuke       pcu        setup      streaming  upgrade
db         org        role       shellenv   token      user
----
====

Certain dynamic arguments, such as database names, also support auto-completion once the CLI discovers them.
For example, after running `astra db list`, type `astra db get` followed by kbd:[Tab] twice to see a list of your database names:

[source,shell,subs="macros"]
----
astra db get kbd:[Tab] kbd:[Tab]
----

.Result
[%collapsible%open]
====
[source,console]
----
prod_db    test_db    playground_db
----
====

[#manage-configuration-profiles]
== Manage configuration profiles

If you ran the `astra setup` command to <<create-first-configuration-profile,create your first configuration profile>>, the {product} automatically sets it as the default configuration profile. stores your application token as the default configuration in the `~/.astrarc` configuration file.

You can create additional configuration profiless, each with their own application token, to make it easier to manage different types of resources across one or more organizations.

=== Get and set configurations

. Use `astra config list` to list all current configuration profiles:
+
[source,shell]
----
astra config list
----
+
.Result
[%collapsible]
====
[source,console]
----
┌───────────────────────────────────┐
│ configuration                     │
├───────────────────────────────────┤
│ Production (in use)               │
│ Testing                           │
└───────────────────────────────────┘
----
====

. Use `astra config create` or `astra setup` again to create a new configuration profile:
+
[source,shell,subs="+quotes"]
----
astra config create "**CONFIG_NAME**" --token **APPLICATION_TOKEN**
----
+
.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
Configuration profile '**CONFIG_NAME**' successfully created.

(Hint: Use 'astra setup' for an interactive profile creation experience!)

# Set it as the default profile:
$ astra config use **CONFIG_NAME**
----
====

. Use `astra config use` to change the default configuration that {product} uses when executing commands:
+
[source,shell,subs="+quotes"]
----
astra config use "**CONFIG_NAME**"
----
+
.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
Default profile set to '**CONFIG_NAME**'.
----
====

. Optional: Rerun `astra config list` to verify that the new default configuration is set.

=== Set the configuration for a single run

Every {product} command supports the `--profile` option.
This option lets you use a different configuration profile when running a command without changing the default configuration profile.
For example:

[source,shell,subs="+quotes"]
----
astra user list --config "**CONFIG_NAME**"
----

=== Delete a configuration profile

Use `astra config delete` to delete a configuration profile:

[source,shell,subs="+quotes"]
----
astra config delete "**CONFIG_NAME**"
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
Profile 'tem' deleted successfully.
----
====

[IMPORTANT]
====
If you delete the default configuration, the {product} _doesn't_ automatically select a new default configuration.
Use the `astra config use` command to select a new default configuration.
====

[#file-locations]
== {product} file locations

The {product} stores installation and configuration files in the following locations:

[cols="1h,2"]
|===
|File / Directory |Description

|`.astra`
a|The `ASTRA_HOME` directory.

_Default location_: `~/.astra` (macOS and Linux), `%USERPROFILE%\.astra` (Windows)

The {product} stores the following items in this directory:

* The {product} executable (scripted installations only)
* Accessory executables for commands like `xref:commands:astra-db-cqlsh.adoc[]` and `xref:commands:astra-db-dsbulk.adoc[]`
* Cache files for <<command-auto-completion,command auto-completion>>
* Logs

|`.astrarc`
|The {product} configuration file.

_Default location_: `~/.astrarc` (macOS and Linux), `%USERPROFILE%\.astrarc` (Windows)

This file stores your <<manage-configuration-profiles,configuration profiles>> and their associated application tokens.
|===
