= Connect and configure the {product}
:navtitle: Connect and configure

Initialize the {product} and run your first commands.

== Connect to {product-short}

After xref:ROOT:install.adoc[installing the {product}], follow these steps to set up your first connection profile:

. {astra-url}[Sign in or create an {product-short} account.^]

. Generate an xref:astra-db-serverless:administration:manage-application-tokens.adoc[application token] with a role that has adequate permissions to perform the tasks you want to accomplish with the {product}.
+
--
* *Non-production organizations*: If your {product-short} organization has no databases or streaming tenants that handle sensitive information, you can grant your application token the `Organization Administrator` role to try out all of the {product} features.

* *Production organizations*: If you're using {product-short} in production, {company} recommends that you use a more limited xref:astra-db-serverless:administration:manage-database-access.adoc#built-in-organization-roles[built-in role] or xref:astra-db-serverless:administration:manage-database-access.adoc#custom-roles[custom role] to grant your application token the bare minimum permissions required to perform your desired tasks with the {product}.
--

. Run the `astra setup` command to to create your first connection profile:
+
[source,bash]
----
astra setup
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
     _____            __
    /  _  \   _______/  |_____________
   /  /_\  \ /  ___/\   __\_  __ \__  \
  /    |    \\___ \  |  |  |  | \ //__ \_
  \____|__  /____  > |__|  |__|  (____  /
          \/     \/                   \/

                       Version: {product-version}

Welcome to the Astra CLI setup!

A configuration file with your profile will be created at /Users/USERNAME/.astrarc

If you'd prefer to provide credentials on a per-command basis rather than storing them in a file, you can either:
- Use the per-command --token flag to pass your existing AstraCS token directly.
- Use the per-command --config-file flag to specify an existing .astrarc file.

# Example:
$ astra db list --token <your_token>

Press Enter to continue, or use Ctrl+C to cancel.
----
====

. When prompted, enter your {product-short} application token and press kbd:[Enter].

. Enter a name for your connection profile or press kbd:[Enter] to accept the default (your organization name).
+
.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
Profile PROFILE_NAME successfully created.

It has been set as the default profile.
----
====

. Test your connection by running a simple command, such as listing your databases:
+
[source,bash]
----
astra db list
----
+
If the command succeeds, your connection is configured correctly.
If your command fails, see the xref:commands:astra-setup.adoc[astra setup command] documentation for troubleshooting tips.

[#file-locations]
== Installation file locations

The {product} and its configuration are installed in the following locations:

[cols="1,2"]
|===
|File location |Description

|`~/.astra`
a|The {product} installation directory.

For <<install-curl,curl-based installations>>, the `astra` executable and `astra-init.sh` auto-completion script are located in `~/.astra/cli`.
The `~/.astra/cli` folder is added to the `PATH` environment variable.
_This folder is deleted and recreated when you update or re-install the {product}._

For <<install-homebrew,Homebrew-based installations>>, the `astra` executable and auto-completion script are located in https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location[Homebrew's default prefix] at the following locations:

* Executable: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/bin/astra`
* Auto-completion script: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/etc/bash_completion.d/astra`

|`~/.astrarc`
|The {product} configuration file.

_This file is *not* deleted when you update or re-install the {product}._
|===

== Print help information

Use `astra help` to print general {product} help information:

[source,bash]
----
astra help
----

.Result
[%collapsible]
====
[source,console]
----
usage: astra <command> [ <args> ]

Commands are:
    ?           Display this help version
    help        Display help information
    login       Authenticate against Astra.
    setup       Initialize configuration file
    config      Manage configuration file
    db          Manage databases
    org         Display Organization Info
    role        Manage roles
    streaming   Manage Streaming tenants
    token       Manage tokens
    user        Manage users

See 'astra help <command>' for more information on a specific command.
----
====

Append a command name to print help information about an individual command.
For example:

[source,bash]
----
astra help db
----

.Result
[%collapsible]
====
[source,console]
----
NAME
        astra db - Manage databases

SYNOPSIS
        astra db { count | cqlsh | create | create-cdc | create-collection |
                create-dotenv | create-keyspace | create-region | delete |
                delete-cdc | delete-collection | delete-keyspace |
                delete-region | describe | download-scb | get |
                get-endpoint-api | get-endpoint-playground |
                get-endpoint-swagger | list* | list-cdc | list-clouds |
                list-collections | list-keyspaces | list-regions |
                list-regions-classic | list-regions-serverless |
                list-regions-vector | load | resume | status | unload } [--]
                [ --token <AUTH_TOKEN> ] [ --no-color ] [ {-v | --verbose} ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ {-cf | --config-file} <CONFIG_FILE> ] [ --env <Environment> ]
                [ {-o | --output} <FORMAT> ] [cmd-options] <cmd-args>

        Where command-specific options [cmd-options] are:
            count: [ {-k | --keyspace} <KEYSPACE> ] [ -encoding <ENCODING> ] [ {-t | --table} <TABLE> ]
                    [ {-query | --schema.query} <QUERY> ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                    [ -maxConcurrentQueries <maxConcurrentQueries> ] [ -logDir <log directory> ]
            cqlsh: [ --debug ] [ {-f | --file} <FILE> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --version ] [ --connect-timeout <TIMEOUT> ] [ {-e | --execute} <STATEMENT> ]
                    [ --request-timeout <TIMEOUT> ] [ --encoding <ENCODING> ]
            create: [ {-c | --cloud} <cloud> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --vector ] [ --timeout <timeout> ] [ {-r | --region} <DB_REGION> ]
                    [ {--if-not-exist | --if-not-exists} ] [ --async ] [ --tier <TIER> ]
                    [ --capacity-units <CAPACITY UNITS> ]
            create-cdc: [ {-k | --keyspace} <KEYSPACE> ] [ --tenant <TENANT> ]
                    [ -p, --partition <PARTITION TOKEN> ] [ --table <TABLE> ]
            create-collection: [ {-m | --metric} <METRIC> ] {-c | --collection}
                    <COLLECTION> [ {-d | --dimension} <DIMENSION> ]
            create-dotenv: [ {-k | --keyspace} <KEYSPACE> ] [ {-d | --directory} <DIRECTORY> ]
                    [ {-r | --region} <DB_REGION> ]
            create-keyspace: {-k | --keyspace} <KEYSPACE> [ --if-not-exist ] [ --wait ]
            create-region: [ {-c | --cloud} <CLOUD> ] [ --timeout <timeout> ]
                    {-r | --region} <REGION> [ --wait ] [ {-t | --tier} <CLOUD> ]
                    [ --async ] [ --if-not-exist ]
            delete: [ --async ] [ --timeout <timeout> ] [ --wait ]
            delete-cdc: [ {-k | --keyspace} <KEYSPACE> ] [ -id <CDC_ID> ] [ --tenant <TENANT> ]
                    [ --table <TABLE> ]
            delete-collection: {-c | --collection} <COLLECTION>
            delete-keyspace: {-k | --keyspace} <KEYSPACE>
            delete-region: [ --async ] [ --timeout <timeout> ] {-r | --region}
                    <REGION> [ --wait ]
            describe: [ {-k | --key} <Key> ]
            download-scb: [ {-f | --output-file} <DEST> ] [ {-r | --region} <DB_REGION> ]
            get: [ {-k | --key} <Key> ]
            get-endpoint-api: [ {-r | --region} <DB_REGION> ]
            get-endpoint-playground: [ {-r | --region} <DB_REGION> ]
            get-endpoint-swagger: [ {-r | --region} <DB_REGION> ]
            list: [ --vector ]
            list-cdc:
            list-clouds:
            list-collections:
            list-keyspaces:
            list-regions:
            list-regions-classic: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            list-regions-serverless: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            list-regions-vector: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            load: [ {-k | --keyspace} <KEYSPACE> ] [ -maxErrors <maxErrors> ] [ -encoding <ENCODING> ]
                    [ {-t | --table} <TABLE> ] [ {-query | --schema.query} <QUERY> ]
                    [ -skipRecords <skipRecords> ] [ --schema.allowMissingFields <allowMissingFields> ]
                    -url <url> [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -dryRun ]
                    [ -header <header> ] [ -delim <delim> ] [ -maxConcurrentQueries <maxConcurrentQueries> ]
                    [ -logDir <log directory> ] [ {-m | --schema.mapping} <mapping> ]
            resume: [ --async ] [ --timeout <timeout> ] [ --wait ]
            status:
            unload: [ {-k | --keyspace} <KEYSPACE> ] [ -maxErrors <maxErrors> ]
                    [ -encoding <ENCODING> ] [ {-t | --table} <TABLE> ] [ {-query | --schema.query} <QUERY> ]
                    [ -skipRecords <skipRecords> ] [ -url <url> ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                    [ -header <header> ] [ -delim <delim> ] [ -maxConcurrentQueries <maxConcurrentQueries> ]
                    [ -logDir <log directory> ] [ {-m | --schema.mapping} <mapping> ]

        Where command-specific arguments <cmd-args> are:
            count: <DB>
            cqlsh: <DB>
            create: <DB>
            create-cdc: <DB>
            create-collection: <DB>
            create-dotenv: <DB>
            create-keyspace: <DB>
            create-region: <DB>
            delete: <DB>
            delete-cdc: <DB>
            delete-collection: <DB>
            delete-keyspace: <DB>
            delete-region: <DB>
            describe: <DB>
            download-scb: <DB>
            get: <DB>
            get-endpoint-api: <DB>
            get-endpoint-playground: <DB>
            get-endpoint-swagger: <DB>
            list:
            list-cdc: <DB>
            list-clouds:
            list-collections: <DB>
            list-keyspaces: <DB>
            list-regions: <DB>
            list-regions-classic:
            list-regions-serverless:
            list-regions-vector:
            load: <DB>
            resume: <DB>
            status: <DB>
            unload: <DB>

        Where * indicates the default command(s)
        See 'astra help db <command>' for more information on a specific command.
----
====

Append a subcommand for further specificity:

[source,bash]
----
astra help db list
----

.Result
[%collapsible]
====
[source,console]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled
----
====

== Set up auto-completion

The {product} provides Bash auto-completion for `bash` and `zsh` shells.

To use auto-completion, type the `astra` command and then press kbd:[Tab] twice to get a list of available options.

[source,bash,subs="macros"]
----
astra kbd:[Tab] kbd:[Tab]
----

.Result
[%collapsible%open]
====
[source,console]
----
 --no-color  config      db          help        role        setup       shell       user
----
====

[#manage-configuration]
== Manage the {product} configuration

When you run the `astra setup` command during <<initialize,initialization>>, the {product} stores your application token as the default configuration in the `~/.astrarc` configuration file.

You can create additional configurations, each with their own application token, to make it easier to manage different types of resources across one or more organizations.

=== Get and set configurations

. Use `astra config list` to list all current configurations:
+
[source,bash]
----
astra config list
----
+
.Result
[%collapsible]
====
[source,console]
+----------------------------+
| configuration              |
+----------------------------+
| Organization 1 (in use)    |
| Organization 2             |
+----------------------------+
====

. Use `astra config create` to create a new configuration:
+
[source,bash,subs="+quotes"]
----
astra config create "**CONFIG_NAME**" --token **APPLICATION_TOKEN**
----
+
.Result
[%collapsible]
====
[source,console]
----
[OK]    Configuration has been saved.
----
====

. Use `astra config use` to change the default configuration that {product} uses when executing commands:
+
[source,bash,subs="+quotes"]
----
astra config use "**CONFIG_NAME**"
----
+
.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
[OK]    Section '**CONFIG_NAME**' is set as default.
----
====

. Optional: Rerun `astra config list` to verify that the new default configuration is set.

=== Set the configuration for a single run

Every {product} command supports the `--config` option.
This option lets you use a different configuration when running a command without changing the default configuration.
For example:

[source,bash,subs="+quotes"]
----
astra user list --config "**CONFIG_NAME**"
----

Alternatively, you can use the `--token` option to supply an application token when running a command.
This option lets you use a different application token without having to create a new configuration.
For example:

[source,bash,subs="+quotes"]
----
astra user list --token "**APPLICATION_TOKEN**"
----

=== Delete a configuration

Use `astra config delete` to delete a configuration:

[source,bash,subs="+quotes"]
----
astra config delete "**CONFIG_NAME**"
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
[OK]    Section '**CONFIG_NAME**' has been deleted.
----
====

[IMPORTANT]
====
If you delete the default configuration, the {product} _doesn't_ automatically select a new default configuration.
Use the `astra config use` command to select a new default configuration.
====

=== `config` options

The following options are available for the `astra config` command:

[source,console]
----
NAME
        astra config - Manage configuration file

SYNOPSIS
        astra config { create | delete | describe | get | list* | use } [--]
                [ {-cf | --config-file} <CONFIG_FILE> ] [ --no-color ]
                [ {-v | --verbose} ] [ {-o | --output} <FORMAT> ] [cmd-options]
                <cmd-args>

        Where command-specific options [cmd-options] are:
            create: [ {-e | --env} <Environment> ] [ {-t | --token} <AuthToken> ]
            delete:
            describe: [ {-k | --key} <Key in the section> ]
            get: [ {-k | --key} <Key in the section> ]
            list:
            use:

        Where command-specific arguments <cmd-args> are:
            create: [ <sectionName> ]
            delete: <sectionName>
            describe: <sectionName>
            get: <sectionName>
            list:
            use: <sectionName>

        Where * indicates the default command(s)
        See 'astra help config <command>' for more information on a specific command.
----

See the following sections for `config` subcommand options:

.Expand to see all `config create` options
[%collapsible]
====
[source,console]
----
NAME
        astra config create - Create a new section in configuration

SYNOPSIS
        astra config create [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-e | --env} <Environment> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-t | --token} <AuthToken> ]
                [ {-v | --verbose} ] [--] [ <sectionName> ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -e <Environment>, --env <Environment>
            Environment to use for this section.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -t <AuthToken>, --token <AuthToken>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config delete` options
[%collapsible]
====
[source,console]
----
NAME
        astra config delete - Delete section in configuration

SYNOPSIS
        astra config delete [ {-cf | --config-file} <CONFIG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-v | --verbose} ] [--] <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config describe` options
[%collapsible]
====
[source,console]
----
NAME
        astra config describe - Show details for a configuration.

SYNOPSIS
        astra config describe [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-k | --key} <Key in the section> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -k <Key in the section>, --key <Key in the section>
            If provided return only value for a key.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config get` options
[%collapsible]
====
[source,console]
----
NAME
        astra config get - Show details for a configuration.

SYNOPSIS
        astra config get [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-k | --key} <Key in the section> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -k <Key in the section>, --key <Key in the section>
            If provided return only value for a key.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config list` options
[%collapsible]
====
[source,console]
----
NAME
        astra config list - Show the list of available configurations.

SYNOPSIS
        astra config list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-v | --verbose} ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console
----
====

.Expand to see all `config use` options
[%collapsible]
====
[source,console]
----
NAME
        astra config use - Make a section the one used by default

SYNOPSIS
        astra config use [ {-cf | --config-file} <CONFIG_FILE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

== Next steps

* xref:ROOT:managing.adoc[]
* xref:ROOT:astra-streaming-cli.adoc[]
* xref:ROOT:administration.adoc[]