= {company} {product} docs
// Variables:
:company: DataStax
:product: Astra CLI
// Document settings:
:toc: macro
:toclevels: 2
:idprefix:
:idseparator: -
:!example-caption:
:!figure-caption:
:!table-caption:
:experimental:
:hide-uri-scheme:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :paperclip:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository contains the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] source files for the {company} {product} documentation.

To learn how to update the documentation, see the https://datastax.jira.com/wiki/spaces/DOCS/overview[Docs team Confluence site].

== Regenerate the Astra CLI command reference

The Astra CLI command reference documentation is generated from the literal CLI help text in the Astra CLI code.
The command reference documentation should be regenerated and committed to the docs whenever a new version of the Astra CLI is released.

You need a recent JDK installed.
You do not need the Astra CLI itself installed.

. If you haven't done so yet, clone the Astra CLI code repository:
+
[source,bash]
----
git clone https://github.com/datastax/astra-cli.git
----

. Change directory to the cloned repository:
+
[source,bash]
----
cd astra-cli
----

. Pull the latest changes:
+
[source,bash]
----
git switch main && git pull
----

. Set the path to your local clone of this documentation repository (`astra-cli-docs`):
+
[source,bash]
----
ASTRA_CLI_DOCS=~/repos/astra-cli-docs
----

. Load the Astra CLI development alias:
+
[source,bash]
----
source scripts/dev-alias.sh
----

. Regenerate the command reference docs:
+
[source,bash]
----
astra docs && \
    rsync -a --delete build/docs/commands/ $ASTRA_CLI_DOCS/modules/commands/pages/ && \
    cp -f build/docs/partial-nav.adoc $ASTRA_CLI_DOCS/modules/commands/partials/
----
