= astra db delete-collection

[source,shell]
----
astra db delete-collection [-qV] [--if-exists] [--no-input] [--[no-]spinner]
                           [--dump-logs[=FILE]] [-c=COLLECTION] [--color=WHEN]
                           [-k=KEYSPACE] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                           [--token=TOKEN [--env=ENV]]] [DB]

----


Delete an existing Data API collection from the specified database and keyspace





== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--keyspace`:: The keyspace to use
`-c`, `--collection`:: The collection to use
`--if-exists`:: Do not fail if collection does not exist
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Delete a collection
$ astra db delete-collection my_db -c my_collection

# Delete a collection from a non-default keyspace
$ astra db delete-collection my_db -k my_keyspace -c my_collection

# Delete a collection without failing if it doesn't exist
$ astra db delete-collection my_db -c my_collection --if-exists
----


