= astra db list

[source,shell]
----
astra db list [-qvV] [--no-input] [--[no-]spinner] [--color[=WHEN]] [--dump-logs
              [=FILE]] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
              [--env=ENV]]]

----


List your non-terminated Astra databases.

== Aliases

`astra db`




== Options

`-v`, `--vector`:: Only show vector-enabled databases

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# List all your Astra databases
$ astra db list

# List only vector-enabled Astra databases
$ astra db list --vector
----


