= astra user invite

[source,shell]
----
astra user invite [-qV] [--if-not-exists] [--no-input] [--[no-]spinner]
                  [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT] [-r=<$roles>[,
                  <$roles>...]]... [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                  [--env=ENV]]] USER

----


Invite a user to an organization





== Options

`USER`:: User email/id to invite
`-r`, `--roles`:: List of roles to assign the user
`--if-not-exists`:: Do not fail if user already exists

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Invite a user with default "Database Administrator" role
$ astra user invite john@example.com

# Invite a user with specific roles
$ astra user invite john@example.com --role 'R/W User' --role 'Billing Admin'

# Invite a user without failing if they already exist
$ astra user invite john@example.com --if-not-exists
----


