= astra db list-collections

[source,shell]
----
astra db list-collections [-aqV] [--no-input] [--[no-]spinner] [--dump-logs
                          [=FILE]] [--color=WHEN] [-k=KEYSPACE] [-o=FORMAT]
                          [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                          [--env=ENV]]] [DB]

----


List the collections in the specified database and keyspace





== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--keyspace`:: The keyspace to use
`-a`, `--all`:: List collections in all keyspaces
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# List all collections in the default keyspace
$ astra db list-collections my_db

# List all collections in a specific keyspace
$ astra db list-collections my_db -k my_keyspace

# List all collections in all keyspaces
$ astra db list-collections my_db --all
----


