= astra token create

[source,shell]
----
astra token create [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]]
                   [--dump-logs[=FILE]] [-d=DESC] [-o=FORMAT] -r=ROLE
                   [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]

----


Create a new token





== Options

`-r`, `--role`:: The role for this token
`-d`, `--description`:: An optional description for this token

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Create a token with a specific role
$ astra token create --role "Organization Administrator"
----


