= astra streaming exist

[source,shell]
----
astra streaming exist [-qV] [--no-input] [--[no-]spinner] [--dump-logs[=FILE]]
                      [--color=WHEN] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                      [--token=TOKEN [--env=ENV]]] TENANT

----


Show existence of a streaming tenant





== Options

`TENANT`:: The name of the tenant to operate on

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Check if a streaming tenant exists
$ astra streaming exist my_tenant
----


