= astra token create

[source,shell]
----
astra token create [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]]
                   [--dump-logs[=FILE]] [-h[=all]] [-d=DESC] [-o=FORMAT]
                   [--org=ORG] [-x=EXPIRY] [-r=ROLE[,ROLE...]]... [[[-cf=PATH]
                   [-p=NAME]] | [--token=TOKEN [--env=ENV]]]

----


Create a new token





== Options

`-r`, `--role`:: List of roles for the token
`-d`, `--description`:: An optional description for this token
`--org`:: Optional UUID of the organization under which the token will be created. If not provided, the token is created under the organization/enterprise of the authorization token.
`-x`, `--expiry`:: Optional expiration date for the token in ISO-8601 format (e.g., 2026-08-19T14:30:00Z). If not provided, the org's max expiry will be used (potentially infinite).

=== Common Options
`-h`, `--help`:: Show this help message and exit.
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file


=== Connection Options
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Astra environment the token belongs to: prod (default), dev, test, or local. Leave unset unless you were issued a non-prod token.



== Examples

[source,bash]
----
# Create a token and interactively select your roles
$ astra token create

# Create a token with a specific role
$ astra token create --role "Organization Administrator"

# Create a token with multiple roles
$ astra token create --role "RO User,Billing Admin"
----


