= astra streaming delete

[source,shell]
----
astra streaming delete [-qV] [--if-exists] [--no-input] [--[no-]spinner]
                       [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT]
                       [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]
                       [TENANT]

----


Delete an existing streaming tenant





== Options

`TENANT`:: The name of the tenant to operate on
`--if-exists`:: Do not fail if tenant does not exist

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Delete an existing streaming tenant
$ astra streaming delete my_tenant

# Delete an existing streaming tenant without failing if it does not exist
$ astra streaming delete my_tenant --if-exists
----


