= astra db list-embedding-providers

[source,shell]
----
astra db list-embedding-providers [-qV] [--no-input] [--[no-]spinner]
                                  [--dump-logs[=FILE]] [--color=WHEN]
                                  [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                                  [--token=TOKEN [--env=ENV]]] [DB]

----


Find all available embedding providers for a given database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Find all available embedding providers for a database
$ astra db list-embedding-providers my_db
----


