= astra db get-endpoint-api

[source,shell]
----
astra db get-endpoint-api [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]]
                          [--dump-logs[=FILE]] [-o=FORMAT] [-r=REGION]
                          [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                          [--env=ENV]]] [DB]

----


Get the API endpoint to interact with the specified database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-r`, `--region`:: The region to use

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----

----


