= astra db dsbulk path

[source,shell]
----
astra db dsbulk path [-qV] [--if-exists] [--no-input] [--[no-]spinner] [--color
                     [=WHEN]] [--dump-logs[=FILE]] [-o=FORMAT] [[[-cf=PATH]
                     [-p=NAME]] | [--token=TOKEN [--env=ENV]]]

----


Get the path to the currently installed dsbulk executable





== Options

`--if-exists`:: Only return path if dsbulk exists, don't install automatically

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Get the path to the dsbulk executable
$ astra db dsbulk path

# Use the dsbulk exe to run a custom command
$ $(astra db dsbulk path) --help

# Get path only if dsbulk exists, don't install
$ astra db dsbulk path --if-exists
----


