= astra pcu list-associations

[source,shell]
----
astra pcu list-associations [-aqV] [--no-input] [--[no-]spinner] [--dump-logs
                            [=FILE]] [--color=WHEN] [-o=FORMAT] [[[-cf=PATH]
                            [-p=NAME]] | [--token=TOKEN [--env=ENV]]] [GROUP]

----


List the associations of a PCU group





== Options

`GROUP`:: The name or ID of the PCU group to work with
`-a`, `--all`:: List all associations for all of your PCU groups
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# List the associations of a PCU group
$ astra pcu list-associations my_pu
----


