= astra db endpoints playground

[source,shell]
----
astra db endpoints playground [-cqV] [--no-input] [--[no-]spinner] [--color
                              [=WHEN]] [--dump-logs[=FILE]] [-o=FORMAT]
                              [-r=REGION] [[[-cf=PATH] [-p=NAME]] |
                              [--token=TOKEN [--env=ENV]]] [DB]

----


Get the GraphQL Playground for the specified database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-r`, `--region`:: The region to use
`-c`, `--copy`:: Copy the endpoint to clipboard as well as print it

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Astra environment the token belongs to: prod (default), dev, or test. Leave unset unless you were issued a non-prod token.
====


== Examples
[source,bash]
----
# Get the GraphQL Playground for the database
$ astra db endpoints playground mydb

# Get the GraphQL Playground for the database in a specific region
$ astra db endpoints playground mydb --region us-east1
----


