= astra token get

[source,shell]
----
astra token get [-cqV] [--no-input] [--[no-]spinner] [--validate] [--dump-logs
                [=FILE]] [--color=WHEN] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
                [--token=TOKEN [--env=ENV]]]

----


Show your current token

== Aliases

`astra token`




== Options

`-c`, `--copy`:: Copy the token to clipboard instead of printing it
`--validate`:: Validates the token before returning it

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Show your current token
$ astra token get
----


