= astra db truncate-collection

[source,shell]
----
astra db truncate-collection [-qV] [--no-input] [--[no-]spinner] [--dump-logs
                             [=FILE]] [-c=COLLECTION] [--color=WHEN]
                             [-k=KEYSPACE] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]]
                             | [--token=TOKEN [--env=ENV]]] [DB]

----


Atomically delete all documents in a Data API collection





== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--keyspace`:: The keyspace to use
`-c`, `--collection`:: The collection to use
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Truncate a collection in the default keyspace
$ astra db truncate-collection my_db -c my_collection

# Truncate a collection in a specific keyspace
$ astra db truncate-collection my_db -k my_keyspace -c my_collection
----


