= astra user get

[source,shell]
----
astra user get [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]] [--dump-logs
               [=FILE]] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
               [--env=ENV]]] USER

----


Show details for a specific user

== Aliases

`astra user describe`




== Options

`USER`:: User email/id to get

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Get details for a specific user by email
$ astra user get john@example.com

# Get details for a specific user by ID
$ astra user get 12345678-abcd-1234-abcd-123456789012
----


