= astra db cqlsh path

[source,shell]
----
astra db cqlsh path [-qV] [--if-exists] [--no-input] [--[no-]spinner]
                    [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT]
                    [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]

----


Get the path to the currently installed cqlsh executable





== Options

`--if-exists`:: Only return path if cqlsh exists, don't install automatically
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Get the path to the cqlsh executable
$ astra db cqlsh path

# Use the cqlsh exe to run a custom command
$ $(astra db cqlsh path) --help

# Get path only if cqlsh exists, don't install
$ astra db cqlsh path --if-exists
----


