= astra streaming pulsar shell

[source,shell]
----
astra streaming pulsar shell [-FqV] [--no-input] [-np] [--[no-]spinner]
                             [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT]
                             [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                             [--env=ENV]]] [-e=STATEMENT | -f=FILE] [TENANT]

----


Launch Apache Pulsar shell for a streaming tenant





== Options

`TENANT`:: The name of the tenant to connect to
`-F`, `--fail-on-error`:: Interrupt the shell if a command throws an exception
`-np`, `--no-progress`:: Display raw output of the commands without progress visualization
`-e`, `--execute`:: Execute the statement and quit
`-f`, `--file`:: Input filename with a list of commands to be executed. Each command must be separated by a newline

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Launch pulsar shell for a tenant
$ astra streaming pulsar shell my_tenant
----


