= astra db delete-region

[source,shell]
----
astra db delete-region [-qV] [--[no-]async] [--if-exists] [--no-input] [--[no-]
                       spinner] [--color[=WHEN]] [--dump-logs[=FILE]]
                       [-o=FORMAT] -r=REGION [--timeout=<timeout>] [[[-cf=PATH]
                       [-p=NAME]] | [--token=TOKEN [--env=ENV]]] DB

----


Delete a region from an existing database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-r`, `--region`:: The region to use
`--async`:: Do not wait for the database to become active
`--if-exists`:: Do not fail if region does not exist
`--timeout`:: How long the command should wait for the database to become active

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Delete a region from a database
$ astra db delete-region my_db -r us-west-2

# Delete a region without failing if it doesn't exist
$ astra db delete-region my_db -r us-west-2 --if-exists

# Delete a region without waiting for the database to become active
$ astra db delete-region my_db -r us-west-2 --async
----


