= astra streaming pulsar path

[source,shell]
----
astra streaming pulsar path [-qV] [--if-exists] [--no-input] [--[no-]spinner]
                            [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT]
                            [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                            [--env=ENV]]]

----


Get the path to the currently installed pulsar executable





== Options

`--if-exists`:: Only return path if pulsar exists, don't install automatically

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Get the path to the pulsar executable
$ astra streaming pulsar path

# Use the pulsar exe to run a custom command
$ $(astra streaming pulsar path) --help

# Get path only if pulsar exists, don't install
$ astra streaming pulsar path --if-exists
----


