= astra db list-keyspaces

[source,shell]
----
astra db list-keyspaces [-qV] [--no-input] [--[no-]spinner] [--dump-logs
                        [=FILE]] [--color=WHEN] [-o=FORMAT] [[[-cf=PATH]
                        [-p=NAME]] | [--token=TOKEN [--env=ENV]]] [DB]

----


List all keyspaces in the specified database





== Options

`DB`:: The name or ID of the Astra database to operate on

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# List all keyspaces in a database
$ astra db list-keyspaces my_db
----


