= astra token

[source,shell]
----
astra token [-cqV] [--no-input] [--[no-]spinner] [--validate] [--color[=WHEN]]
            [--dump-logs[=FILE]] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
            [--token=TOKEN [--env=ENV]]] [COMMAND]

----


Manage your Astra tokens


**Alias of `astra token get`**


== Subcommands

* xref:astra-token-list.adoc[astra token list]
* xref:astra-token-get.adoc[astra token get]
* xref:astra-token-create.adoc[astra token create]
* xref:astra-token-delete.adoc[astra token delete]


== Options

`-c`, `--copy`:: Copy the token to clipboard instead of printing it
`--validate`:: Validates the token before returning it

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Astra environment the token belongs to: prod (default), dev, or test. Leave unset unless you were issued a non-prod token.
====


== Examples
[source,bash]
----
# Show your current token
$ astra token

# Copy your current token
$ astra token -c

# Show a token from a different profile
$ astra token -p <profile>
----


