= astra db endpoints list

[source,shell]
----
astra db endpoints list [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]]
                        [--dump-logs[=FILE]] [-o=FORMAT] [-r=REGION]
                        [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]
                        [DB]

----


Get the various endpoints for a database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-r`, `--region`:: The region to use

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# List the various endpoints for the specified database
$ astra db endpoints list my_db

# List the various endpoints for a prompted db
$ astra db endpoints list
----


