= astra db delete

[source,shell]
----
astra db delete [-qV] [--[no-]async] [--if-exists] [--no-input] [--[no-]
                spinner] [--yes] [--dump-logs[=FILE]] [--color=WHEN]
                [-o=FORMAT] [--timeout=<timeout>] [[[-cf=PATH] [-p=NAME]] |
                [--token=TOKEN [--env=ENV]]] [DB]

----


Delete an existing Astra database





== Options

`DB`:: The name or ID of the Astra database to operate on
`--if-exists`:: Do not fail if database does not exist
`--yes`:: Force deletion of database without prompting
`--async`:: Do not wait for the database to become active
`--timeout`:: How long the command should wait for the database to become active
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Delete an existing Astra database
$ astra db delete my_db

# Delete an existing Astra database without confirmation (required for non-interactive shells)
$ astra db delete my_db --yes

# Delete an existing Astra database without failing if it does not exist
$ astra db delete my_db --if-exists

# Delete an existing Astra database without waiting for complete termination
$ astra db delete my_db --async
----


