= astra db delete-cdc

[source,shell]
----
astra db delete-cdc [-qV] [--if-exists] [--no-input] [--[no-]spinner]
                    [--dump-logs[=FILE]] [--color=WHEN] [-o=FORMAT]
                    [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]
                    (--cdc-id=CDC_ID | [-k=KEYSPACE --table=TABLE
                    --tenant=TENANT]) [DB]

----


Delete a CDC (Change Data Capture) from the database





== Options

`DB`:: The name or ID of the Astra database to operate on
`--if-exists`:: Do not fail if CDC does not exist
`--cdc-id`:: The CDC ID to delete
`-k`, `--keyspace`:: The keyspace
`--table`:: The table
`--tenant`:: The tenant name

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Delete a CDC by ID
$ astra db delete-cdc my_db --cdc-id abc123

# Delete a CDC by table and tenant
$ astra db delete-cdc my_db -k my_keyspace --table my_table --tenant my_tenant

# Delete a CDC without failing if it doesn't exist
$ astra db delete-cdc my_db --cdc-id abc123 --if-exists
----


