= astra pcu unpark

[source,shell]
----
astra pcu unpark [-qV] [--[no-]async] [--no-input] [--[no-]spinner] [--color
                 [=WHEN]] [--dump-logs[=FILE]] [-o=FORMAT]
                 [--timeout=<timeout>] [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                 [--env=ENV]]] [GROUP]

----


Unpark a parked PCU group





== Options

`GROUP`:: The name or ID of the PCU group to work with
`--async`:: Do not wait for the database to become active
`--timeout`:: How long the command should wait for the database to become active

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Unpark a parked PCU group
$ astra pcu unpark my_pcu
----


