= astra db create-keyspace

[source,shell]
----
astra db create-keyspace [-qV] [--[no-]async] [--if-not-exists] [--no-input] [--
                         [no-]spinner] [--dump-logs[=FILE]] [--color=WHEN]
                         -k=KEYSPACE [-o=FORMAT] [--timeout=<timeout>]
                         [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN [--env=ENV]]]
                         [DB]

----


Create a new keyspace in the specified database





== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--keyspace`:: The keyspace to use
`--if-not-exists`:: Don't error if a keyspace with the same name already exists
`--async`:: Do not wait for the database to become active
`--timeout`:: How long the command should wait for the database to become active

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Create a new keyspace
$ astra db create-keyspace my_db -k my_keyspace

# Create a new keyspace without failing if it already exists
$ astra db create-keyspace my_db -k my_keyspace --if-not-exists

# Create a new keyspace without waiting for the database to become active
$ astra db create-keyspace my_db -k my_keyspace --async
----


