= astra db describe-table

[source,shell]
----
astra db describe-table [-qV] [--no-input] [--[no-]spinner] [--dump-logs
                        [=FILE]] [--color=WHEN] [-k=KEYSPACE] [-o=FORMAT]
                        [-t=TABLE] [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
                        [--env=ENV]]] [DB]

----


Describe an existing table with detailed information including columns and primary key structure





== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--keyspace`:: The keyspace to use
`-t`, `--table`:: The table to use
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment


== Examples
[source,bash]
----
# Describe a table in the default keyspace
$ astra db describe-table my_db -t my_table

# Describe a table in a specific keyspace
$ astra db describe-table my_db -k my_keyspace -t my_table
----


