= astra org get

[source,shell]
----
astra org get [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]] [--dump-logs
              [=FILE]] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] | [--token=TOKEN
              [--env=ENV]]]

----


Get your organization's information

The ``--token`` flag is handy to quickly get information about another organization.

Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.

== Aliases

`astra org`




== Options


.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Get your organization's information
$ astra org

# Get information about another organization
$ astra org get --token AstraCS:...
----


