= astra db get

[source,shell]
----
astra db get [-qV] [--no-input] [--[no-]spinner] [--color[=WHEN]] [--dump-logs
             [=FILE]] [-k=KEY] [-o=FORMAT] [[[-cf=PATH] [-p=NAME]] |
             [--token=TOKEN [--env=ENV]]] [DB]

----


Get information about a specific database.

== Aliases

`astra db describe`




== Options

`DB`:: The name or ID of the Astra database to operate on
`-k`, `--key`:: Specific database attribute to retrieve

.Common Options
[%collapsible]
====
`-o`, `--output`:: One of: human, json, csv
`-V`, `--verbose`:: Enable verbose logging output
`-q`, `--quiet`:: Only output essential information
`--spinner`:: Enable/disable loading spinners
`--no-input`:: Don't ask for user input (e.g. confirmation prompts)
`--color`:: One of: auto, never, always
`--dump-logs`:: Write all logs to an optionally specified file
====

.Connection Options
[%collapsible]
====
`-cf`, `--config-file`:: The ``.astrarc`` file to use for this command
`-p`, `--profile`:: The ``.astrarc`` profile to use for this command. Can be set via ``ASTRA_PROFILE``.
`--token`:: The astra token to use for this command. Use the ``--token @file`` syntax to read the token from a file, to avoid potential leaks.
`--env`:: Override the target astra environment
====


== Examples
[source,bash]
----
# Get information about a specific database
$ astra db get my_db

# Get a specific attribute of a database
$ astra db get my_db --key id
----


