= Get started with the {product}
:navtitle: Get started

Initialize the {product} and run your first commands.

== Prerequisites

To configure the {product}:

*  xref:ROOT:installation.adoc[Install the {product}].

* You must have an active {astra-url}[{product-short} account^].

* [[get-credentials]]You must have an xref:astra-db-serverless:administration:manage-application-tokens.adoc[application token] that is assigned a _role_ with adequate _permissions_ to perform the tasks you'd like to accomplish with the {product}.

** *Non-production organizations*: If your {product-short} organization has no databases or streaming tenants that handle sensitive information, you can grant your application token the `Organization Administrator` role to try out all of the {product} features.

** *Production organizations*: If you're using {product-short} in production, {company} recommends that you use a xref:astra-db-serverless:administration:manage-database-access.adoc#custom-roles[custom role] to grant your application token the bare minimum xref:astra-db-serverless:administration:manage-database-access.adoc#about-permissions[permissions] required to perform the required tasks with the {product}.

* If you plan to manage an {astra_db} database that has restricted public access, then you must xref:astra-db-serverless:administration:manage-database-ip-access-list.adoc#add-ip-access-list-entries[add your IP address to the database's access list].

[#initialize]
== Initialize the {product}

After installation, initialize the {product} and connect it to an existing {product-short} account.

. Use the `astra setup` command to initialize the {product} with your xref:astra-db-serverless:administration:manage-application-tokens.adoc[application token]:
+
[source,bash,subs="+quotes"]
----
astra setup --token *APPLICATION_TOKEN*
----
+
Replace `*APPLICATION_TOKEN*` with your application token.
The token format is `AstraCS:` followed by a unique token string.
+
.Result
[%collapsible]
====
[source,console]
----
[OK]    Configuration has been saved.
[OK]    Setup completed.
[INFO]  Enter 'astra help' to list available commands.
----
====

. List the {product} configuration to confirm that your token is in use:
+
[source,bash]
----
astra config list
----
+
.Result
[%collapsible]
====
[source,console]
----
+--------------------------------+
| configuration                  |
+--------------------------------+
| alex@altostrat.com (in use)    |
+--------------------------------+
----
====

The {product} is initialized and your application token is set as the default configuration.
The {product} stores configurations and their associated application tokens in the `~/.astrarc` file.
To create additional configurations, see <<manage-configuration>>.

[IMPORTANT]
====
Application tokens are stored in plain text in the `~/.astrarc` file.
Your application tokens are like passwords, therefore you should take precautions to secure the configuration file.
====

== Print help information

Use `astra help` to print general {product} help information:

[source,bash]
----
astra help
----

.Result
[%collapsible]
====
[source,console]
----
usage: astra <command> [ <args> ]

Commands are:
    ?           Display this help version
    help        Display help information
    login       Authenticate against Astra.
    setup       Initialize configuration file
    config      Manage configuration file
    db          Manage databases
    org         Display Organization Info
    role        Manage roles
    streaming   Manage Streaming tenants
    token       Manage tokens
    user        Manage users

See 'astra help <command>' for more information on a specific command.
----
====

Append a command name to print help information about an individual command.
For example:

[source,bash]
----
astra help db
----

.Result
[%collapsible]
====
[source,console]
----
NAME
        astra db - Manage databases

SYNOPSIS
        astra db { count | cqlsh | create | create-cdc | create-collection |
                create-dotenv | create-keyspace | create-region | delete |
                delete-cdc | delete-collection | delete-keyspace |
                delete-region | describe | download-scb | get |
                get-endpoint-api | get-endpoint-playground |
                get-endpoint-swagger | list* | list-cdc | list-clouds |
                list-collections | list-keyspaces | list-regions |
                list-regions-classic | list-regions-serverless |
                list-regions-vector | load | resume | status | unload } [--]
                [ --token <AUTH_TOKEN> ] [ --no-color ] [ {-v | --verbose} ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ {-cf | --config-file} <CONFIG_FILE> ] [ --env <Environment> ]
                [ {-o | --output} <FORMAT> ] [cmd-options] <cmd-args>

        Where command-specific options [cmd-options] are:
            count: [ {-k | --keyspace} <KEYSPACE> ] [ -encoding <ENCODING> ] [ {-t | --table} <TABLE> ]
                    [ {-query | --schema.query} <QUERY> ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                    [ -maxConcurrentQueries <maxConcurrentQueries> ] [ -logDir <log directory> ]
            cqlsh: [ --debug ] [ {-f | --file} <FILE> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --version ] [ --connect-timeout <TIMEOUT> ] [ {-e | --execute} <STATEMENT> ]
                    [ --request-timeout <TIMEOUT> ] [ --encoding <ENCODING> ]
            create: [ {-c | --cloud} <cloud> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --vector ] [ --timeout <timeout> ] [ {-r | --region} <DB_REGION> ]
                    [ {--if-not-exist | --if-not-exists} ] [ --async ] [ --tier <TIER> ]
                    [ --capacity-units <CAPACITY UNITS> ]
            create-cdc: [ {-k | --keyspace} <KEYSPACE> ] [ --tenant <TENANT> ]
                    [ -p, --partition <PARTITION TOKEN> ] [ --table <TABLE> ]
            create-collection: [ {-m | --metric} <METRIC> ] {-c | --collection}
                    <COLLECTION> [ {-d | --dimension} <DIMENSION> ]
            create-dotenv: [ {-k | --keyspace} <KEYSPACE> ] [ {-d | --directory} <DIRECTORY> ]
                    [ {-r | --region} <DB_REGION> ]
            create-keyspace: {-k | --keyspace} <KEYSPACE> [ --if-not-exist ] [ --wait ]
            create-region: [ {-c | --cloud} <CLOUD> ] [ --timeout <timeout> ]
                    {-r | --region} <REGION> [ --wait ] [ {-t | --tier} <CLOUD> ]
                    [ --async ] [ --if-not-exist ]
            delete: [ --async ] [ --timeout <timeout> ] [ --wait ]
            delete-cdc: [ {-k | --keyspace} <KEYSPACE> ] [ -id <CDC_ID> ] [ --tenant <TENANT> ]
                    [ --table <TABLE> ]
            delete-collection: {-c | --collection} <COLLECTION>
            delete-keyspace: {-k | --keyspace} <KEYSPACE>
            delete-region: [ --async ] [ --timeout <timeout> ] {-r | --region}
                    <REGION> [ --wait ]
            describe: [ {-k | --key} <Key> ]
            download-scb: [ {-f | --output-file} <DEST> ] [ {-r | --region} <DB_REGION> ]
            get: [ {-k | --key} <Key> ]
            get-endpoint-api: [ {-r | --region} <DB_REGION> ]
            get-endpoint-playground: [ {-r | --region} <DB_REGION> ]
            get-endpoint-swagger: [ {-r | --region} <DB_REGION> ]
            list: [ --vector ]
            list-cdc:
            list-clouds:
            list-collections:
            list-keyspaces:
            list-regions:
            list-regions-classic: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            list-regions-serverless: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            list-regions-vector: [ {-c | --cloud} <CLOUD> ] [ {-f | --filter} <filter> ]
            load: [ {-k | --keyspace} <KEYSPACE> ] [ -maxErrors <maxErrors> ] [ -encoding <ENCODING> ]
                    [ {-t | --table} <TABLE> ] [ {-query | --schema.query} <QUERY> ]
                    [ -skipRecords <skipRecords> ] [ --schema.allowMissingFields <allowMissingFields> ]
                    -url <url> [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -dryRun ]
                    [ -header <header> ] [ -delim <delim> ] [ -maxConcurrentQueries <maxConcurrentQueries> ]
                    [ -logDir <log directory> ] [ {-m | --schema.mapping} <mapping> ]
            resume: [ --async ] [ --timeout <timeout> ] [ --wait ]
            status:
            unload: [ {-k | --keyspace} <KEYSPACE> ] [ -maxErrors <maxErrors> ]
                    [ -encoding <ENCODING> ] [ {-t | --table} <TABLE> ] [ {-query | --schema.query} <QUERY> ]
                    [ -skipRecords <skipRecords> ] [ -url <url> ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                    [ -header <header> ] [ -delim <delim> ] [ -maxConcurrentQueries <maxConcurrentQueries> ]
                    [ -logDir <log directory> ] [ {-m | --schema.mapping} <mapping> ]

        Where command-specific arguments <cmd-args> are:
            count: <DB>
            cqlsh: <DB>
            create: <DB>
            create-cdc: <DB>
            create-collection: <DB>
            create-dotenv: <DB>
            create-keyspace: <DB>
            create-region: <DB>
            delete: <DB>
            delete-cdc: <DB>
            delete-collection: <DB>
            delete-keyspace: <DB>
            delete-region: <DB>
            describe: <DB>
            download-scb: <DB>
            get: <DB>
            get-endpoint-api: <DB>
            get-endpoint-playground: <DB>
            get-endpoint-swagger: <DB>
            list:
            list-cdc: <DB>
            list-clouds:
            list-collections: <DB>
            list-keyspaces: <DB>
            list-regions: <DB>
            list-regions-classic:
            list-regions-serverless:
            list-regions-vector:
            load: <DB>
            resume: <DB>
            status: <DB>
            unload: <DB>

        Where * indicates the default command(s)
        See 'astra help db <command>' for more information on a specific command.
----
====

Append a subcommand for further specificity:

[source,bash]
----
astra help db list
----

.Result
[%collapsible]
====
[source,console]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled
----
====

== Set up auto-completion

The {product} provides Bash auto-completion for `bash` and `zsh` shells.

To use auto-completion, type the `astra` command and then press kbd:[Tab] twice to get a list of available options.

[source,bash,subs="macros"]
----
astra kbd:[Tab] kbd:[Tab]
----

.Result
[%collapsible%open]
====
[source,console]
----
 --no-color  config      db          help        role        setup       shell       user
----
====

[#manage-configuration]
== Manage the {product} configuration

When you run the `astra setup` command during <<initialize,initialization>>, the {product} stores your application token as the default configuration in the `~/.astrarc` configuration file.

You can create additional configurations, each with their own application token, to make it easier to manage different types of resources across one or more organizations.

=== Get and set configurations

. Use `astra config list` to list all current configurations:
+
[source,bash]
----
astra config list
----
+
.Result
[%collapsible]
====
[source,console]
+----------------------------+
| configuration              |
+----------------------------+
| Organization 1 (in use)    |
| Organization 2             |
+----------------------------+
====

. Use `astra config create` to create a new configuration:
+
[source,bash,subs="+quotes"]
----
astra config create "**CONFIG_NAME**" --token **APPLICATION_TOKEN**
----
+
.Result
[%collapsible]
====
[source,console]
----
[OK]    Configuration has been saved.
----
====

. Use `astra config use` to change the default configuration that {product} uses when executing commands:
+
[source,bash,subs="+quotes"]
----
astra config use "**CONFIG_NAME**"
----
+
.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
[OK]    Section '**CONFIG_NAME**' is set as default.
----
====

. Optional: Rerun `astra config list` to verify that the new default configuration is set.

=== Set the configuration for a single run

Every {product} command supports the `--config` option.
This option lets you use a different configuration when running a command without changing the default configuration.
For example:

[source,bash,subs="+quotes"]
----
astra user list --config "**CONFIG_NAME**"
----

Alternatively, you can use the `--token` option to supply an application token when running a command.
This option lets you use a different application token without having to create a new configuration.
For example:

[source,bash,subs="+quotes"]
----
astra user list --token "**APPLICATION_TOKEN**"
----

=== Delete a configuration

Use `astra config delete` to delete a configuration:

[source,bash,subs="+quotes"]
----
astra config delete "**CONFIG_NAME**"
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
[OK]    Section '**CONFIG_NAME**' has been deleted.
----
====

[IMPORTANT]
====
If you delete the default configuration, the {product} _doesn't_ automatically select a new default configuration.
Use the `astra config use` command to select a new default configuration.
====

=== `config` options

The following options are available for the `astra config` command:

[source,console]
----
NAME
        astra config - Manage configuration file

SYNOPSIS
        astra config { create | delete | describe | get | list* | use } [--]
                [ {-cf | --config-file} <CONFIG_FILE> ] [ --no-color ]
                [ {-v | --verbose} ] [ {-o | --output} <FORMAT> ] [cmd-options]
                <cmd-args>

        Where command-specific options [cmd-options] are:
            create: [ {-e | --env} <Environment> ] [ {-t | --token} <AuthToken> ]
            delete:
            describe: [ {-k | --key} <Key in the section> ]
            get: [ {-k | --key} <Key in the section> ]
            list:
            use:

        Where command-specific arguments <cmd-args> are:
            create: [ <sectionName> ]
            delete: <sectionName>
            describe: <sectionName>
            get: <sectionName>
            list:
            use: <sectionName>

        Where * indicates the default command(s)
        See 'astra help config <command>' for more information on a specific command.
----

See the following sections for `config` subcommand options:

.Expand to see all `config create` options
[%collapsible]
====
[source,console]
----
NAME
        astra config create - Create a new section in configuration

SYNOPSIS
        astra config create [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-e | --env} <Environment> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-t | --token} <AuthToken> ]
                [ {-v | --verbose} ] [--] [ <sectionName> ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -e <Environment>, --env <Environment>
            Environment to use for this section.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -t <AuthToken>, --token <AuthToken>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config delete` options
[%collapsible]
====
[source,console]
----
NAME
        astra config delete - Delete section in configuration

SYNOPSIS
        astra config delete [ {-cf | --config-file} <CONFIG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-v | --verbose} ] [--] <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config describe` options
[%collapsible]
====
[source,console]
----
NAME
        astra config describe - Show details for a configuration.

SYNOPSIS
        astra config describe [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-k | --key} <Key in the section> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -k <Key in the section>, --key <Key in the section>
            If provided return only value for a key.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config get` options
[%collapsible]
====
[source,console]
----
NAME
        astra config get - Show details for a configuration.

SYNOPSIS
        astra config get [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-k | --key} <Key in the section> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -k <Key in the section>, --key <Key in the section>
            If provided return only value for a key.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

.Expand to see all `config list` options
[%collapsible]
====
[source,console]
----
NAME
        astra config list - Show the list of available configurations.

SYNOPSIS
        astra config list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-v | --verbose} ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console
----
====

.Expand to see all `config use` options
[%collapsible]
====
[source,console]
----
NAME
        astra config use - Make a section the one used by default

SYNOPSIS
        astra config use [ {-cf | --config-file} <CONFIG_FILE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-v | --verbose} ] [--]
                <sectionName>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <sectionName>
            Section in configuration file to as as default.
----
====

== Next steps

* xref:ROOT:managing.adoc[]
* xref:ROOT:astra-streaming-cli.adoc[]
* xref:ROOT:administration.adoc[]