= Connect the {product} to your Astra account
:navtitle: Connect to your Astra account
// include::astra-db-serverless:ROOT:partial$astra-role-attributes.adoc[]
// include::astra-db-serverless:ROOT:partial$astra-permission-attributes.adoc[]

Initialize the Astra CLI and run your first commands.

== Prerequisites

To configure the {product}:

* You must have an active {url-astra}[Astra account^].

* You must have an xref:astra-db-serverless:administration:manage-application-tokens.adoc[application token] that is assigned a _role_ with adequate _permissions_ to perform the tasks you'd like to accomplish with the {product}.
For more information, see <<get-credentials>>.

* If you plan to manage an {astra_db} database that has restricted public access, then you must xref:astra-db-serverless:administration:manage-database-ip-access-list.adoc#add-ip-access-list-entries[add your IP address to the database's access list].

[#get-credentials]
== Retrieve your application token

The Astra CLI requires an _application token_ to authenticate with Astra.
For instructions on how to create an application token, see xref:astra-db-serverless:administration:manage-application-tokens.adoc[].

Non-production environments::
To try out all the {product} features, grant your application token the `Organization Administrator` role.

Production environments::
If you're using Astra in production, {company} recommends that you use a xref:astra-db-serverless:administration:manage-database-access.adoc#custom-roles[custom role] to grant your application token the bare minimum xref:astra-db-serverless:administration:manage-database-access.adoc#about-permissions[permissions] required to perform the tasks you'll be doing with the {product}.

== Set up a new configuration

To initialize the {product} and connect to an existing Astra account, pass your <<get-credentials,application token>> with the `astra setup` command:

[source,bash,subs="verbatim,quotes"]
----
astra setup --token *APPLICATION_TOKEN*
----

Replace `*APPLICATION_TOKEN*` with your application token.
The token format is `AstraCS:` followed by a unique token string.
For example:

[source,bash]
----
astra setup --token AstraCS:ozgLKiotAPSgFvBylkUEdPzB:3d061eaa636a6a032f352588f5ba2b777fefdd80f201640063576a9732c4a54d
----

.Result
[%collapsible]
====
[source,bash]
----
[OK]    Configuration has been saved.
[OK]    Setup completed.
[INFO]  Enter 'astra help' to list available commands.
----
====

Display the current {product} configuration to confirm that setup is complete:

[source,bash]
----
astra config list
----

.Result
[%collapsible]
====
[source,bash]
----
+--------------------------------+
| configuration                  |
+--------------------------------+
| alex@altostrat.com (in use)    |
+--------------------------------+
----
====

The {product} is now initialized and connected to your Astra account.
The {product} configuration, including your application token, is stored in the `~/.astrarc` file.
The information in this file is used whenever you run the `astra` command.

[IMPORTANT]
====
Application tokens are stored in plaintext in the {product} configuration file.
Your application tokens are like passwords, and you should take precautions to secure the configuration file.
====

[#first-commands]
== First commands

* Display the current version of the CLI.

[source,bash]
----
astra --version
----

* Display your configuration list, validating setup is complete.

[source,bash]
----
astra config list
----

Output:

[source,bash]
----
 +-----------------------------------------+
 | configuration                           |
 +-----------------------------------------+
 | alex@altostrat.com                      |
 +-----------------------------------------+
----

== Get help

Once installed, the {product} provides extensive documentation for any command.

It also provides some bash autocompletion, use the `TAB` key twice to get a list of propositions.

*Autocompletion*

[source,bash]
----
astra <TAB> <TAB>
----

Output:

[source,bash]
----
 --no-color  config      db          help        role        setup       shell       user
----

* Command-line documentation*

Groups of command will get you the different command avalable.

* Display main help

[source,bash]
----
astra help
----

Output:

[source,bash]
----
usage: astra <command> [ <args> ]

Commands are:
    help     View help for any command
    setup    Initialize configuration file
    shell    Interactive mode (default if no command provided)
    config   Manage configuration file
    db       Manage databases
    role     Manage roles (RBAC)
    user     Manage users

See 'astra help <command>' for more information on a specific command.
----

* Display help for a command group, such as: `astra db`

[source,bash]
----
astra help db
----

Output:

[source,bash]
----
NAME
        astra db - Manage databases

SYNOPSIS
        astra db { cqlsh | create | create-keyspace | delete | dsbulk | get |
                list } [--] [ --token <AUTH_TOKEN> ]
                [ --config-file <CONFIG_FILE> ] [ --no-color ]
                [ {-v | --verbose} ] [ {-conf | --config} <CONFIG_SECTION> ]
                [ --log <LOG_FILE> ] [ {-o | --output} <FORMAT> ] [cmd-options]
                <cmd-args>

        Where command-specific options [cmd-options] are:
            cqlsh: [ --debug ] [ {-f | --file} <FILE> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --version ] [ {-e | --execute} <STATEMENT> ] [ --encoding <ENCODING> ]
            create: [ {-k | --keyspace} <KEYSPACE> ] [ --if-not-exist ] [ {-r | --region} <DB_REGION> ]
            create-keyspace: {-k | --keyspace} <KEYSPACE> [ --if-not-exist ]
            delete:
            dsbulk:
            get:
            list:

        Where command-specific arguments <cmd-args> are:
            cqlsh: <DB>
            create: <DB_NAME>
            create-keyspace: <DB>
            delete: <DB>
            dsbulk: [ <dsbulkArguments>... ]
            get: <DB>
            list:

        See 'astra help db <command>' for more information on a specific command.
----

* Display help for a specific command, such as: `astra db list`

For unitary commands all options details are provided.

[source,bash]
----
astra help db list
----

Output:

[source,bash]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-conf | --config} <CONFIG_SECTION> ]
                [ --config-file <CONFIG_FILE> ] [ --log <LOG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ]

OPTIONS
        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --log <LOG_FILE>
            Logs will go in the file plus on console

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----

