= Getting started with {product}

Initialize the Astra CLI and run your first commands.

[#get-credentials]
== Retrieve your application token

The Astra CLI requires an _application token_ to authenticate with Astra.
For instructions on how to create an application token, see xref:astra-db-serverless:administration:manage-application-tokens.adoc[].

To increase the security of your Astra account, DataStax recommends that you grant your application token only the bare minimum xref:astra-db-serverless:administration:manage-database-access.adoc[permissions] required to perform the tasks you'll be running in Astra.

== Set up a new configuration

Use the `astra setup` command to initialize the Astra CLI:

[source,bash,subs="verbatim,quotes"]
----
astra setup --token *APPLICATION_TOKEN*
----

Replace `*APPLICATION_TOKEN*` with your <<get-credentials,application token>>.
The token format is `AstraCS:` followed by a unique token string.

.Result
[%collapsible]
====
[source,bash]
----
[OK]    Configuration has been saved.
[OK]    Setup completed.
[INFO]  Enter 'astra help' to list available commands.
----
====

The Astra CLI is now initialized and ready to use.

The Astra CLI configuration, including your application token, is stored in `~/.astrarc`.
The information in this file is used whenever you run the `astra` command.

[#first-commands]
== First commands

* Display the current version of the CLI.

[source,bash]
----
astra --version
----

* Display your configuration list, validating setup is complete.

[source,bash]
----
astra config list
----

Output:

[source,bash]
----
 +-----------------------------------------+
 | configuration                           |
 +-----------------------------------------+
 | alex@altostrat.com                      |
 +-----------------------------------------+
----

== Get Help

Once installed, {product} provides extensive documentation for any command.

It also provides some bash autocompletion, use the `TAB` key twice to get a list of propositions.

*Autocompletion*

[source,bash]
----
astra <TAB> <TAB>
----

Output:

[source,bash]
----
 --no-color  config      db          help        role        setup       shell       user
----

* Command-line documentation*

Groups of command will get you the different command avalable.

* Display main help

[source,bash]
----
astra help
----

Output:

[source,bash]
----
usage: astra <command> [ <args> ]

Commands are:
    help     View help for any command
    setup    Initialize configuration file
    shell    Interactive mode (default if no command provided)
    config   Manage configuration file
    db       Manage databases
    role     Manage roles (RBAC)
    user     Manage users

See 'astra help <command>' for more information on a specific command.
----

* Display help for a command group, such as: `astra db`

[source,bash]
----
astra help db
----

Output:

[source,bash]
----
NAME
        astra db - Manage databases

SYNOPSIS
        astra db { cqlsh | create | create-keyspace | delete | dsbulk | get |
                list } [--] [ --token <AUTH_TOKEN> ]
                [ --config-file <CONFIG_FILE> ] [ --no-color ]
                [ {-v | --verbose} ] [ {-conf | --config} <CONFIG_SECTION> ]
                [ --log <LOG_FILE> ] [ {-o | --output} <FORMAT> ] [cmd-options]
                <cmd-args>

        Where command-specific options [cmd-options] are:
            cqlsh: [ --debug ] [ {-f | --file} <FILE> ] [ {-k | --keyspace} <KEYSPACE> ]
                    [ --version ] [ {-e | --execute} <STATEMENT> ] [ --encoding <ENCODING> ]
            create: [ {-k | --keyspace} <KEYSPACE> ] [ --if-not-exist ] [ {-r | --region} <DB_REGION> ]
            create-keyspace: {-k | --keyspace} <KEYSPACE> [ --if-not-exist ]
            delete:
            dsbulk:
            get:
            list:

        Where command-specific arguments <cmd-args> are:
            cqlsh: <DB>
            create: <DB_NAME>
            create-keyspace: <DB>
            delete: <DB>
            dsbulk: [ <dsbulkArguments>... ]
            get: <DB>
            list:

        See 'astra help db <command>' for more information on a specific command.
----

* Display help for a specific command, such as: `astra db list`

For unitary commands all options details are provided.

[source,bash]
----
astra help db list
----

Output:

[source,bash]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-conf | --config} <CONFIG_SECTION> ]
                [ --config-file <CONFIG_FILE> ] [ --log <LOG_FILE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ]

OPTIONS
        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        --log <LOG_FILE>
            Logs will go in the file plus on console

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----

