= {product}
:page-layout: landing

The DataStax Astra Command-Line Interface ({product}) is a free utility that you can use to create and manage Astra resources.
{product} is available across Astra services and is designed to get you working quickly with {astra_db} and {astra_stream}, with an emphasis on automation.

With {product}, you can manage Astra resources from the command line instead of (or in addition to) the {astra_ui} and Astra DevOps API calls.

{product} features are for operators, Site Reliability Engineers (SREs), and developers who want the option of using commands when working with {astra_db} databases and {astra_stream} tenants.
The tools should be complementary and not restrictive, so choose what tool works best for you.

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="grid gap-6 lg:grid-cols-3">
  <div class="grid gap-4">

    svg:ROOT:icons/datastax/create-db-now.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Installing and getting started</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:installation.adoc[]
    </div>

    <div class="landing-a">
        xref:getting-started.adoc[]
    </div>

  </div>
  <div class="grid gap-4">

    svg:ROOT:icons/datastax/what-is-astra-db.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Load data</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:managing.adoc[]
    </div>

  </div>
  <div class="grid gap-4">

    svg:ROOT:icons/datastax/what-is-astra-streaming.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Explore your data</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:astra-streaming-cli.adoc[]
    </div>

  </div>
</div>
++++
