= {astra_cli}
:data-uri:

The DataStax Astra Command-Line Interface ({astra_cli}) is a set of commands used to create and manage Astra resources.
{astra_cli} is available across Astra services and is designed to get you working quickly with {astra_db} and {astra_stream}, with an emphasis on automation.

{astra_cli} makes it possible to submit commands instead of *or in addition to* using {astra_ui} and DataStax API calls.

{astra_cli} features are for operators, Site Reliability Engineers (SREs), and developers who want the option of using commands when working with {astra_db} databases and {astra_stream} tenants.
The tools should be complementary and not restrictive, so choose what tool works best for you.

{astra_cli} is free.

Any user with the **Organization Administrator** role may use {astra_cli} commands with:

* {astra_db} Serverless databases
* {astra_db} Classic databases
* {astra_stream} tenants

Get started with the links below.

++++
<div class="landing-row">
++++

[sidebar.landing-card]
.Installing and getting started
****
--
* xref:installation.adoc[Install {astra_cli}]
* xref:getting-started.adoc[Get started]
--
[.landing-card-body-icon]
image::create-db-now.svg[icon description,40]
****

[sidebar.landing-card]
.Managing {astra_db}
****
--
* xref:managing.adoc[]
--
[.landing-card-body-icon]
image::what-is-astra-db.svg[icon description,40]
****

[sidebar.landing-card]
.Managing {astra_stream}
****
--
* xref:astra-streaming-cli.adoc[]
--
[.landing-card-body-icon]
image::what-is-astra-streaming.svg[icon description,40]
****

++++
</div>
++++
