= {product}
:page-layout: landing

The {product} is a free utility that you can use to create and manage Astra resources.
You can use the {product} to perform common platform tasks for {astra_db} and {astra_stream} from the command line or with automation to control your Astra resources at scale.

To make it even easier to integrate Astra into your applications and workflows, the {product} provides seamless integration with the following external tools:

* DSBulk
* cqlsh
* pulshar-shell
* Useful shortcuts like dotenv file generation

[.[&>h2]:!hidden]
== {empty}

[subs="macros,attributes"]
++++
<div class="grid gap-6 lg:grid-cols-3">
  <div class="grid gap-4">

    svg:common:ROOT:icons/create-db-now.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Get started</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:installation.adoc[]
    </div>

    <div class="landing-a">
        xref:getting-started.adoc[]
    </div>

  </div>
  <div class="grid gap-4">

    svg:common:ROOT:icons/cloud-db.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Manage {astra_db}</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:managing.adoc[]
    </div>

  </div>
  <div class="grid gap-4">

    svg:common:ROOT:icons/streaming.svg[role="mx-auto max-w-xs md:mx-0 lg:max-w-none"]

    <h3 class="discrete !text-h2 !m-0">Manage {astra_stream}</h3>

    <!-- <p>Placeholder text.</p> -->

    <div class="landing-a">
        xref:astra-streaming-cli.adoc[]
    </div>

  </div>
</div>
++++
