= Install or update the {product}
:description: {product} makes it easier to integrate Astra into your applications and workflows by letting you perform common platform tasks for {astra_db} and {astra_stream} from the command line.

Install the {product} to create and manage {astra_db} databases and {astra_stream} tenants from the command line.

== Platform compatibility

The {product} supports the following operating systems:

[cols="1,2"]
|===
|Operating System |Architecture

|Linux
|x86-64, ARM

|macOS
|x86-64, ARM

|Microsoft Windows
|x86-64, ARM

_Requires https://learn.microsoft.com/en-us/windows/wsl/install[Windows Subsystem for Linux (WSL)]_
|===

== Install the {product}

Install the {product} using your preferred method:

[tabs,id=install]
======
Homebrew::
+
--
You can use Homebrew to install the {product} on macOS.

To install the {product} using Homebrew, you must have https://brew.sh/[Homebrew] installed and you must set your macOS app security settings to https://support.apple.com/en-us/102445[allow apps downloaded from App Store and identified developers].

[NOTE]
====
The Homebrew formula installs a native executable for macOS that is not compatible with https://docs.brew.sh/Homebrew-on-Linux[Homebrew on Linux].
To install {product} on Linux-based systems, use <<install-curl,curl>> or one of the other installation methods.
====

. Make sure Homebrew is up to date:
+
[source,bash]
----
brew update
----

. Install the {product}:
+
[source,bash]
----
brew install datastax/astra-cli/astra-cli
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
==> Fetching datastax/astra-cli/astra-cli
==> Downloading https://github.com/datastax/astra-cli/releases/download/...
==> Downloading from https://objects.githubusercontent.com/...
######################################################################### 100.0%
==> Installing astra-cli from datastax/astra-cli
==> Pouring astra-cli-{product-version}.arm64_sonoma.bottle.tar.gz
==> Caveats
You must have python 3.7+ to use cqlsh and java11+ to use dsbulk
==> Summary
ðŸº  /opt/homebrew/Cellar/astra-cli/{product-version}: 4 files, 61.7MB
==> Running `brew cleanup astra-cli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
----
====

. Confirm that the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
+
The command returns the {product} version that is installed.
+
include::ROOT:partial$macos-security-notice.adoc[]

. (Optional) If you haven't done so already, enable https://docs.brew.sh/Shell-Completion[`brew` shell completion].
+
The {product} Homebrew formula installs a completion file named `astra` in the Homebrew-managed completions directory.
If you have shell completion enabled in Homebrew, your terminal will automatically suggest and complete {product} commands and options as you type them.
--

curl::
+
--
You can use `curl` to install the {product} on Linux, macOS, and Windows Subsystem for Linux (WSL).

. Install the {product}:
+
[source,bash]
----
curl -Ls "https://dtsx.io/get-astra-cli" | bash
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----

    _____            __
   /  _  \   _______/  |_____________
  /  /_\  \ /  ___/\   __\_  __ \__  \
 /    |    \___ \  |  |  |  | \// __ \_
 \____|__  /____  > |__|  |__|  (____  /
         \/     \/                   \/

Installing Astra Cli {product-version}  please wait...

Checking prerequisites:
[OK] - Ready to install.
[OK] - unzip command is available
[OK] - curl command is available

Preparing directories:
[OK] - Created /home/USERNAME/.astra/tmp
[OK] - Created /home/USERNAME/.astra/cli
[OK] - Created /home/USERNAME/.astra/scb

Downloading archive:
######################################################################## 100.0%
[OK] - File downloaded
[OK] - Integrity of the archive checked

Extracting and installation:
[OK] - Extraction is successful
[OK] - File moved to /home/USERNAME/.astra/cli
[OK] - Installation cleaned up
[OK] - astra added to /home/USERNAME/.bashrc
[OK] - astra added to /home/USERNAME/.zshrc
[OK] - Installation Successful

Open A NEW TERMINAL and run: astra setup

You can close this window.
----
====
+
The `~/.astra/cli` folder is added to the `PATH` environment variable.
See <<file-locations>> for more information.

. Open a new terminal or restart your existing terminal.

. Confirm that the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
+
The command returns the {product} version that is installed.
+
include::ROOT:partial$macos-security-notice.adoc[]
--

JVM::
+
--
The {product} is available as a packaged Java application that you can use on any machine running a JVM.

To run the {product} in a JVM, you must have Java 17+ installed.
You can install Java by downloading and installing the latest https://www.oracle.com/java/technologies/downloads/[Oracle JDK]

. Verify that Java is version 17 or higher:
+
[source,bash]
----
java --version
----

. Download the latest release from the https://github.com/datastax/astra-cli/releases[{product} GitHub repository]:
+
[source,bash,subs="+attributes"]
----
curl -L -o astra-cli-{product-version}.zip https://github.com/datastax/astra-cli/releases/download/{product-version}/astra-cli-{product-version}.zip
----

. Unzip the archive:
+
[source,bash,subs="+attributes"]
----
unzip astra-cli-{product-version}.zip -d ./astra-cli-{product-version} && cd astra-cli-{product-version}
----

. Confirm that you can successfully run the {product}:
+
[source,bash]
----
java -jar astra-cli.jar --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
+
The command returns the {product} version that is installed.

You can use all options and suffixes on this command when running the JAR file.
For example:

[source,bash]
----
java -jar ./astra-cli.jar db list --token AstraCS:...
----
--

Docker::
+
--
The {product} is available as an https://hub.docker.com/r/datastax/astra-cli[official Docker image] that you can run in a container.

To install the {product} using Docker, you must have the https://docs.docker.com/engine/install/[Docker engine] or https://www.docker.com/products/docker-desktop[Docker desktop] installed.

. Confirm that Docker is installed and running:
+
[source,bash]
----
docker --version
----
+
.Result
[%collapsible]
====
[source,console]
----
Docker version 27.1.1, build 6312585
----
====

. Pull the latest {product} Docker image:
+
[source,bash,subs="+attributes"]
----
docker pull datastax/astra-cli
----
+
.Result
[%collapsible]
====
[source,console]
----
Using default tag: latest
latest: Pulling from datastax/astra-cli
7890eb226106: Pull complete
f4455e290156: Pull complete
e6c3f5cd9c43: Pull complete
322cfd5270ff: Pull complete
Digest: sha256:8dcba8115cbae7bcabfc579341611f30860239ee5edbca3938edea4542ca06fb
Status: Downloaded newer image for datastax/astra-cli:latest
docker.io/datastax/astra-cli:latest

What's next:
    View a summary of image vulnerabilities and recommendations â†’ docker scout quickview datastax/astra-cli
----
====
+
[NOTE]
====
When you run `docker pull datastax/astra-cli`, Docker automatically pulls the latest version of the Docker image (`datastax/astra-cli:latest`).

To pull a specific version of the Docker image, run the following command:

[source,bash,subs="+quotes"]
----
docker pull datastax/astra-cli:**TAG**
----

Replace `**TAG**` with the version tag of the Docker image you want to pull.
====

. Confirm that you can successfully run the {product} in a Docker container:
+
[source,bash]
----
docker run -rm datastax/astra-cli --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
+
The command returns the {product} version that is installed.

. (Optional) Run the {product} with a configuration file:
+
[source,bash,subs="+quotes"]
----
docker run -rm -v **CONFIG_FILE**:/work/.astrarc datastax/astra-cli --version
----
+
Replace `**CONFIG_FILE**`with the path to your {product} configuration file.
For example:
+
[source,bash]
----
docker run -rm -v ~/.astrarc:/work/.astrarc datastax/astra-cli --version
----
+
This command mounts the `~/.astrarc` file from your local machine to the `/work/.astrarc` file in the Docker container.
This lets you use your local configuration file when running the {product} in a Docker container.

. (Optional) Create a shell alias for running the {product} in a Docker container.
+
You can create a shell alias to eliminate the need to include the `docker run` command whenever you want to run the {product} in a Docker container.
For example, the following command creates an alias named `astra`:
+
[source,bash]
----
alias astra='docker run -rm -v ~/.astrarc:/work/.astrarc datastax/astra-cli'
----
+
You can run this command in your terminal to create a temporary alias for the current session, or you can add it to your shell configuration file so that the alias is available in every new terminal session.
+
After you add the alias, you can use it to run {product} commands in a Docker container using the same syntax as the `astra` binary:
+
[source,bash]
----
astra --version
----
--
======

To set up a new configuration and run your first commands, see xref:getting-started.adoc[].

[#file-locations]
=== Installation file locations

The {product} and its configuration are installed in the following locations:


[cols="1,2"]
|===
|File location |Description

|`~/.astra`
a|The {product} installation directory.

For <<install-curl,curl-based installations>>, the `astra` executable and `astra-init.sh` auto-completion script are located in `~/.astra/cli`.
The `~/.astra/cli` folder is added to the `PATH` environment variable.
_This folder is deleted and recreated when you update or re-install the {product}._

For <<install-homebrew,Homebrew-based installations>>, the `astra` executable and auto-completion script are located in https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location[Homebrew's default prefix] at the following locations:

* Executable: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/bin/astra`
* Auto-completion script: `HOMEBREW_PREFIX/Cellar/astra-cli/VERSION/etc/bash_completion.d/astra`

|`~/.astrarc`
|The {product} configuration file.

_This file is *not* deleted when you update or re-install the {product}._
|===

////
== Install additional components

Some {product} commands require you to install additional external components.

=== Install CQL shell (`cqlsh`)


=== Install DataStax Bulk Loader (`dsbulk`)


=== Install Pulsar shell (`pulsar-shell`)
////


== Update the {product}

To update the {product}, follow the procedure for the method you used to originally install the {product}:

[tabs]
======
Homebrew::
+
--
. Make sure Homebrew is up to date:
+
[source,bash]
----
brew update
----

. Update the {product}:
+
[source,bash]
----
brew upgrade datastax/astra-cli/astra-cli
----

. Confirm that the latest version of the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
--

curl::
+
--
. Update the {product}:
+
[source,bash]
----
curl -Ls "https://dtsx.io/get-astra-cli" | bash
----

. Confirm that the latest version of the {product} is installed:
+
[source,bash]
----
astra --version
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
{product-version}
----
====
--
======

== Uninstall the {product}

To uninstall the {product}, follow the procedure for the method you used to originally install the {product}:

[tabs]
======
Homebrew::
+
--
. Uninstall the {product}:
+
[source,bash]
----
brew uninstall datastax/astra-cli/astra-cli
----
+
.Result
[%collapsible]
====
[source,console,subs="+attributes"]
----
Uninstalling /opt/homebrew/Cellar/astra-cli/{product-version}... (4 files, 61.7MB)
----
====

. Delete the {product} and its associated installation files:
+
[source,bash]
----
rm -R ~/.astra
----

. (Optional) Delete the {product} configuration file:
+
[source,bash]
----
rm ~/.astrarc
----
--

curl::
+
--
. Delete the {product} and its associated installation files:
+
[source,bash]
----
rm -R ~/.astra
----

. (Optional) Delete the {product} configuration file:
+
[source,bash]
----
rm ~/.astrarc
----

. (Optional) Remove the {product} from your shell configuration file (for example, `.zshrc` or `.bashrc`).

.. Open your shell configuration file in a text editor.
For example:
+
[source,bash]
----
nano ~/.zshrc
----

.. Remove any lines that reference the {product}.
For example:
+
[source,bash]
----
#THIS MUST BE AT THE END OF THE FILE FOR ASTRA_CLI TO WORK!!!
export ASTRADIR="/Users/USERNAME/.astra/cli"
[[ -s "/Users/USERNAME/.astra/cli/astra-init.sh" ]] && source "/Users/USERNAME/.astra/cli/astra-init.sh"
----

.. Save and close the file.
--
======
