= Introduction to {astra_cli}

The DataStax Astra Command-Line Interface ({astra_cli}) is a set of commands used to create and manage Astra resources. 
{astra_cli} is available across Astra services and is designed to get you working quickly with {astra_db} and {astra_stream}, with an emphasis on automation.

{astra_cli} makes it possible for you to submit commands instead of -- or in addition to -- using {astra_ui} and DataStax API calls. 
{astra_cli} features are for operators, Site Reliability Engineers (SREs), and developers who want the option of using commands when working with {astra_db} databases and {astra_stream} tenants. 

== Prerequisites

* Create an account in https://astra.datastax.com[Astra Portal^].
* Create a token with the `Organization Administration` role, as explained in https://docs.datastax.com/en/astra-serverless/docs/getting-started/gs-grant-user-access.html[this topic^].

== Pricing

{astra_cli} is free.

== Availability

Any user with the **Organization Administration** role may use {astra_cli} commands with:

* {astra_db} Serverless databases
* {astra_db} Classic databases
* {astra_stream} tenants
