= Manage {astra_db} databases with the {product}
:navtitle: Manage {astra_db} databases
:toc: macro
:toc-title:
:toclevels: 1

Use the following {product} commands to manage your {astra_db} databases.
From the command line in a Terminal, the supported tasks are:

toc::[]

== List databases

Use `astra db list` to get a list of all databases in your organization:

[source,bash]
----
astra db list
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| Name                | id                                   | Regions   | Cloud | V | Status    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| vector_db           | 600d564e-2f2f-44d8-9818-6fdb8ca7eb94 | us-east-2 | aws   | ■ | ACTIVE    |
| non_vector_db       | c136ff74-1b6e-4501-a996-686ead1151f1 | us-east-2 | aws   |   | ACTIVE    |
| demo                | 01c0c118-ebce-4a99-a619-369a4cf5d8ff | us-east1  | gcp   |   | ACTIVE    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
----
====

Use the `-o` option to output the result in `csv` or `json` format:

[source,bash]
----
astra db list -o csv
----

.Result
[%collapsible]
====
[source,csv]
----
Name,id,Regions,Cloud,V,Status
vector_db,600d564e-2f2f-44d8-9818-6fdb8ca7eb94,us-east-2,aws,■,ACTIVE
non_vector_db,c136ff74-1b6e-4501-a996-686ead1151f1,us-east-2,aws,,ACTIVE
demo,01c0c118-ebce-4a99-a619-369a4cf5d8ff,us-east1,gcp,,ACTIVE
----
====

[source,bash]
----
astra db list -o json
----

.Result
[%collapsible]
====
[source,json]
----
{
  "code" : 0,
  "message" : "[db, list, -o, json]",
  "data" : [ {
    "Status" : "ACTIVE",
    "V" : "■",
    "Cloud" : "aws",
    "Regions" : "us-east-2",
    "id" : "600d564e-2f2f-44d8-9818-6fdb8ca7eb94",
    "us-east-2" : "us-east-2",
    "Name" : "vector_db"
  }, {
    "Status" : "ACTIVE",
    "V" : "",
    "Cloud" : "aws",
    "Regions" : "us-east-2",
    "id" : "c136ff74-1b6e-4501-a996-686ead1151f1",
    "us-east-2" : "us-east-2",
    "Name" : "non_vector_db"
  }, {
    "Status" : "ACTIVE",
    "V" : "",
    "Cloud" : "gcp",
    "us-east1" : "us-east1",
    "Regions" : "us-east1",
    "id" : "01c0c118-ebce-4a99-a619-369a4cf5d8ff",
    "Name" : "demo"
  } ]
}
----
====

== Create a database

Use `astra db create` to create a new {db-serverless} database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
REGION OK
[INFO]  Database '**DATABASE_NAME**' does not exist. Creating database '**DATABASE_NAME**' with keyspace 'default_keyspace'
get CLoud provider
[INFO]  Database '**DATABASE_NAME**' and keyspace 'default_keyspace' are being created.
[INFO]  Database '**DATABASE_NAME**' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database '**DATABASE_NAME**' has status 'ACTIVE' (took 153147 millis)
[OK]    Database '**DATABASE_NAME**' is ready.
----
====

[TIP]
=====
By default, `astra db create` runs synchronously and doesn't return the command prompt until the database reaches `ACTIVE` or `ERROR` status.
To run the command _asynchronously_, use the `--async` option:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** --async
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
REGION OK
[INFO]  Database '**DATABASE_NAME**' does not exist. Creating database '**DATABASE_NAME**' with keyspace 'default_keyspace'
get CLoud provider
[INFO]  Database '**DATABASE_NAME**' and keyspace 'default_keyspace' are being created.
----
====

The {product} returns the command prompt before the database finishes creating.
Use `astra db list` to monitor the status of the database.
=====

// TODO: Confirm if this still applies.
////
[NOTE]
====
If the database already exists with status `HIBERNATED`, the `astra db create` command <<resume-database,resumes>> the database.
====
////

// TODO: Determine how to address Classic in CLI docs.
////
[NOTE]
====
While you cannot create {astra_db} *Classic* databases with the `astra db create <db-name>` command, you can use other {product} commands to return information about existing {astra_db} Classic databases.
====
////

=== `db create` options

Running `astra db create` without any options deploys the database in an available *Free* region and uses `default_keyspace` as the name for the default keyspace.

For example, you can use the `-c`, `-r`, and `-k` options to define the cloud provider, region, and keyspace name when creating a database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** -c aws -r us-east-1 -k keyspace1
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
REGION OK
[INFO]  Database '**DATABASE_NAME**' does not exist. Creating database '**DATABASE_NAME**' with keyspace 'keyspace1'
get CLoud provider
[INFO]  Database '**DATABASE_NAME**' and keyspace 'keyspace1' are being created.
[INFO]  Database '**DATABASE_NAME**' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database '**DATABASE_NAME**' has status 'ACTIVE' (took 150067 millis)
[OK]    Database '**DATABASE_NAME**' is ready.
----
====

//TODO: Confirm that this no longer applies.
////
The database ID, not the database name, ensures uniqueness within your {astra_db} organization.
Consequently, if you issue the `astra db create` command multiple times, you will create multiple database instances.
To ensure that you don't create a database with the same name as another existing database, use the `--if-not-exist` option:

[source,bash]
----
astra db create demo -r us-east-1 -k keyspace1 --if-not-exist
----
////

[#resume-database]
== Resume a database

Use `astra db resume` to resume a xref:astra-db-serverless:databases:database-statuses.adoc[hibernated] database:

[source,bash,subs="+quotes"]
----
astra db resume **DATABASE_NAME**
----

Resuming the database may take a few minutes.

[TIP]
====
By default, `astra db resume` runs synchronously and doesn't return the command prompt until the database reaches `ACTIVE` or `ERROR` status.
To run the command _asynchronously_, use the `--async` option:

[source,bash,subs="+quotes"]
----
astra db resume **DATABASE_NAME** --async
----

The {product} returns the command prompt before the database finishes resuming.
Use `astra db list` to monitor the status of the database.
====

== Get database details

Use `astra db get` to get information about a database:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME**
----

.Result
[%collapsible]
====
// The extra four spaces after **DATABASE_NAME** ensures proper alignment in the rendered output.
[source,console,subs="+quotes"]
----
+------------------+-----------------------------------------+
| Attribute        | Value                                   |
+------------------+-----------------------------------------+
| Name             | **DATABASE_NAME**                           |
| id               | 01c0c118-ebce-4a99-a619-369a4cf5d8ff    |
| Cloud            | GCP                                     |
| Regions          | us-east1                                |
| Status           | ACTIVE                                  |
| Vector           | Disabled                                |
| Default Keyspace | default_keyspace                        |
| Creation Time    | 2024-09-24T21:08:19Z                    |
|                  |                                         |
| Keyspaces        | [0] default_keyspace                    |
|                  |                                         |
|                  |                                         |
| Regions          | [0] us-east1                            |
|                  |                                         |
+------------------+-----------------------------------------+
----
====

Use the `-o` option to output the result in `csv` or `json` format:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME** -o csv
----

.Result
[%collapsible]
====
[source,csv,subs="+quotes"]
----
Attribute,Value
Name,**DATABASE_NAME**
id,01c0c118-ebce-4a99-a619-369a4cf5d8ff
Cloud,GCP
Regions,us-east1
Status,ACTIVE
Vector,Disabled
Default Keyspace,default_keyspace
Creation Time,2024-09-24T21:08:19Z
Regions,[us-east1]
Keyspaces,[default_keyspace]
----
====

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME** -o json
----

.Result
[%collapsible]
====
[source,json,subs="+quotes"]
----
{
  "code" : 0,
  "message" : "db get **DATABASE_NAME**",
  "data" : {
    "id" : "01c0c118-ebce-4a99-a619-369a4cf5d8ff",
    "orgId" : "2dbd3c55-6a68-4b5b-9155-5be9d41823d8",
    "ownerId" : "FZmCtRdyzJkYidnmlzwcwJWc",
    "creationTime" : "2024-09-24T21:08:19Z",
    "terminationTime" : "0001-01-01T00:00:00Z",
    "lastUsageTime" : "2024-09-24T21:08:19Z",
    "info" : {
      "name" : "**DATABASE_NAME**",
      "keyspace" : "default_keyspace",
      "dbType" : null,
      "keyspaces" : [ "default_keyspace" ],
      "datacenters" : [ {
        "id" : "01c0c118-ebce-4a99-a619-369a4cf5d8ff-1",
        "name" : "dc-1",
        "tier" : "serverless",
        "status" : "",
        "dateCreated" : "2024-09-24T21:08:19Z",
        "cloudProvider" : "GCP",
        "region" : "us-east1",
        "regionZone" : "na",
        "regionClassification" : "standard",
        "capacityUnits" : 1,
        "secureBundleUrl" : "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/01c0c118-ebce-4a99-a619-369a4cf5d8ff-1/secure-connect-**DATABASE_NAME**.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20240924%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240924T231816Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=91e0009b6f7bcfe837c919a133a5ba25a62fa49e073001f04917455f4134438a",
        "secureBundleInternalUrl" : "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/01c0c118-ebce-4a99-a619-369a4cf5d8ff-1/secure-connect-internal-**DATABASE_NAME**.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20240924%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240924T231816Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=79a0d583c791efa8a7d5677e90b69d20d14d8847fdffed12ee38551676296ff3",
        "secureBundleMigrationProxyUrl" : "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/01c0c118-ebce-4a99-a619-369a4cf5d8ff-1/secure-connect-proxy-**DATABASE_NAME**.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20240924%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240924T231816Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=008a1c248b3aa4bc83a7ed6e0d0dd65f670e71568ef2a7a0117ef003429c58c9",
        "secureBundleMigrationProxyInternalUrl" : "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/01c0c118-ebce-4a99-a619-369a4cf5d8ff-1/secure-connect-proxy-internal-**DATABASE_NAME**.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20240924%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20240924T231816Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=bc02762cda92d4cfe77fb231f63c83e7fd3ef1dcf4cddd4701dd4510a5f9a424"
      } ],
      "cloudProvider" : "GCP",
      "tier" : "serverless",
      "capacityUnits" : 1,
      "region" : "us-east1",
      "engineType" : null,
      "additionalKeyspaces" : null
    },
    "status" : "ACTIVE",
    "observedStatus" : "ACTIVE",
    "storage" : {
      "nodeCount" : 3,
      "replicationFactor" : 1,
      "totalStorage" : 5,
      "usedStorage" : 0
    },
    "cost" : {
      "costPerMinCents" : 0.0,
      "costPerHourCents" : 0.0,
      "costPerDayCents" : 0.0,
      "costPerMonthCents" : 0.0,
      "costPerMinMRCents" : 0.0,
      "costPerHourMRCents" : 0.0,
      "costPerDayMRCents" : 0.0,
      "costPerMonthMRCents" : 0.0,
      "costPerMinParkedCents" : 0.0,
      "costPerHourParkedCents" : 0.0,
      "costPerDayParkedCents" : 0.0,
      "costPerMonthParkedCents" : 0.0,
      "costPerNetworkGbCents" : 0.0,
      "costPerWrittenGbCents" : 0.1,
      "costPerReadGbCents" : 0.1
    },
    "metrics" : {
      "writeRequestsTotalCount" : 0,
      "readRequestsTotalCount" : 0,
      "liveDataSizeBytes" : 0,
      "errorsTotalCount" : 0
    },
    "availableActions" : [ "suspend", "removeKeyspace", "getVectorAgentConfig", "removeServerlessMigrationProxy", "getCreds", "migrateServerlessTenant", "addKeyspace", "updateVectorAgent", "hibernate", "cloneDatabaseFromSnapshot", "terminateDatacenter", "createServerlessMigrationProxy", "addDatacenters", "terminate" ],
    "studioUrl" : null,
    "grafanaUrl" : "https://01c0c118-ebce-4a99-a619-369a4cf5d8ff-us-east1.dashboard.astra.datastax.com/d/cloud/dse-cluster-condensed?refresh=30s&orgId=1&kiosk=tv",
    "cqlshUrl" : "https://01c0c118-ebce-4a99-a619-369a4cf5d8ff-us-east1.apps.astra.datastax.com/cqlsh",
    "graphqlUrl" : "https://01c0c118-ebce-4a99-a619-369a4cf5d8ff-us-east1.apps.astra.datastax.com/api/graphql",
    "dataEndpointUrl" : "https://01c0c118-ebce-4a99-a619-369a4cf5d8ff-us-east1.apps.astra.datastax.com/api/rest"
  }
}
----
====

[NOTE]
====
The `json` output returns more information about the database than the default and `csv` options.
====

=== `db get` options

Use the `--key` option to get information about a specific property of the database:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME** --key **PROPERTY**
----

Replace **`PROPERTY`** with one of the supported properties: `id`, `status`, `cloud`, `keyspace`, `keyspaces`, `region`, or `regions`.

For example, to get the database ID:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME** --key id
----

The `--key` option returns the value of the specified property in a raw format.
It is intended for use in scripts.

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
c310bdb0-93dd-4c61-aafb-dae981bb7691
----
====

== Delete a database

Use `astra db delete` to delete an {astra_db} Serverless database:

[source,bash,subs="+quotes"]
----
astra db delete **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console,subs="+quotes"]
----
[INFO]  Deleting Database '**DATABASE_NAME**'
[OK]    Database **DATABASE_NAME** has been deleted
----
====

[TIP]
====
By default, `astra db delete` runs synchronously and doesn't return the command prompt until the database reaches `TERMINATED` or `ERROR` status.
To run the command _asynchronously_, use the `--async` option:

[source,bash,subs="+quotes"]
----
astra db delete **DATABASE_NAME** --async
----

The {product} returns the command prompt before the database finishes deleting.
Use `astra db list` to monitor the status of the database.
====

== List regions

For database creation or regions management, the region name is expected.

With {product}, you can list every available regions per service.

[TIP]
====
For help on this command, use:

[source,bash]
----
astra help db list-regions-serverless
----

Or:

[source,bash]
----
astra help db list-regions-classic
----
====

=== List Serverless regions

In this example, `aws` is the cloud provider.


[source,bash]
----
astra db list-regions-serverless -c aws
----

.Result
[%collapsible]
====
[source,csv]
----
 +----------------+---------------------+-------------------------------+
 | Cloud Provider | Region              | Full Name                     |
 +----------------+---------------------+-------------------------------+
 | aws            | ap-east-1           | Asia Pacific (Hong Kong)      |
 | aws            | ap-south-1          | Asia Pacific (Mumbai)         |
 | aws            | ap-southeast-1      | Asia Pacific (Singapore)      |
 | aws            | ap-southeast-2      | Asia Pacific (Sydney)         |
 | aws            | eu-central-1        | Europe (Frankfurt)            |
 | aws            | eu-west-1           | Europe (Ireland)              |
 | aws            | sa-east-1           | South America (Sao Paulo)     |
 | aws            | us-east-1           | US East (N. Virginia)         |
 | aws            | us-east-2           | US East (Ohio)                |
 | aws            | us-west-2           | US West (Oregon)              |
 +----------------+---------------------+-------------------------------+
----
====

Command parameters:

* `-c` or `--cloud` allows you to select the cloud provider - accepted values are `aws`, `gcp` and `azure`
* `-f` or `--filter` allows you to look for either a location of region, such as `-f France` or `-f us`
* `-o` or `--output` can change output from the default table output to `csv` or `json`
* `-v` for verbose mode
* `-t` to provide token of organization if not default selected

[NOTE]
====
Supported regions are subject to change and may be different from the sample output shown above.
====

=== List Classic regions


[source,bash]
----
astra db list-regions-classic
----

.Result
[%collapsible]
====
[source,csv]
----
 +----------------+---------------------+-------------------------------+
 | Cloud Provider | Region              | Full Name                     |
 +----------------+---------------------+-------------------------------+
 | aws            | ap-south-1          | Asia Pacific (Mumbai)         |
 | aws            | ap-southeast-1      | Asia Pacific (Singapore)      |
 | aws            | ap-southeast-2      | Asia Pacific (Sydney)         |
 | aws            | ap-northeast-1      | Asia Pacific (Tokyo)          |
 | aws            | eu-central-1        | Europe (Frankfurt)            |
 | aws            | eu-west-1           | Europe (Ireland)              |
 | aws            | eu-west-2           | Europe (London)               |
 | aws            | ca-central-1        | Canada (Montréal)             |
 | aws            | us-east-1           | US East (N. Virginia)         |
 | aws            | us-east-2           | US East (Ohio)                |
 | aws            | us-west-2           | US West (Oregon)              |
 +----------------+---------------------+-------------------------------+
----
====

[NOTE]
====
Supported regions are subject to change and may be different from the sample output shown above.
====


== Manage users and roles

For your {astra_db} organization, you can use {product} commands to:

* <<List users>>
* <<Invite a new user>>
* <<Delete a user>>
* <<List roles>>
* <<Get specific role information>>

=== List users


[source,bash]
----
astra user list
----

.Result
[%collapsible]
====
[source,csv]
----
 +--------------------------------------+-----------------------------+---------------------+
 | User Id                              | User Email                  | Status              |
 +--------------------------------------+-----------------------------+---------------------+
 | b665658a-ae6a-4f30-a740-999999999999 | mr.wonderful@mycompany.com  | active              |
 +--------------------------------------+-----------------------------+---------------------+
----
====


=== Invite a new user


[source,bash]
----
astra user invite mydevfriend99a9@gmail.com
----

.Result
[%collapsible]
====
[source,csv]
----
 +--------------------------------------+-----------------------------+---------------------+
 | User Id                              | User Email                  | Status              |
 +--------------------------------------+-----------------------------+---------------------+
 | 825bd3d3-82ae-404b-9aad-999999999999 | mydevfriend99a9@gmail.com   | invited             |
 | b665658a-ae6a-4f30-a740-999999999999 | mr.wonderful@mycompany.com  | active              |
 +--------------------------------------+-----------------------------+---------------------+
----
====


=== Delete a user

[source,bash]
----
astra user delete mydevfriend99a9@gmail.com
----

=== List roles

[source,bash]
----
astra role list
----

=== Get specific role information

[source,bash]
----
astra role get "Database Administrator"
----





== Manage keyspaces

A keyspace is created when you create the database. A keyspace is essentially a handle that you can use to identify database resources such as its tables and indexes.

By default, {product} provides values for the keyspace and database names. Optionally, you can define a custom keyspace name by using the flag `-k`.

[TIP]
====
For help on this command, use:

[source,bash]
----
astra help db create-keyspaces

or:

astra help db list-keyspaces
----
====


=== Create a new keyspace

To add a keyspace named `ks2` to an existing database named `demo`, use the following command.
The option `--if-not-exist` is optional but could help you provide idempotent scripts.
Example:

[source,bash]
----
astra db create-keyspace demo -k ks2 --if-not-exist
----

If the database is not found, {astra_db} returns a warning message and a dedicated code.
To see your new keyspace, you can display your database details.

[source,bash]
----
astra db list-keyspaces demo
----


== Use cqlsh

https://cassandra.apache.org/doc/latest/cassandra/tools/cqlsh.html[cqlsh^] is a standalone shell to work with Apache Cassandra&reg;.
It is compliant with {product} but requires a few extra steps of configuration.
The purpose of {product} is to integrate with `cqlsh` and to perform the integration for you.

{product} will *download*, *install*, *setup* and *wrap* `cqlsh` for you to interact with {astra_db}.

=== Interactive mode

If no options are provided, by default you'll enter `cqlsh` interactive mode.
Example:


[source,bash]
----
astra db cqlsh demo
----

.Result
[%collapsible]
====
[source,csv]
----
 Cqlsh is starting please wait for connection establishment...
 Connected to cndb at 127.0.0.1:9042.
 [cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
 Use HELP for help.
 token@cqlsh>

----
====


=== Execute CQL

To execute a CQL statement with `cqlsh` use the flag `-e`.
Example:

[source,bash]
----
astra db cqlsh demo -e "describe keyspaces;"
----

=== Execute CQL files

To execute CQL files with `cqlsh` use the flag `-f`.
You could also use the CQL syntax SOURCE.
Example:

[source,bash]
----
astra db cqlsh demo -f sample.cql
----


== Use DSBulk with Astra CLI

https://github.com/datastax/dsbulk[DataStax Bulk Loader^] (`dsbulk`) allows you to you load, unload, and count data from Cassandra-based database tables, such as those in Apache Cassandra, DataStax Enterprise, and Astra DB. {product} commands can invoke dsbulk.

As for `cqlsh`, {product} will *download*, *install*, *setup* and *wrap* the `dsbulk` command for you.
All options are available.

=== Set up the demo

To give you an idea, let's walk through a simple example, where we have a database named `demo` with a keyspace named `demo`. If you haven't already, here is the preliminary step:

[source,bash]
----
astra db create demo
----

Let's look at a dataset of cities around the world. We'll use this CSV file from the Awesome Astra site:

https://raw.githubusercontent.com/awesome-astra/docs/main/docs/assets/cities.csv[cities.csv, window="_blank"]

For example, here are the first lines of the CSV:

[source,csv]
----
id,name,state_id,state_code,state_name,country_id,country_code,country_name,latitude,longitude,wikiDataId 52,Ashkāsham,3901,BDS,Badakhshan,1,AF,Afghanistan,36.68333000,71.53333000,Q4805192 68,Fayzabad,3901,BDS,Badakhshan,1,AF,Afghanistan,37.11664000,70.58002000,Q156558
----

Let's create a table to store those values.

Connect to CQLSH with this {product} command:

[source,bash]
----
astra db cqlsh demo -k demo
----

Create the table in cqlsh:

[source,cql]
----
CREATE TABLE cities_by_country ( country_name text, name text, id int, state_id text, state_code text, state_name text, country_id text, country_code text, latitude double, longitude double, wikiDataId text, PRIMARY KEY ((country_name), name) );

describe table cities_by_country;

quit
----


=== Load data

{product} will get cities.csv sample data from https://raw.githubusercontent.com/awesome-astra/docs/main/docs/assets/cities.csv[this file^].

[TIP]
====
The first time you run the `astra db load` command, the message -- `DSBulk is starting please wait` -- may take a few seconds to appear because {product} is downloading `dsbulk` (if it wasn't downloaded previously).
====

Example:


[source,bash]
----
astra db load demo \
 -url https://raw.githubusercontent.com/awesome-astra/docs/main/docs/assets/cities.csv \
 -k demo \
 -t cities_by_country \
 --schema.allowMissingFields true
----

.Result
[%collapsible]
====
[source,csv]
----
 DSBulk is starting please wait ...
 Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
 A cloud secure connect bundle was provided: ignoring all explicit contact points.
 A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
 Operation directory: /Users/awesome.user/Downloads/logs/LOAD_20220823-182343-074618
 Setting executor.maxPerSecond not set when connecting to DataStax Astra: applying a limit of 9,000 ops/second based on the number of coordinators (3).
 If your Astra database has higher limits, please define executor.maxPerSecond explicitly.
   total | failed | rows/s |  p50ms |  p99ms | p999ms | batches
 148,266 |      0 |  8,361 | 663.86 | 767.56 | 817.89 |   30.91
 Operation LOAD_20221123-182343-074618 completed successfully in 17 seconds.
 Last processed positions can be found in positions.txt
----
====


=== Count table row data

Check than the data has been imported with cqlsh.
Example:


[source,bash]
----
astra db cqlsh demo -e "select * from demo.cities_by_country LIMIT 20;"
----

.Result
[%collapsible]
====
[source,csv]
----
Cqlsh is starting please wait for connection establishment...

country_name | name                | country_code | country_id | id   | latitude | longitude | state_code | state_id | state_name          | wikidataid
--------------+---------------------+--------------+------------+------+----------+-----------+------------+----------+---------------------+------------
  Bangladesh |             Azimpur |           BD |         19 | 8454 |  23.7298 |   90.3854 |         13 |      771 |      Dhaka District |       null
  Bangladesh |           Badarganj |           BD |         19 | 8455 | 25.67419 |  89.05377 |         55 |      759 |    Rangpur District |       null
  Bangladesh |            Bagerhat |           BD |         19 | 8456 |     22.4 |     89.75 |         27 |      811 |     Khulna District |       null
  Bangladesh |           Bandarban |           BD |         19 | 8457 |       22 |  92.33333 |          B |      803 | Chittagong Division |       null
  Bangladesh |          Baniachang |           BD |         19 | 8458 | 24.51863 |  91.35787 |         60 |      767 |     Sylhet District |       null
  Bangladesh |             Barguna |           BD |         19 | 8459 | 22.13333 |  90.13333 |         06 |      818 |    Barisal District |       null
  Bangladesh |             Barisal |           BD |         19 | 8460 |     22.8 |      90.5 |         06 |      818 |    Barisal District |       null
  Bangladesh |                Bera |           BD |         19 | 8462 | 24.07821 |  89.63262 |         54 |      813 |   Rajshahi District |       null
  Bangladesh |       Bhairab Bāzār |           BD |         19 | 8463 |  24.0524 |   90.9764 |         13 |      771 |      Dhaka District |       null
  Bangladesh |           Bherāmāra |           BD |         19 | 8464 | 24.02452 |  88.99234 |         27 |      811 |     Khulna District |       null
  Bangladesh |               Bhola |           BD |         19 | 8465 | 22.36667 |  90.81667 |         06 |      818 |    Barisal District |       null
  Bangladesh |           Bhāndāria |           BD |         19 | 8466 | 22.48898 |  90.06273 |         06 |      818 |    Barisal District |       null
  Bangladesh | Bhātpāra Abhaynagar |           BD |         19 | 8467 | 23.01472 |  89.43936 |         27 |      811 |     Khulna District |       null
  Bangladesh |           Bibir Hat |           BD |         19 | 8468 | 22.68347 |  91.79058 |          B |      803 | Chittagong Division |       null
  Bangladesh |               Bogra |           BD |         19 | 8469 | 24.78333 |     89.35 |         54 |      813 |   Rajshahi District |       null
  Bangladesh |        Brahmanbaria |           BD |         19 | 8470 | 23.98333 |  91.16667 |          B |      803 | Chittagong Division |       null
  Bangladesh |         Burhānuddin |           BD |         19 | 8471 | 22.49518 |  90.72391 |         06 |      818 |    Barisal District |       null
  Bangladesh |            Bājitpur |           BD |         19 | 8472 | 24.21623 |  90.95002 |         13 |      771 |      Dhaka District |       null
  Bangladesh |            Chandpur |           BD |         19 | 8474 |    23.25 |  90.83333 |          B |      803 | Chittagong Division |       null
  Bangladesh |    Chapai Nababganj |           BD |         19 | 8475 | 24.68333 |     88.25 |         54 |      813 |   Rajshahi District |       null
----
====


This next example shows how to count the loaded data:


[source,bash]
----
astra db count demo -k demo -t cities_by_country
----

.Result
[%collapsible]
====
[source,csv]
----
 DSBulk is starting please wait ...
 [INFO ] - RUNNING: /Users/awesome.user/.astra/dsbulk-1.9.1/bin/dsbulk count -k demo -t cities_by_country -u token -p AstraCS:gdZaqzmFZsza999999999999:edd25600df1c01506f5388340f138f277cece2c93cb70f999999999999 -b /Users/awesome.user/.astra/scb/scb_071d7059-d55b-4cdb-90c6-999999999999_us-east-1.zip
 Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
 A cloud secure connect bundle was provided: ignoring all explicit contact points.
 Operation directory: /Users/awesome.user/Downloads/logs/COUNT_20221123-182833-197954
   total | failed | rows/s |  p50ms |  p99ms | p999ms
 134,574 |      0 | 43,307 | 315.71 | 457.18 | 457.18
----
====


=== Unload data

You can also unload data.
Example:


[source,bash]
----
astra db unload demo -k demo -t cities_by_country -url /tmp/unload
----

.Result
[%collapsible]
====
[source,csv]
----
 DSBulk is starting please wait ...
 Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
 A cloud secure connect bundle was provided: ignoring all explicit contact points.
 Operation directory: /Users/awesome.user/Downloads/logs/UNLOAD_20221123-183054-208353
   total | failed | rows/s |  p50ms |    p99ms |   p999ms
 134,574 |      0 | 14,103 | 927.51 | 1,853.88 | 1,853.88
 Operation UNLOAD_20221123-183054-208353 completed successfully in 9 seconds.
----
====


== Download Secure Connect Bundle

=== Default values

Use the `astra db download-scb` command to download the different secure connect bundles (one per region) with the pattern `+scb_${dbid}-${dbregion}.zip+` in the current folder.

[source,bash]
----
mkdir db-demo
cd db-demo
astra db download-scb demo
ls
----

=== Download to a specific target folder

Use the `astra db download-scb` command with the `-d` (`--output-directory`) option to download the different secure connect bundles (one per region) with the pattern `+scb_${dbid}-${dbregion}.zip+`. Example of downloading to a `/tmp` folder:

[source,bash]
----
astra db download-scb demo -d /tmp
----

=== Download an SCB and provide output zip filename

Provide the target filename with `-f` (`--output-file`). This command flag works only if you have a **single region** for your database (or you will have to use the flag `-d`).

[source,bash]
----
astra db download-scb demo -f /tmp/demo.zip
----


== Create environment variables

When working with Astra DB, it's handy to generate a set of relevant environment variables such as database name, database region, API call URLs, and so on.

This {product} command creates an `.env` file based on your environment.
Example:


[source,bash]
----
astra db create-dotenv -f /tmp/.env
----

.Result
[%collapsible]
====
[source,bash]
----
 ASTRA_DB_APPLICATION_TOKEN="AstraCS:QeUmROP..."
 ASTRA_DB_GRAPHQL_URL="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/graphql/order_management_data"
 ASTRA_DB_GRAPHQL_URL_ADMIN="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/graphql-admin"
 ASTRA_DB_GRAPHQL_URL_PLAYGROUND="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/playground"
 ASTRA_DB_GRAPHQL_URL_SCHEMA="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/graphql-schema"
 ASTRA_DB_ID="a6b5cb4c-3267-4414-8bba-999999999999"
 ASTRA_DB_KEYSPACE="order_management_data"
 ASTRA_DB_REGION="us-east-1"
 ASTRA_DB_REST_URL="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/rest"
 ASTRA_DB_REST_URL_SWAGGER="https://a6b5cb4c-3267-4414-8bba-999999999999-us-east-1.apps.astra.datastax.com/api/rest/swagger-ui/"
 ASTRA_DB_SECURE_BUNDLE_PATH="/Users/awesome.user/.astra/scb/scb_a6b5cb4c-3267-4414-8bba-999999999999-east-1.zip"
 ASTRA_DB_SECURE_BUNDLE_URL="https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/a6b5cb4c-3267-4414-8bba-999999999999....X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AI....."
 ASTRA_ORG_ID="f9460f14-9879-...."
 ASTRA_ORG_NAME="awe..."
 ASTRA_ORG_TOKEN="AstraCS:QeUmROPLeNbd..."
----
====




== Create and manage configurations

If you work with multiple {astra_db} organizations, it can be useful to switch from one configuration to another, and from one auth token to another.

{product} provides a configuration management solution to handle these use cases.

=== List available configurations

[source,bash]
----
astra config list
----

=== Create a new section

Here we'll name a configuration `dev` and identify the auth token of a separate organization:

[source,bash]
----
astra config create dev --token <token_of_org_2>
----

=== Use your section configuration

You can use an organization configuration anytime by qualifying the `astra` command with the `--config <config_name>` option.
Example:

[source,bash]
----
astra user list --config dev
----

=== Select a section as the default

Change the current organization:

[source,bash]
----
astra config use dev
----

See your new list:

[source,bash]
----
astra config list
----

=== Delete a section

You can delete any organization.
If you delete the selected organization, you will have to pick a new one.

Delete your config:

[source,bash]
----
astra config delete dev
----

See the new list:

[source,bash]
----
astra config list
----


== What's next?

See the CLI commands that you can use to manage your {company} {astra_stream} xref:astra-streaming-cli.adoc[operations].
