= Manage {astra_db} with the {product}
:navtitle: Manage {astra_db}

Use the {product} to manage your {astra_db} databases.

== Create a database

Use the `astra db create` command to create a new {db-serverless} database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'my_serverless_db' does not exist. Creating database 'my_serverless_db' with keyspace 'default_keyspace'
get CLoud provider
[INFO]  Database 'my_serverless_db' and keyspace 'default_keyspace' are being created.
[INFO]  Database 'my_serverless_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 474743 millis)
[OK]    Database 'my_serverless_db' is ready.
----
====

Use the `--vector` option to create a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** --vector
----

.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'my_vector_db' does not exist. Creating database 'my_vector_db' with keyspace 'default_keyspace'
get CLoud provider
[INFO]  Enabling vector search for database my_vector_db
[INFO]  Database 'my_vector_db' and keyspace 'default_keyspace' are being created.
[INFO]  Database 'my_vector_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_vector_db' has status 'ACTIVE' (took 142496 millis)
[OK]    Database 'my_vector_db' is ready.
----
====

[NOTE]
====
You cannot create {db-classic} databases with the {product}.
However, you can use the {product} to <<get-database-details,get information>> about existing {db-classic} databases.
====

Running `astra db create` without any options deploys the database in an available *Free* region and uses `default_keyspace` as the name for the default keyspace.

If the database already exists but is currently xref:astra-db-serverless:databases:database-statuses.adoc[hibernated], the `astra db create` command <<resume-database,resumes>> the database.

include::ROOT:partial$async-option.adoc[]

=== `db create` options

[source,console]
----
NAME
        astra db create - Create a database with cli

SYNOPSIS
        astra db create [ --async ] [ {-c | --cloud} <cloud> ]
                [ --capacity-units <CAPACITY UNITS> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {--if-not-exist | --if-not-exists} ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --tier <TIER> ] [ --timeout <timeout> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ] [--]
                <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -c <cloud>, --cloud <cloud>
            Cloud Provider to create a db

        --capacity-units <CAPACITY UNITS>
            Capacity units to create the database with (default 1)

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist, --if-not-exists
            will create a new DB only if none with same name

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Default keyspace created with the Db

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region to provision

        --tier <TIER>
            Tier to create the database in

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 300s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

Use the `-c`, `-r`, and `-k` options to define the cloud provider, region, and keyspace name when creating a database:

[source,bash,subs="+quotes"]
----
astra db create **DATABASE_NAME** \
    -c **CLOUD_PROVIDER** \
    -r **REGION** \
    -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'my_serverless_db' does not exist. Creating database 'my_serverless_db' with keyspace 'my_keyspace'
get CLoud provider
[INFO]  Database 'my_serverless_db' and keyspace 'my_keyspace' are being created.
[INFO]  Database 'my_serverless_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 112684 millis)
[OK]    Database 'my_serverless_db' is ready.
----
====

//TODO: Confirm that this no longer applies.
////
The database ID, not the database name, ensures uniqueness within your {astra_db} organization.
Consequently, if you issue the `astra db create` command multiple times, you will create multiple database instances.
To ensure that you don't create a database with the same name as another existing database, use the `--if-not-exist` option:

[source,bash]
----
astra db create demo -r us-east-1 -k keyspace1 --if-not-exist
----
////

[#get-database-details]
== Get database details

Use the `astra db list` command to get a list of all the databases in your organization:

[source,bash]
----
astra db list
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| Name                | id                                   | Regions   | Cloud | V | Status    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| my_serverless_db    | 3f2e8f8d-f24d-4dc9-b740-d57e643c7143 | us-east1  | gcp   |   | ACTIVE    |
| my_vector_db        | ebae8d5a-4848-44c9-8485-87e413b60549 | us-east1  | gcp   | ■ | ACTIVE    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
----
====

Use the `astra db get` or `astra db describe` command to get information about a specific database:

[source,bash,subs="+quotes"]
----
astra db get **DATABASE_NAME**
----

[source,bash,subs="+quotes"]
----
astra db describe **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+------------------+-----------------------------------------+
| Attribute        | Value                                   |
+------------------+-----------------------------------------+
| Name             | my_serverless_db                        |
| id               | 3f2e8f8d-f24d-4dc9-b740-d57e643c7143    |
| Cloud            | GCP                                     |
| Regions          | us-east1                                |
| Status           | ACTIVE                                  |
| Vector           | Disabled                                |
| Default Keyspace | default_keyspace                        |
| Creation Time    | 2025-01-06T21:45:08Z                    |
|                  |                                         |
| Keyspaces        | [0] default_keyspace                    |
|                  |                                         |
|                  |                                         |
| Regions          | [0] us-east1                            |
|                  |                                         |
+------------------+-----------------------------------------+
----
====

Use the `astra db status` command to get the status of a specific database:

[source,bash,subs="+quotes"]
----
astra db status **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    Database 'my_serverless_db' has status 'ACTIVE'
----
====

=== `db list` options

[source,console]
----
NAME
        astra db list - Display the list of Databases in an organization

SYNOPSIS
        astra db list [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --vector ]

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --vector
            Create a database with vector search enabled
----

Use the `--vector` option to list only {db-serverless-vector} databases:

[source,bash]
----
astra db list --vector
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| Name                | id                                   | Regions   | Cloud | V | Status    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
| my_vector_db        | ebae8d5a-4848-44c9-8485-87e413b60549 | us-east1  | gcp   | ■ | ACTIVE    |
+---------------------+--------------------------------------+-----------+-------+---+-----------+
----
====

=== `db get` options

[source,console]
----
NAME
        astra db get - Show details of a database

SYNOPSIS
        astra db get [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --key} <Key> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <Key>, --key <Key>
            Show value for a property among: 'id', 'status', 'cloud',
            'keyspace', 'keyspaces', 'region', 'regions'

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db describe` options

[source,console]
----
NAME
        astra db describe - Show details of a database

SYNOPSIS
        astra db describe [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --key} <Key> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <Key>, --key <Key>
            Show value for a property among: 'id', 'status', 'cloud',
            'keyspace', 'keyspaces', 'region', 'regions'

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifie
----

=== `db status` options

[source,console]
----
NAME
        astra db status - Show status of a database

SYNOPSIS
        astra db status [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

== Manage multi-region databases

You can configure a database to replicate data across multiple regions.
Some benefits of multi-region databases include better data locality and higher availability for multi-region application architectures.
For more information, see xref:astra-db-serverless:databases:manage-regions.adoc[].

[IMPORTANT]
====
Multi-region databases are a premium feature.
Each region added to a database increases the database's costs.
This includes a one-time data replication fee for the new region, and charges for replicating data to all database regions.
For more information, see xref:astra-db-serverless:administration:subscription-plans.adoc[].
====

Use the `astra db create-region` command to add a region to a database:

[source,bash,subs="+quotes"]
----
astra db create-region **DATABASE_NAME** -r **REGION**
----

Replace `**REGION**` with the region you want to add to your database.
The following restrictions apply:

* You can add only one region at a time.

* You can't select a region that the database already uses.

* You must select a region in the same cloud provider as the database's other regions.
Multi-region databases can't span multiple cloud providers.

* For {db-serverless-vector} databases, you must select a region that supports that database type.
For more information, see xref:astra-db-serverless:databases:regions.adoc[].

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] UNAVAILABLE: Database 'my_serverless_db' has been found but operation cannot be processed due to invalid state (ACTIVE) expected (ACTIVE)
.Result
[%collapsible]
====
[source,console]
----

----
====
////

[NOTE]
====
The database enters *Maintenance* status while provisioning and replicating data to the new region.

While in *Maintenance* status, you can't add or remove regions, truncate tables, or delete keyspaces, tables, or collections.

*Maintenance* status doesn't impact reads and writes.
====

Use the `astra db list-regions` command to list the regions where a database is deployed:

[source,bash,subs="+quotes"]
----
astra db list-regions **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+----------------+---------------------+----------------+----------------+
| Cloud Provider | Region              | Tier           | Status         |
+----------------+---------------------+----------------+----------------+
| gcp            | us-east1 (default)  | serverless     |                |
| gcp            | us-west1            | serverless     |                |
+----------------+---------------------+----------------+----------------+
----
====

Use the `astra db delete-region` command to remove a region from a database:

[source,bash,subs="+quotes"]
----
astra db delete-region **DATABASE_NAME** -r **REGION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Region 'us-west1' is deleting.
[OK]    Region us-west1 has been deleted
----
====

[NOTE]
====
The database enters *Maintenance* status while deleting the region.

While in *Maintenance* status, you can't add or remove regions, truncate tables, or delete keyspaces, tables, or collections.

*Maintenance* status doesn't impact reads and writes.
====

[IMPORTANT]
====
You can't remove the primary (default) region, which is the first region selected when you created the database.

When you remove a region, any connections to the deleted region are also removed.
However, to avoid data loss, all data is replicated before the region is deleted.
====

=== `db create-region` options

[source,console]
----
NAME
        astra db create-region - Expand database to a new region

SYNOPSIS
        astra db create-region [ --async ] [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-not-exist ] [ --no-color ] [ {-o | --output} <FORMAT> ]
                {-r | --region} <REGION> [ {-t | --tier} <CLOUD> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will wait until the database become ACTIVE

        -c <CLOUD>, --cloud <CLOUD>
            Name of the cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist
            will create a new DB only if none with same name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <REGION>, --region <REGION>
            Name of the region to create

        -t <CLOUD>, --tier <CLOUD>
            Name of the tiers

        --timeout <timeout>
            Max wait time in seconds, default+1800, 0 = no timeout.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db list-regions` options

[source,console]
----
NAME
        astra db list-regions - List regions for a database

SYNOPSIS
        astra db list-regions [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db delete-region` options

[source,console]
----
NAME
        astra db delete-region - Delete a region from a database

SYNOPSIS
        astra db delete-region [ --async ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                {-r | --region} <REGION> [ --timeout <timeout> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --wait ] [--]
                <DB>

OPTIONS
        --async
            Will wait until the database become ACTIVE

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <REGION>, --region <REGION>
            Name of the region to create

        --timeout <timeout>
            Max wait time in seconds, default+1800, 0 = no timeout.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

== Get database API endpoints

Use the `get-endpoint-swagger` command to get the Swagger UI endpoint for a database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-swagger **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
https://3f2e8f8d-f24d-4dc9-b740-d57e643c7143-us-east1.apps.astra.datastax.com/api/rest/swagger-ui/
----
====

Use the `get-endpoint-api` command to get the JSON API endpoint for a {db-serverless-vector} database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-api **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
https://ebae8d5a-4848-44c9-8485-87e413b60549-us-east1.apps.astra.datastax.com/api/json
----
====

Use the `get-endpoint-playground` command to get the GraphQL playground endpoint for a non-vector database:

[source,bash,subs="+quotes"]
----
astra db get-endpoint-playground **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
https://3f2e8f8d-f24d-4dc9-b740-d57e643c7143-us-east1.apps.astra.datastax.com/api/playground
----
====

=== `db get-endpoint-swagger` options

[source,console]
----
NAME
        astra db get-endpoint-swagger - Open the swagger user interface

SYNOPSIS
        astra db get-endpoint-swagger [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db get-endpoint-api` options

[source,console]
----
NAME
        astra db get-endpoint-api - Open the json api endpoint

SYNOPSIS
        astra db get-endpoint-api [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db get-endpoint-playground` options

[source,console]
----
NAME
        astra db get-endpoint-playground - Expand database to a new region

SYNOPSIS
        astra db get-endpoint-playground
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ {-r | --region} <DB_REGION> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

[#resume-database]
== Resume a hibernated database

Use the `astra db resume` command to resume a xref:astra-db-serverless:databases:database-statuses.adoc[hibernated] database:

[source,bash,subs="+quotes"]
----
astra db resume **DATABASE_NAME**
----

Resuming the database may take a few minutes.

include::ROOT:partial$async-option.adoc[]

=== `db resume` options

[source,console]
----
NAME
        astra db resume - Resume a db if needed

SYNOPSIS
        astra db resume [ --async ] [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 180s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

== Terminate a database

[WARNING]
====
Terminating a database permanently deletes all of its data, including xref:astra-db-serverless:databases:backup-restore.adoc[automatic backups].
You can't undo this action.
====

Use the `astra db delete` command to terminate a database:

[source,bash,subs="+quotes"]
----
astra db delete **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Deleting Database 'my_serverless_db'
[OK]    Database my_serverless_db has been deleted
----
====

The database enters *Terminating* status while deletion occurs.

By default, the command runs synchronously and doesn't return the command prompt until the database reaches *Terminated* or *Error* status.
To run the command _asynchronously_, add the `--async` option.

=== `db delete` options

[source,console]
----
NAME
        astra db delete - Delete an existing database

SYNOPSIS
        astra db delete [ --async ] [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --timeout <timeout> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        --async
            Will not wait for the resource to become available

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --timeout <timeout>
            Provide a limit to the wait period in seconds, default is 500s.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

== Manage keyspaces

Use the `astra db create-keyspace` command to create a new keyspace in a database:

[source,bash,subs="+quotes"]
----
astra db create-keyspace **DATABASE_NAME** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Keyspace  'keyspace2' is creating.
[INFO]  Database 'my_serverless_db' has status 'MAINTENANCE' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 6882 millis)
[OK]    Database 'my_serverless_db' is ready.
[OK]    Database 'my_serverless_db' is ready.
----
====

The database enters *Maintenance* status while creating the keyspace.
When the database returns to *Active* status, you can use the new keyspace.

include::ROOT:partial$async-option.adoc[]

[TIP]
======
By default, the {product} returns an error if a keyspace with the same name already exists.
However, if you use the `--if-not-exist` option, the {product} automatically connects to the existing keyspace instead of returning an error.
This option can be useful when invoking the {product} in idempotent scripts.

[source,bash,subs="+quotes"]
----
astra db create-keyspace **DATABASE_NAME** -k **KEYSPACE_NAME** --if-not-exist
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Keyspace  'keyspace2' already exists. Connecting to keyspace.
[OK]    Database 'my_serverless_db' is ready.
[OK]    Database 'my_serverless_db' is ready.
----
====
======

Use the `astra db list-keyspaces` command to get a list of the keyspaces in a database:

[source,bash,subs="+quotes"]
----
astra db list-keyspaces **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+---------------------+
| Name                |
+---------------------+
| keyspace1 (default) |
| keyspace2           |
+---------------------+
----
====

Use the `astra db delete-keyspace` command to delete a keyspace from a database:

[source,bash,subs="+quotes"]
----
astra db delete-keyspace **DATABASE_NAME** -k **KEYSPACE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Database 'my_serverless_db' has status 'MAINTENANCE' waiting to be 'ACTIVE' ...
[INFO]  Database 'my_serverless_db' has status 'ACTIVE' (took 6917 millis)
[OK]    Database 'my_serverless_db' is ready.
----
====

[WARNING]
====
Deleting a keyspace permanently deletes all collections, tables, and data in the keyspace.
====

The database enters *Maintenance* status while it deletes the keyspace along with any collections, tables, and data within the keyspace.

include::ROOT:partial$async-option.adoc[]

If you delete the default keyspace, {astra_db} automatically selects another keyspace to be the default keyspace.

=== `db create-keyspace` options

[source,console]
----
NAME
        astra db create-keyspace - Create a new keyspace

SYNOPSIS
        astra db create-keyspace [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --if-not-exist ] {-k | --keyspace} <KEYSPACE> [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [ --wait ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --if-not-exist
            will create a new DB only if none with same name

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --wait
            Will wait until the database become ACTIVE

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db list-keyspaces` options

[source,console]
----
NAME
        astra db list-keyspaces - Display the list of Keyspaces in an database

SYNOPSIS
        astra db list-keyspaces [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db delete-keyspace` options

[source,console]
----
NAME
        astra db delete-keyspace - Delete an existing keyspace

SYNOPSIS
        astra db delete-keyspace [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                {-k | --keyspace} <KEYSPACE> [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Name of the keyspace to create

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

== Get a list of available regions

Use the `astra db list-regions-serverless` command to get a list of available cloud provider regions that support {db-serverless} databases:

[source,bash]
----
astra db list-regions-serverless
----

.Result
[%collapsible]
======
[source,console]
----
+-----------------+-------------------------+---------------------------------------+
| Cloud Provider  | Region                  | Full Name                             |
+-----------------+-------------------------+---------------------------------------+
| aws             | ap-east-1               | Asia Pacific (Hong Kong)              |
| aws             | ap-south-1              | Asia Pacific (Mumbai)                 |
| aws             | ap-southeast-1          | Asia Pacific (Singapore)              |
| aws             | ap-southeast-2          | Asia Pacific (Sydney)                 |
| aws             | ca-central-1            | Canada (Central)                      |
| aws             | ca-west-1               | Canada West (Calgary)                 |
| aws             | eu-central-1            | Europe (Frankfurt)                    |
| aws             | eu-west-1               | Europe (Ireland)                      |
| aws             | eu-west-2               | Europe (London)                       |
| aws             | me-central-1            | Middle East (UAE)                     |
| aws             | sa-east-1               | South America (Sao Paulo)             |
| aws             | us-east-1               | US East (N. Virginia)                 |
| aws             | us-east-2               | US East (Ohio)                        |
| aws             | us-west-2               | US West (Oregon)                      |
| azure           | australiaeast           | Australia East                        |
| azure           | brazilsouth             | Brazil South (Sao Paulo)              |
| azure           | canadacentral           | Canada Central (Toronto)              |
| azure           | centralindia            | Central India (Pune)                  |
| azure           | centralus               | (US) Central US                       |
| azure           | eastus                  | US East                               |
| azure           | eastus2                 | US East 2 (Virginia)                  |
| azure           | northeurope             | Northern Europe (Ireland)             |
| azure           | westeurope              | West Europe                           |
| azure           | westus2                 | US West (Washington)                  |
| azure           | westus3                 | US West 3                             |
| gcp             | asia-northeast1         | Asia Northeast1 (Tokyo, Japan)        |
| gcp             | asia-northeast2         | Osaka, Japan, APAC                    |
| gcp             | asia-south1             | Mumbai, India                         |
| gcp             | australia-southeast1    | Sydney, Australia, APAC               |
| gcp             | europe-west1            | St. Ghislain, Belgium                 |
| gcp             | europe-west2            | West Europe2 (London, England, UK)    |
| gcp             | europe-west3            | West Europe3 (Frankfurt, Germany)     |
| gcp             | europe-west4            | West Europe4 (Eemshaven, Netherlands) |
| gcp             | northamerica-northeast1 | Montreal, Quebec                      |
| gcp             | northamerica-northeast2 | Toronto, Ontario                      |
| gcp             | us-central1             | Council Bluffs, Iowa                  |
| gcp (free-tier) | us-east1                | Moncks Corner, South Carolina         |
| gcp             | us-east4                | Ashburn, Virginia                     |
| gcp             | us-west1                | The Dalles, Oregon                    |
| gcp             | us-west4                | US West (Las Vegas, USA)              |
+-----------------+-------------------------+---------------------------------------+
----

include::ROOT:partial$regions-change-admonition.adoc[]
======

Use the `astra db list-regions-vector` command to get a list of available cloud provider regions that support {db-serverless-vector} databases:

[source,bash]
----
astra db list-regions-vector
----

.Result
[%collapsible]
======
[source,console]
----
+-----------------+-------------------------+------------------------------------+
| Cloud Provider  | Region                  | Full Name                          |
+-----------------+-------------------------+------------------------------------+
| aws             | ap-south-1              | Asia Pacific (Mumbai)              |
| aws             | ap-southeast-2          | Asia Pacific (Sydney)              |
| aws             | eu-west-1               | Europe (Ireland)                   |
| aws             | us-east-1               | US East (N. Virginia)              |
| aws             | us-east-2               | US East (Ohio)                     |
| azure           | australiaeast           | Australia East                     |
| azure           | centralindia            | Central India (Pune)               |
| azure           | westeurope              | West Europe                        |
| azure           | westus3                 | US West 3                          |
| gcp             | europe-west2            | West Europe2 (London, England, UK) |
| gcp             | northamerica-northeast1 | Montreal, Quebec                   |
| gcp (free-tier) | us-east1                | Moncks Corner, South Carolina      |
| gcp             | us-east4                | Ashburn, Virginia                  |
+-----------------+-------------------------+------------------------------------+
----

include::ROOT:partial$regions-change-admonition.adoc[]
======

Use the `astra db list-regions-classic` command to get a list of available cloud provider regions that support {db-classic} databases:

[source,bash]
----
astra db list-regions-classic
----

.Result
[%collapsible]
======
[source,console]
----
+-----------------+-------------------------+-------------------------------+
| Cloud Provider  | Region                  | Full Name                     |
+-----------------+-------------------------+-------------------------------+
| aws             | af-south-1              | Africa (Cape Town)            |
| aws             | ap-east-1               | Hong Kong                     |
| aws             | ap-south-1              | Asia Pacific (Mumbai)         |
| aws             | ap-southeast-1          | Asia Pacific (Singapore)      |
| aws             | ap-southeast-2          | Asia Pacific (Sydney)         |
| aws             | ca-central-1            | Canada (Central)              |
| aws             | ca-west-1               | Canada West (Calgary)         |
| aws             | eu-central-1            | Europe (Frankfurt)            |
| aws             | eu-west-1               | EU West 1 (Ireland)           |
| aws             | eu-west-2               | Europe (London)               |
| aws             | me-central-1            | Middle East (UAE)             |
| aws             | sa-east-1               | Sao Paulo                     |
| aws             | us-east-1               | US East (N. Virginia)         |
| aws             | us-east-2               | US East (Ohio)                |
| aws             | us-west-2               | US West (Oregon)              |
| azure           | australiaeast           | Australia East                |
| azure           | brazilsouth             | Brazil South                  |
| azure           | canadacentral           | Canada Central (Toronto)      |
| azure           | centralindia            | Central India                 |
| azure           | centralus               | (US) Central US               |
| azure           | eastus2                 | East US 2 (Virginia)          |
| azure           | northeurope             | North Europe                  |
| azure           | southcentralus          | South Central US              |
| azure           | westeurope              | West Europe                   |
| azure           | westus2                 | West US 2 (Washington)        |
| azure           | westus3                 | West US 3                     |
| gcp             | asia-northeast2         | Osaka, Japan, APAC            |
| gcp             | asia-south1             | Mumbai, India                 |
| gcp             | europe-west1            | St. Ghislain, Belgium         |
| gcp             | northamerica-northeast1 | NA Northeast 1 (Montreal)     |
| gcp             | southamerica-east1      | Osasco, Sao Paulo, Brazil     |
| gcp             | us-central1             | US Central (Iowa)             |
| gcp (free-tier) | us-east1                | US East (South Carolina)      |
| gcp             | us-east4                | US East 4 (Virginia)          |
| gcp             | us-west1                | The Dalles, Oregon            |
+-----------------+-------------------------+-------------------------------+
----

include::ROOT:partial$regions-change-admonition.adoc[]
======

=== `db list-regions-serverless` options

[source,console]
----
NAME
        astra db list-regions-serverless - Show available regions (serverless).

SYNOPSIS
        astra db list-regions-serverless [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----

=== `db list-regions-vector` options

[source,console]
----
NAME
        astra db list-regions-serverless - Show available regions (serverless).

SYNOPSIS
        astra db list-regions-serverless [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----

=== `db list-regions-classic` options

[source,console]
----
NAME
        astra db list-regions-classic - Show available regions (classic).

SYNOPSIS
        astra db list-regions-classic [ {-c | --cloud} <CLOUD> ]
                [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --filter} <filter> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ]

OPTIONS
        -c <CLOUD>, --cloud <CLOUD>
            Filter on Cloud provider

        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <filter>, --filter <filter>
            Filter on names

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console
----

[#cqlsh]
== Use the CQL shell (cqlsh)

The CQL shell (`cqlsh`) is an interface that you can use to issue xref:astra@cql:ROOT:index.adoc[{cass-short} Query Language (CQL)] commands to your {astra_db} database.
The {product} provides built-in CQL shell support by downloading, installing, configuring, and wapping the `cqlsh` utility.
This can act as a convenient alternative to installing and configuring a xref:astra-db-serverless:cql:develop-with-cql.adoc#connect-to-the-cql-shell[standalone CQL shell].

To use `cqlsh` commands, you must have a supported version of Python installed on your system.
The underlying `cqlsh` utility requires Python 2.7 (with TLS support) or Python 3.6--3.11.
Python versions 3.12 and later are not supported.
For more details, see this https://support.datastax.com/s/article/cqlsh-may-fail-with-A-Python-installation-with-SSL-is-required-to-connect-to-a-cloud-cluster-when-connecting-to-Astra[Support article]

Use the `astra db cqlsh` command to start the CQL shell in interactive mode:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Downloading Cqlshell, please wait...
[INFO]  Installing  archive, please wait...
[INFO]  Cqlsh is starting, please wait for connection establishment...
Connected to cndb at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
----
====

Type `exit` and press kbd:[Return] to exit the CQL shell.

The first time you use the `astra db cqlsh` command, the {product} downloads and installs the `cqlsh` utility to the {product} installation directory (`~/.astra/cqlsh-astra`).
The {product} also downloads the {scb-long} for each database you connect to and stores the {scb} zip files in the `~/.astra/scb` directory.

[NOTE]
======
If the {product} reports `ModuleNotFoundError`, check that you have a supported version of Python available in your terminal:

[source,bash]
----
python -V
----

.Result
[%collapsible]
====
[source,console]
----
Python 3.11.10
----
====
======

=== `db cqlsh` options

[source,console]
----
NAME
        astra db cqlsh - Start Cqlsh

SYNOPSIS
        astra db cqlsh [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ --connect-timeout <TIMEOUT> ] [ --debug ]
                [ {-e | --execute} <STATEMENT> ] [ --encoding <ENCODING> ]
                [ --env <Environment> ] [ {-f | --file} <FILE> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ --request-timeout <TIMEOUT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [ --version ]
                [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --connect-timeout <TIMEOUT>
            Connection timeout in seconds (default is 10

        --debug
            Show additional debugging information.

        -e <STATEMENT>, --execute <STATEMENT>
            Execute the statement and quit.

        --encoding <ENCODING>
            Output encoding. Default encoding: utf8.

        --env <Environment>
            Astra Environment to use

        -f <FILE>, --file <FILE>
            Execute commands from a CQL file, then exit.

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Authenticate to the given keyspace.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --request-timeout <TIMEOUT>
            Request timeout in seconds (default is 20

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --version
            Display information of cqlsh.

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

Use the `-e`/`--execute` option to execute a CQL statement:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_NAME** -e "describe keyspaces;"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

system_auth    system_traces       datastax_sla
system_schema  data_endpoint_auth  system_virtual_schema
system         keyspace1           system_views
----
====

Use the `-f`/`--file` option to execute a CQL file:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_NAME** -f sample.cql
----

.Example CQL file
[%collapsible]
====
.sample.cql
[source,cql]
----
-- Use a specific keyspace
USE keyspace1;

-- Create a table
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    name TEXT,
    email TEXT
);

-- Insert some data
INSERT INTO users (id, name, email) VALUES (uuid(), 'Alice', 'alice@example.com');
INSERT INTO users (id, name, email) VALUES (uuid(), 'Bob', 'bob@example.com');

-- Query the data
SELECT * FROM users;
----
====

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 id                                   | email             | name
--------------------------------------+-------------------+-------
 6639b572-fad5-4d0a-b324-bb57d3b88530 |   bob@example.com |   Bob
 c6c38995-0307-429d-935b-37173807c6d9 | alice@example.com | Alice
----
====

[TIP]
======
You can also execute a CQL file using the `xref:astra@cql:reference:cqlsh-commands/source.adoc[]` CQL command:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_NAME** -e "SOURCE 'sample.cql'"
----

.Result
[%collapsible]
====
[source,cql]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 id                                   | email             | name
--------------------------------------+-------------------+-------
 6639b572-fad5-4d0a-b324-bb57d3b88530 |   bob@example.com |   Bob
 c6c38995-0307-429d-935b-37173807c6d9 | alice@example.com | Alice
----
====
======

== Use DataStax Bulk Loader (DSBulk)

The xref:dsbulk:overview:dsbulk-about.adoc[DataStax Bulk Loader] (DSBulk) lets you load, unload, and count data in your {astra_db} database tables.
The {product} provides built-in DSBulk support by downloading, installing, configuring, and wapping the `dsbulk` utility.

The {product} exposes DSBulk functionality through the `astra db load`, `astra db unload`, and `astra db count` commands.

Use the `astra db load` command to load data from a file into a database table:

[source,bash,subs="+quotes"]
----
astra db load **DATABASE_NAME** \
  -k **KEYSPACE_NAME** \
  -t **TABLE_NAME** \
  -url **FILE_LOCATION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Downloading Dsbulk, please wait...
[INFO]  Installing  archive, please wait...
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk load -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_d123ae26-2ba1-4975-87cd-da33a887a0c1_us-east-1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url cities.csv -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
Operation directory: /Users/USERNAME/logs/LOAD_20241120-190553-154417
Setting executor.maxPerSecond not set when connecting to DataStax Astra: applying a limit of 27,000 ops/second based on the number of coordinators (9).
If your Astra database has higher limits, please define executor.maxPerSecond explicitly.
  total | failed | rows/s |  p50ms |  p99ms | p999ms | batches
148,266 |      0 | 19,857 | 237.29 | 738.20 | 872.42 |   31.06
Operation LOAD_20241120-190553-154417 completed successfully in 7 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/LOAD_20241120-190553-154417/checkpoint.csv
----
====

[TIP]
======
You can use the `cqlsh` command to check that the data imported successfully:

[source,bash,subs="+quotes"]
----
astra db cqlsh **DATABASE_NAME** -e \
"SELECT * FROM **KEYSPACE_NAME**.**TABLE_NAME** LIMIT 20;"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 country_name | name                | country_code | country_id | id   | latitude | longitude | state_code | state_id | state_name          | wikidataid
--------------+---------------------+--------------+------------+------+----------+-----------+------------+----------+---------------------+------------
   Bangladesh |             Azimpur |           BD |         19 | 8454 |  23.7298 |   90.3854 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Badarganj |           BD |         19 | 8455 | 25.67419 |  89.05377 |         55 |      759 |    Rangpur District |       null
   Bangladesh |            Bagerhat |           BD |         19 | 8456 |     22.4 |     89.75 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bandarban |           BD |         19 | 8457 |       22 |  92.33333 |          B |      803 | Chittagong Division |       null
   Bangladesh |          Baniachang |           BD |         19 | 8458 | 24.51863 |  91.35787 |         60 |      767 |     Sylhet District |       null
   Bangladesh |             Barguna |           BD |         19 | 8459 | 22.13333 |  90.13333 |         06 |      818 |    Barisal District |       null
   Bangladesh |             Barisal |           BD |         19 | 8460 |     22.8 |      90.5 |         06 |      818 |    Barisal District |       null
   Bangladesh |                Bera |           BD |         19 | 8462 | 24.07821 |  89.63262 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |       Bhairab Bāzār |           BD |         19 | 8463 |  24.0524 |   90.9764 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Bherāmāra |           BD |         19 | 8464 | 24.02452 |  88.99234 |         27 |      811 |     Khulna District |       null
   Bangladesh |               Bhola |           BD |         19 | 8465 | 22.36667 |  90.81667 |         06 |      818 |    Barisal District |       null
   Bangladesh |           Bhāndāria |           BD |         19 | 8466 | 22.48898 |  90.06273 |         06 |      818 |    Barisal District |       null
   Bangladesh | Bhātpāra Abhaynagar |           BD |         19 | 8467 | 23.01472 |  89.43936 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bibir Hat |           BD |         19 | 8468 | 22.68347 |  91.79058 |          B |      803 | Chittagong Division |       null
   Bangladesh |               Bogra |           BD |         19 | 8469 | 24.78333 |     89.35 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |        Brahmanbaria |           BD |         19 | 8470 | 23.98333 |  91.16667 |          B |      803 | Chittagong Division |       null
   Bangladesh |         Burhānuddin |           BD |         19 | 8471 | 22.49518 |  90.72391 |         06 |      818 |    Barisal District |       null
   Bangladesh |            Bājitpur |           BD |         19 | 8472 | 24.21623 |  90.95002 |         13 |      771 |      Dhaka District |       null
   Bangladesh |            Chandpur |           BD |         19 | 8474 |    23.25 |  90.83333 |          B |      803 | Chittagong Division |       null
   Bangladesh |    Chapai Nababganj |           BD |         19 | 8475 | 24.68333 |     88.25 |         54 |      813 |   Rajshahi District |       null

(20 rows)
----
====
======

Use the `astra db unload` command to unload database table rows into a file:

[source,bash,subs="+quotes"]
----
astra db unload **DATABASE_NAME** \
    -k **KEYSPACE_NAME** \
    -t **TABLE_NAME** \
    -url **FILE_LOCATION**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk unload -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_d123ae26-2ba1-4975-87cd-da33a887a0c1_us-east-1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url FILE_LOCATION -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/UNLOAD_20241120-193658-535944
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 33,860 | 284.67 | 587.20 | 587.20
Operation UNLOAD_20241120-193658-535944 completed successfully in 3 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/UNLOAD_20241120-193658-535944/checkpoint.csv
----
====

Use the `astra db count` command to get information about loaded data:

[source,bash,subs="+quotes"]
----
astra db count **DATABASE_NAME** \
    -k **KEYSPACE_NAME** \
    -t **TABLE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk count -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_d123ae26-2ba1-4975-87cd-da33a887a0c1_us-east-1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/COUNT_20241120-192745-378116
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 66,270 | 236.12 | 501.22 | 501.22
Operation COUNT_20241120-192745-378116 completed successfully in 1 second.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/COUNT_20241120-192745-378116/checkpoint.csv
134574
----
====

[NOTE]
====
The first time you use one of the `astra db load`, `astra db unload`, or `astra db count` commands, the {product} downloads and installs the `dsbulk` utility to the {product} installation directory (`~/.astra/dsbulk-*`).
The {product} also downloads the {scb-long} for each database you connect to and stores the {scb} zip files in the `~/.astra/scb` directory.
====

=== `db load` options

[source,console]
----
NAME
        astra db load - Load data leveraging DSBulk

SYNOPSIS
        astra db load [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ -delim <delim> ]
                [ -dryRun ] [ --dsbulk-config <DSBULK_CONF_FILE> ]
                [ -encoding <ENCODING> ] [ --env <Environment> ]
                [ -header <header> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ -logDir <log directory> ]
                [ {-m | --schema.mapping} <mapping> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ]
                [ -maxErrors <maxErrors> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ --schema.allowMissingFields <allowMissingFields> ]
                [ -skipRecords <skipRecords> ] [ {-t | --table} <TABLE> ]
                [ --token <AUTH_TOKEN> ] -url <url> [ {-v | --verbose} ] [--]
                <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -delim <delim>
            Character(s) use as field delimiter.

        -dryRun
            Enable or disable dry-run mode.

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -header <header>
            Read, Write Header in input file

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -m <mapping>, --schema.mapping <mapping>
            Field-to-column mapping to use.

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        -maxErrors <maxErrors>
            Maximum number of errors before aborting the operation.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        --schema.allowMissingFields <allowMissingFields>
            Ease the mapping

        -skipRecords <skipRecords>
            Lines to skip before readind

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -url <url>
            File location to load data

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifie
----

=== `db unload` options

[source,console]
----
NAME
        astra db unload - Unload data leveraging DSBulk

SYNOPSIS
        astra db unload [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ -delim <delim> ]
                [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -encoding <ENCODING> ]
                [ --env <Environment> ] [ -header <header> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ -logDir <log directory> ]
                [ {-m | --schema.mapping} <mapping> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ]
                [ -maxErrors <maxErrors> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ -skipRecords <skipRecords> ] [ {-t | --table} <TABLE> ]
                [ --token <AUTH_TOKEN> ] [ -url <url> ] [ {-v | --verbose} ]
                [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -delim <delim>
            The character(s) to use as field delimiter. Field delimiters
            containing more than one character are accepted.

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -header <header>
            Enable or disable whether the files to read or write begin with a
            header line.

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -m <mapping>, --schema.mapping <mapping>
            The field-to-column mapping to use, that applies to both loading
            and unloading; ignored when counting.

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        -maxErrors <maxErrors>
            The maximum number of errors to tolerate before aborting the entire
            operation.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        -skipRecords <skipRecords>
            The number of records to skip from each input file before the
            parser can begin to execute. Note that if the file contains a
            header line, that line is not counted as a valid record. This
            setting is ignored when writing.

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -url <url>
            The URL or path of the resource(s) to read from or write to.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db count` options

[source,console]
----
NAME
        astra db count - Count items for a table, a query

SYNOPSIS
        astra db count [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ --dsbulk-config <DSBULK_CONF_FILE> ] [ -encoding <ENCODING> ]
                [ --env <Environment> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ -logDir <log directory> ]
                [ -maxConcurrentQueries <maxConcurrentQueries> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ {-query | --schema.query} <QUERY> ]
                [ {-t | --table} <TABLE> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --dsbulk-config <DSBULK_CONF_FILE>
            Not all options offered by the loader DSBulk are exposed in this
            CLI

        -encoding <ENCODING>
            The file name format to use when writing. This setting is ignored
            when reading and for non-file URLs.

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace used for loading or unloading data.

        -logDir <log directory>
            Optional filter

        -maxConcurrentQueries <maxConcurrentQueries>
            The maximum number of concurrent queries that should be carried in
            parallel.

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -query <QUERY>, --schema.query <QUERY>
            Optional to unload or count

        -t <TABLE>, --table <TABLE>
            Table used for loading or unloading data. Table names should not be
            quoted and are case-sensitive.

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== End-to-end example

The following end-to-end example shows how to use the {product}'s built-in DSBulk support to load data into an {astra_db} database, get information about the data, and unload the data into CSV files:

. (Optional) This procedure assumes that you have a database and keyspace both named `demo`:
+
[source,bash]
----
astra db create demo -k demo
----
+
.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'demo' does not exist. Creating database 'demo' with keyspace 'demo'
get CLoud provider
[INFO]  Database 'demo' and keyspace 'demo' are being created.
[INFO]  Database 'demo' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'demo' has status 'ACTIVE' (took 484471 millis)
[OK]    Database 'demo' is ready.
----
====
+
If you choose not to follow this step, make sure to replace `demo` in the subsequent steps with your own database and keyspace names.

. Download the xref:ROOT:attachment$cities.csv[cities.csv] file and move it to the directory where you run {product} commands.
+
The `cities.csv` dataset contains information about cities around the world:
+
.cities.csv
[source,csv]
----
id,name,state_id,state_code,state_name,country_id,country_code,country_name,latitude,longitude,wikiDataId
52,Ashkāsham,3901,BDS,Badakhshan,1,AF,Afghanistan,36.68333000,71.53333000,Q4805192
68,Fayzabad,3901,BDS,Badakhshan,1,AF,Afghanistan,37.11664000,70.58002000,Q156558
...
----

. Create a table in your {astra_db} database to store your data.
+
.. Start the CQL shell in interactive mode:
+
[source,bash]
----
astra db cqlsh demo -k demo
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
Connected to cndb at 127.0.0.1:9042.
[cqlsh 6.8.0 | Cassandra 4.0.0.6816 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
----
====
+
.. Copy and paste the following CQL command into the `cqlsh` prompt and press kbd:[Return]:
+
[source,cql]
----
CREATE TABLE cities_by_country4 (
    country_name text,
    name text,
    id int,
    state_id text,
    state_code text,
    state_name text,
    country_id text,
    country_code text,
    latitude double,
    longitude double,
    wikiDataId text,
    PRIMARY KEY ((country_name), name)
);
----
+
This command creates a table named `cities_by_country` with the appropriate schema for the `cities.csv` dataset.
+
.. Type `exit` and press kbd:[Return] to exit the CQL shell.

. Load the data from the `cities.csv` file into the `cities_by_country` table that you just created in your database:
+
[source,bash]
----
astra db load demo \
  -k demo \
  -t cities_by_country \
  -url cities.csv
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk load -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_us-east1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url cities.csv -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
A cloud secure connect bundle was provided and selected operation performs writes: changing default consistency level to LOCAL_QUORUM.
Operation directory: /Users/USERNAME/logs/LOAD_20241120-205743-166874
Setting executor.maxPerSecond not set when connecting to DataStax Astra: applying a limit of 27,000 ops/second based on the number of coordinators (9).
If your Astra database has higher limits, please define executor.maxPerSecond explicitly.
  total | failed | rows/s |  p50ms |  p99ms |   p999ms | batches
148,266 |      0 | 14,545 | 245.70 | 792.72 | 1,149.24 |   31.03
Operation LOAD_20241120-205743-166874 completed successfully in 7 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/LOAD_20241120-205743-166874/checkpoint.csv
----
====

. Confirm that the data loaded successfully:
+
[source,bash]
----
astra db cqlsh demo -e \
"select * from demo.cities_by_country LIMIT 20;"
----
+
.Result
[%collapsible]
====
[source,console]
----
 country_name | name                | country_code | country_id | id   | latitude | longitude | state_code | state_id | state_name          | wikidataid
--------------+---------------------+--------------+------------+------+----------+-----------+------------+----------+---------------------+------------
   Bangladesh |             Azimpur |           BD |         19 | 8454 |  23.7298 |   90.3854 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Badarganj |           BD |         19 | 8455 | 25.67419 |  89.05377 |         55 |      759 |    Rangpur District |       null
   Bangladesh |            Bagerhat |           BD |         19 | 8456 |     22.4 |     89.75 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bandarban |           BD |         19 | 8457 |       22 |  92.33333 |          B |      803 | Chittagong Division |       null
   Bangladesh |          Baniachang |           BD |         19 | 8458 | 24.51863 |  91.35787 |         60 |      767 |     Sylhet District |       null
   Bangladesh |             Barguna |           BD |         19 | 8459 | 22.13333 |  90.13333 |         06 |      818 |    Barisal District |       null
   Bangladesh |             Barisal |           BD |         19 | 8460 |     22.8 |      90.5 |         06 |      818 |    Barisal District |       null
   Bangladesh |                Bera |           BD |         19 | 8462 | 24.07821 |  89.63262 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |       Bhairab Bāzār |           BD |         19 | 8463 |  24.0524 |   90.9764 |         13 |      771 |      Dhaka District |       null
   Bangladesh |           Bherāmāra |           BD |         19 | 8464 | 24.02452 |  88.99234 |         27 |      811 |     Khulna District |       null
   Bangladesh |               Bhola |           BD |         19 | 8465 | 22.36667 |  90.81667 |         06 |      818 |    Barisal District |       null
   Bangladesh |           Bhāndāria |           BD |         19 | 8466 | 22.48898 |  90.06273 |         06 |      818 |    Barisal District |       null
   Bangladesh | Bhātpāra Abhaynagar |           BD |         19 | 8467 | 23.01472 |  89.43936 |         27 |      811 |     Khulna District |       null
   Bangladesh |           Bibir Hat |           BD |         19 | 8468 | 22.68347 |  91.79058 |          B |      803 | Chittagong Division |       null
   Bangladesh |               Bogra |           BD |         19 | 8469 | 24.78333 |     89.35 |         54 |      813 |   Rajshahi District |       null
   Bangladesh |        Brahmanbaria |           BD |         19 | 8470 | 23.98333 |  91.16667 |          B |      803 | Chittagong Division |       null
   Bangladesh |         Burhānuddin |           BD |         19 | 8471 | 22.49518 |  90.72391 |         06 |      818 |    Barisal District |       null
   Bangladesh |            Bājitpur |           BD |         19 | 8472 | 24.21623 |  90.95002 |         13 |      771 |      Dhaka District |       null
   Bangladesh |            Chandpur |           BD |         19 | 8474 |    23.25 |  90.83333 |          B |      803 | Chittagong Division |       null
   Bangladesh |    Chapai Nababganj |           BD |         19 | 8475 | 24.68333 |     88.25 |         54 |      813 |   Rajshahi District |       null

(20 rows)
----
====

. Count the loaded data:
+
[source,bash]
----
astra db count demo \
    -k demo \
    -t cities_by_country
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk count -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_us-east1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/COUNT_20241120-210748-465576
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 70,713 | 215.20 | 354.42 | 354.42
Operation COUNT_20241120-210748-465576 completed successfully in 1 second.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/COUNT_20241120-210748-465576/checkpoint.csv
134574
----
====

. Unload the data into CSV files:
+
[source,bash]
----
astra db unload demo \
    -k demo \
    -t cities_by_country \
    -url unloaded_data
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  RUNNING: /Users/USERNAME/.astra/dsbulk-1.11.0/bin/dsbulk unload -u token -p AstraCS:FZm... -b /Users/USERNAME/.astra/scb/scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_us-east1.zip -k demo -t cities_by_country -logDir ./logs --log.verbosity normal --schema.allowMissingFields true -maxConcurrentQueries AUTO -delim , -url unloaded_data -header true -encoding UTF-8 -skipRecords 0 -maxErrors 100
[INFO]  DSBulk is starting please wait ...
Username and password provided but auth provider not specified, inferring PlainTextAuthProvider
A cloud secure connect bundle was provided: ignoring all explicit contact points.
Operation directory: /Users/USERNAME/logs/UNLOAD_20241120-211159-993666
  total | failed | rows/s |  p50ms |  p99ms | p999ms
134,574 |      0 | 31,329 | 308.52 | 603.98 | 603.98
Operation UNLOAD_20241120-211159-993666 completed successfully in 4 seconds.
Checkpoints for the current operation were written to checkpoint.csv.
To resume the current operation, re-run it with the same settings, and add the following command line flag:
--dsbulk.log.checkpoint.file=/Users/USERNAME/logs/UNLOAD_20241120-211159-993666/checkpoint.csv
----
====
+
This command unloads row data from the `cities_by_country` table, and stores it as CSV files within a subsirectory names `unloaded_data` in the same directory where you ran the command.

== Download the {scb-cap}

The xref:astra-db-serverless:drivers:secure-connect-bundle.adoc[] is a zip file containing security credentials and certificates required for secure mutual TLS (mTLS) connection to your {astra_db} database.

Use the `astra db download-scb` command to download the {scb-long} for an {astra_db} database:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in ./scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_dc-1.zip
----
====

By default, the {product} downloads the {scb} to the directory where you run the command using the following naming pattern: `scb_**DATABASE-ID**_**REGION-NAME**.zip`.
For multi-region databases, the {product} downloads a different SCB for each region.

[WARNING]
====
Treat the {scb} the same way you would any other sensitive values, such as passwords or tokens.

The {scb} contains sensitive information that establishes a connection to your database, including key pairs and certificates.
====

=== `db download-scb` options

[source,console]
----
NAME
        astra db download-scb - Download secure connect bundle archive for a
        region

SYNOPSIS
        astra db download-scb [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-f | --output-file} <DEST> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -f <DEST>, --output-file <DEST>
            Destination file

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

Use the `-r`/`--region` option to download the {scb} for a specific region:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_NAME** -r **REGION_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in ./scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_dc-1.zip
----
====

Use the `-f`/`--output-file` option to download the {scb} to a specific location and filename:

[source,bash,subs="+quotes"]
----
astra db download-scb **DATABASE_NAME** -f **DESTINATION_FILE**.zip
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Bundle downloaded in DESTINATION_FILE.zip
----
====

== Create environment variables

When developing applications with {astra_db} APIs, you will notice common values that are frequently reused, such as application tokens, database API endpoints, database IDs, and keyspace names.
It's a good practice to store these values in environment variables to facilitate reuse in your scripts, simplify token rotation, and increase security by keeping sensitive information separate from your core application code.

The {product} can automatically generate a set of relevant variables for an {astra_db} database that you can use in your applications.

Use the `astra db create-dotenv` command to generate a `.env` file containing relevant environment variables for a specific {astra_db} database:

[source,bash,subs="+quotes"]
----
astra db create-dotenv **DATABASE_NAME**
----

By default, the {product} saves the `.env` file to the directory where you run the command.

If a `.env` file already exists in the directory, the {product} appends the new environment variables to the existing file.

.Result
[%collapsible%open]
====
..env
[source,console]
----
ASTRA_DB_API_ENDPOINT="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/json"
ASTRA_DB_APPLICATION_TOKEN="AstraCS:FZm..."
ASTRA_DB_GRAPHQL_URL="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql/demo"
ASTRA_DB_GRAPHQL_URL_ADMIN="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql-admin"
ASTRA_DB_GRAPHQL_URL_PLAYGROUND="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/playground"
ASTRA_DB_GRAPHQL_URL_SCHEMA="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/graphql-schema"
ASTRA_DB_ID="a53003fe-ba42-4c3c-85d0-6b345622c2dc"
ASTRA_DB_KEYSPACE="demo"
ASTRA_DB_REGION="us-east1"
ASTRA_DB_REST_URL="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/rest"
ASTRA_DB_REST_URL_SWAGGER="https://a53003fe-ba42-4c3c-85d0-6b345622c2dc-us-east1.apps.astra.datastax.com/api/rest/swagger-ui/"
ASTRA_DB_SECURE_BUNDLE_PATH="/Users/USERNAME/.astra/scb/scb_a53003fe-ba42-4c3c-85d0-6b345622c2dc_us-east1.zip"
ASTRA_DB_SECURE_BUNDLE_URL="https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/a53003fe-ba42-4c3c-85d0-6b345622c2dc-1/secure-connect-demo.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2AIQRQ76XML7FLD6%2F20241120%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20241120T233147Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=46d8704e382458c82d7da02db1ca79657e003de327f0123a0189ec1a50171cb0"
ASTRA_ORG_ID="2dbd3c55-6a68-4b5b-9155-5be9d41823e8"
ASTRA_ORG_NAME="alice@example.com"
ASTRA_ORG_TOKEN="AstraCS:FZm..."
----
====

[WARNING]
====
The generated `.env` files contains sensitive information, including the application token that the {product} uses to connect to Astra.

The {scb} contains sensitive information that establishes a connection to your database, including key pairs and certificates.
====

=== `db create-dotenv` options

[source,console]
----
NAME
        astra db create-dotenv - Generate an .env configuration file associate
        with the db

SYNOPSIS
        astra db create-dotenv [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ]
                [ {-d | --directory} <DIRECTORY> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ] [ {-r | --region} <DB_REGION> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        -d <DIRECTORY>, --directory <DIRECTORY>
            Destination for the config file

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Default keyspace created with the Db

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -r <DB_REGION>, --region <DB_REGION>
            Cloud provider region

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

Use the `-d`/`--directory` option to save the `.env` file to a specified directory:

[source,bash,subs="+quotes"]
----
astra db create-dotenv **DATABASE_NAME** -d ~/tmp
----

.Result
[%collapsible]
====
[source,console]
----
[OK]    File '/Users/USERNAME/tmp/.env' has been created/amended
----
====

[NOTE]
====
The directory must already exist before you run the command.
If the directory doesn't exist, the {product} will report the following error: `INVALID_ARGUMENT: Destination folder has not been found`.
====

[#cdc]
== Change Data Capture (CDC)

[IMPORTANT]
====
CDC for {astra_db} incurs billed charges based on your {astra_stream} usage.
For more information, see https://www.datastax.com/pricing/astra-streaming[{astra_stream} pricing] and https://www.datastax.com/products/datastax-astra/cdc-for-astra-db[CDC metering rates].
====

CDC for {astra_db} automatically captures changes in real time, de-duplicates the changes, and then streams the clean set of changed data into xref:astra-streaming:ROOT:index.adoc[{astra_stream}] where it can be processed by client applications or sent to downstream systems.

Use the `astra db create-cdc` command to create a CDC connection for a table in a {db-serverless} database:

[source,bash,subs="+quotes"]
----
astra db create-cdc **DATABASE_NAME** \
    -k **KEYSPACE_NAME** \
    --table **TABLE_NAME** \
    --tenant **TENANT_NAME**
----

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

Use the `astra db list-cdc` command to list the CDC connections for a specifc database:

[source,bash,subs="+quotes"]
----
astra db list-cdc **DATABASE_NAME**
----

.Result
[%collapsible]
====
[source,console]
----
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| id                    | keyspace          | table          | tenant         | cluster            | namespace      | Status         |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| 57a3024f-cdcdemotable | cdc_demo_keyspace | cdc_demo_table | cdc-demo-tenant| pulsar-aws-useast1 | astracdc       | Running        |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
----
====

Use the `astra db delete-cdc` command to delete a CDC connection for a specific table:

[source,bash,subs="+quotes"]
----
astra db delete-cdc **DATABASE_NAME** \
    -k **KEYSPACE_NAME** \
    --table **TABLE_NAME** \
    --tenant **TENANT_NAME**
----

////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

=== `db create-cdc` options

[source,console]
----
NAME
        astra db create-cdc - Create a CDC to pulsar

SYNOPSIS
        astra db create-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ {-k | --keyspace} <KEYSPACE> ] [ --no-color ]
                [ {-o | --output} <FORMAT> ]
                [ -p, --partition <PARTITION TOKEN> ] [ --table <TABLE> ]
                [ --tenant <TENANT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        -p, --partition <PARTITION TOKEN>
            Paritions in the topics

        --table <TABLE>
            Table name

        --tenant <TENANT>
            Tenant name

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db list-cdc` options

[source,console]
----
NAME
        astra db list-cdc - List CDC available on this databse

SYNOPSIS
        astra db list-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ]
                [ --token <AUTH_TOKEN> ] [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== `db delete-cdc` options

[source,console]
----
NAME
        astra db delete-cdc - Delete a CDC connection

SYNOPSIS
        astra db delete-cdc [ {-cf | --config-file} <CONFIG_FILE> ]
                [ {-conf | --config} <CONFIG_SECTION> ] [ --env <Environment> ]
                [ -id <CDC_ID> ] [ {-k | --keyspace} <KEYSPACE> ]
                [ --no-color ] [ {-o | --output} <FORMAT> ] [ --table <TABLE> ]
                [ --tenant <TENANT> ] [ --token <AUTH_TOKEN> ]
                [ {-v | --verbose} ] [--] <DB>

OPTIONS
        -cf <CONFIG_FILE>, --config-file <CONFIG_FILE>
            Configuration file (default = ~/.astrarc)

        -conf <CONFIG_SECTION>, --config <CONFIG_SECTION>
            Section in configuration file (default = ~/.astrarc)

        --env <Environment>
            Astra Environment to use

        -id <CDC_ID>
            Identifier of the cdc when providing

        -k <KEYSPACE>, --keyspace <KEYSPACE>
            Keyspace name

        --no-color
            Remove all colors in output

        -o <FORMAT>, --output <FORMAT>
            Output format, valid values are: human,json,csv

        --table <TABLE>
            Table name

        --tenant <TENANT>
            Tenant name

        --token <AUTH_TOKEN>
            Key to use authenticate each call.

        -v, --verbose
            Verbose mode with log in console

        --
            This option can be used to separate command-line options from the
            list of arguments (useful when arguments might be mistaken for
            command-line options)

        <DB>
            Database name (if unique) or Database identifier
----

=== End-to-end example

The following end-to-end example shows how to use the {product} to create a CDC connection for a table in a {db-serverless} database:

. Create an {astra_db} {db-serverless} database:
+
[source,bash]
----
astra db create cdc_demo_db \
    -c aws \
    -r us-east-1 \
    -k cdc_demo_keyspace
----
+
.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'cdc_demo_db' does not exist. Creating database 'cdc_demo_db' with keyspace 'cdc_demo_keyspace'
get CLoud provider
[INFO]  Database 'cdc_demo_db' and keyspace 'cdc_demo_keyspace' are being created.
[INFO]  Database 'cdc_demo_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'cdc_demo_db' has status 'ACTIVE' (took 112117 millis)
[OK]    Database 'cdc_demo_db' is ready.
----
====

. Create an {astra_stream} tenant in the same region as your database:
+
[source,bash]
----
astra streaming create cdc-demo-tenant \
    -c aws \
    -r useast1
----
+
.Result
[%collapsible]
====
[source,console]
----
https://api.astra.datastax.com/v2/streaming/tenants/cdc-demo-tenant
[OK]    Tenant 'cdc-demo-tenant' has being created.
----
====

. Use the xref:ROOT:managing.adoc#cqlsh[CQL shell] to create a table with a primary key column in your database.
+
[source,bash]
----
astra db cqlsh cdc_demo_db -e \
"CREATE TABLE IF NOT EXISTS cdc_demo_keyspace.cdc_demo_table ( \
    key text PRIMARY KEY, \
    c1 text \
);"
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
----
====

. Confirm table creation:
+
[source,bash]
----
astra db cqlsh cdc_demo_db -e \
"SELECT * FROM cdc_demo_keyspace.cdc_demo_table"
----
+
.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 key | c1
-----+----

(0 rows)
----
====

. Create a CDC connection.
+
[source,bash]
----
astra db create-cdc cdc_demo_db \
    -k cdc_demo_keyspace \
    --table cdc_demo_table \
    --tenant cdc-demo-tenant
----
+
////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

. Confirm CDC details for the database and tenant.
+
[source,bash]
----
astra db list-cdc cdc_demo_db
----
+
.Result
[%collapsible]
====
[source,console]
----
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| id                    | keyspace          | table          | tenant         | cluster            | namespace      | Status         |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| 57a3024f-cdcdemotable | cdc_demo_keyspace | cdc_demo_table | cdc-demo-tenant| pulsar-aws-useast1 | astracdc       | Running        |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
----
====
+
[source,bash]
----
astra streaming list-cdc cdc-demo-tenant
----
+
.Result
[%collapsible]
====
[source,console]
----
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| cluster            | namespace      | database       | keyspace          | table          | status         |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| pulsar-aws-useast1 | astracdc       | cdc_demo_db    | cdc_demo_keyspace | cdc_demo_table | running        |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
----
====

After you enable CDC on your {db-serverless} database, you can xref:astra-db-serverless:databases:change-data-capture.adoc#connect-a-sink[connect a sink].
