= Change Data Capture (CDC)

CDC for {astra_db} automatically captures changes in real time, de-duplicates the changes, and then streams the clean set of changed data into xref:astra-streaming:ROOT:index.adoc[{astra_stream}] where it can be processed by client applications or sent to downstream systems.

This page describes an end-to-end example showing how to use the {product} to create a CDC connection for a table in a {db-serverless} database.

[IMPORTANT]
====
CDC for {astra_db} incurs billed charges based on your {astra_stream} usage.
For more information, see https://www.ibm.com/docs/en/astra-streaming?topic=astra-streaming-annual-price-plans[{astra_stream} pricing].
====

== Create a database

Create an {astra_db} {db-serverless} database:

[source,shell]
----
astra db create cdc_demo_db \
    -c aws \
    -r us-east-1 \
    -k cdc_demo_keyspace
----

.Result
[%collapsible]
====
[source,console]
----
REGION OK
[INFO]  Database 'cdc_demo_db' does not exist. Creating database 'cdc_demo_db' with keyspace 'cdc_demo_keyspace'
get CLoud provider
[INFO]  Database 'cdc_demo_db' and keyspace 'cdc_demo_keyspace' are being created.
[INFO]  Database 'cdc_demo_db' has status 'PENDING' waiting to be 'ACTIVE' ...
[INFO]  Database 'cdc_demo_db' has status 'ACTIVE' (took 112117 millis)
[OK]    Database 'cdc_demo_db' is ready.
----
====

== Create a streaming tenant

Create an {astra_stream} tenant in the same region as your database:

[source,shell]
----
astra streaming create cdc-demo-tenant \
    -c aws \
    -r useast1
----

.Result
[%collapsible]
====
[source,console]
----
https://api.astra.datastax.com/v2/streaming/tenants/cdc-demo-tenant
[OK]    Tenant 'cdc-demo-tenant' has being created.
----
====

== Create a table in your database

Use `xref:commands:astra-db-cqlsh.adoc[]` to create a table with a primary key column in your database:

[source,shell]
----
astra db cqlsh cdc_demo_db -e \
"CREATE TABLE IF NOT EXISTS cdc_demo_keyspace.cdc_demo_table ( \
    key text PRIMARY KEY, \
    c1 text \
);"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...
----
====

Confirm table creation:
+
[source,shell]
----
astra db cqlsh cdc_demo_db -e \
"SELECT * FROM cdc_demo_keyspace.cdc_demo_table"
----

.Result
[%collapsible]
====
[source,console]
----
[INFO]  Cqlsh is starting, please wait for connection establishment...

 key | c1
-----+----

(0 rows)
----
====

== Create a CDC connection

Use `xref:commands:astra-db-create-cdc.adoc[]` to create a CDC connection between your database table and streaming tenant:

[source,shell]
----
astra db create-cdc cdc_demo_db \
    -k cdc_demo_keyspace \
    --table cdc_demo_table \
    --tenant cdc-demo-tenant
----
+
////
// TODO: The command is not working as expected. Must investigate and figure out why it is reporting the following error: [ERROR] INVALID_ARGUMENT: Error Code=422(422) Invalid information provided to create DB: 422 Unprocessable Entity: databaseId, keyspace, tableName, and orgId are mandatory fields
.Result
[%collapsible]
====
[source,console]
----

----
====
////

Use `xref:commands:astra-db-list-cdcs.adoc[]` to confirm CDC details for the database and tenant:

[source,shell]
----
astra db list-cdcs cdc_demo_db
----

.Result
[%collapsible]
====
[source,console]
----
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| id                    | keyspace          | table          | tenant         | cluster            | namespace      | Status         |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
| 57a3024f-cdcdemotable | cdc_demo_keyspace | cdc_demo_table | cdc-demo-tenant| pulsar-aws-useast1 | astracdc       | Running        |
+-----------------------+-------------------+----------------+----------------+--------------------+----------------+----------------+
----
====

[source,shell]
----
astra streaming list-cdc cdc-demo-tenant
----

.Result
[%collapsible]
====
[source,console]
----
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| cluster            | namespace      | database       | keyspace          | table          | status         |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
| pulsar-aws-useast1 | astracdc       | cdc_demo_db    | cdc_demo_keyspace | cdc_demo_table | running        |
+--------------------+----------------+----------------+-------------------+----------------+----------------+
----
====

== Connect a sink

After you enable CDC on your {db-serverless} database, you're ready to xref:astra-streaming:developing:astream-cdc.adoc#connect-a-sink[connect a sink].
